### ISSUE TITLE
Trigger a Power BI dataset from a Data Factory Pipeline

### ISSUE THREAD

**Issue by CTsiaras** [MicrosoftDocs/powerbi-docs#1098]
To fully integrate our Data Factory pipelines and our Power BI reports we should be able to trigger a data set update from a Data Factory Pipeline. Thus, it would be nice to have a simpler authentication method e.g., via MSI like we do to start an Azure SSIS integration runtime. If you do it then please provide a proper example with some print screens etc. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @CTsiaras. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
