### ISSUE TITLE
Still Missing Elements

### ISSUE THREAD

**Issue by HenryIppolito** [MicrosoftDocs/powerbi-docs#1105]
Still waiting on some missing elements to be documents above. Where is the +/- Icon for Matrix Row Header? Under Matrix and Tables &gt; Field Formatting, I cannot alter the Value Decimal Place default. Are data driven format defaults ever going to be available (Matrix &gt; Conditional formatting &gt; Font Color)? Considering the defaults exist, we should have some sort of option to alter the defaults.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#feedback)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @HenryIppolito. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
