### ISSUE TITLE
Ability to sync filters across multiple report pages

### ISSUE THREAD

**Issue by chrispaquet** [MicrosoftDocs/powerbi-docs#1117]
in the same way as sync slicers.

**Comment by mgblythe** [comment]
Thanks for your comment, @chrispaquet. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
