### ISSUE TITLE
Missing discussion on the effect on Premium Memory

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#1124]
This page is Missing discussion on the effect on Premium Memory if your resources are already stretched. What happens if we set too many Datasets to use Query Caching. Will other Datasets be starved for the memory resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13962e5-2d39-a6cd-274c-2317477acc22
* Version Independent ID: 099fe9f8-0c2b-b359-b761-251587a0ab76
* Content: [Query caching in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching)
* Content Source: [powerbi-docs/power-bi-query-caching.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-query-caching.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @pcgeekus. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @pcgeekus -- thanks for your question! I'm adding @Bhavik-MSFT to the conversation. He's the best person to answer you.

**Comment by Bhavik-MSFT** [comment]
Hi @pcgeekus , great question! We've designed Query Caching to have a negligible effect on capacity memory even if you have turned it on for many datasets. You may see temporary load on the capacity when the cache is refreshed since we need to issue queries to the underlying data models. The effect of this depends on the number and complexity of the cached queries. If you have a capacity that is already under heavy load, the cache refresh may affect general performance since it adds additional load.

**Comment by pcgeekus** [comment]
It was my understanding that our capacity already caches heavier used
queries. What's different in using this setting and what tells me I should
consider it for a particular Dataset?

Jon

**Comment by Bhavik-MSFT** [comment]
@pcgeekus By default the capacity will cache dashboard tiles (i.e. the final pinned visual) and visuals on the default page of reports. Query Caching will also put query results in the cache. For reports that are slow because of high query duration in proportion to visual drawing time, turning Query Caching on will give you the most benefit. You can determine this timing using the new [Desktop Performance Analyzer](https://docs.microsoft.com/en-us/power-bi/desktop-performance-analyzer)
