### ISSUE TITLE
Size Range limitation

### ISSUE THREAD

**Issue by dannodj** [MicrosoftDocs/powerbi-docs#1132]
It would be useful to add a comment on the size limitation of pinning excel ranges to a dashboard, please can you state the maximum cell range that can be pinned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458afd24-a62a-7944-5cd4-de9a9290c308
* Version Independent ID: ed6a56f0-e067-9f92-5d54-6755b49f3bc0
* Content: [Using Power BI publisher for Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/publisher-for-excel#feedback)
* Content Source: [powerbi-docs/publisher-for-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/publisher-for-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @dannodj. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks @dannodj - are you running into specific issues with the amount you can pin? I believe you would run into a situation where the range is unreadable (because too many cells are selected) long before you'd run into trouble on the technical capacity (maximum size limitation) for pinning. I'll close this, but if you've run into a specific limitation, please re-comment and I'll look deeper.
