### ISSUE TITLE
monitor SSAS tabular model datasets

### ISSUE THREAD

**Issue by johnyuan10** [MicrosoftDocs/powerbi-docs#1161]
Hi, 

Can the capacity metrics monitor be used to monitor SSAS tabular model based datasets? If so, how can I view it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c913b90d-071a-7be0-6652-4b1b024e7f45
* Version Independent ID: bc99d496-cf13-552b-b6df-55229ad9ff1d
* Content: [Deploying and Managing Power BI Premium Capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-powerbi-premium-deployment#exploring-real-world-scenarios)
* Content Source: [powerbi-docs/whitepaper-powerbi-premium-deployment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-powerbi-premium-deployment.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @johnyuan10 -- thanks for your question! Assigning it to the author to get back to you.

**Comment by swgupt** [comment]
@johnyuan10 , Yes for import and No for Live connect. To elaborate If you are selecting items and importing data from SSAS tabular based datasets into Power BI Service, you will be able to use the metrics app to be able to monitor. When connecting live, no data from the Tabular model is imported into Power BI Desktop. Each time you interact with a visualization,Power BI Desktop queries the Tabular model and calculates the results you see. You’re always looking at the latest data that is available in the Tabular model, either from the last processing time, or from Direct Query tables available in the Tabular Model. Since all the calculation is done on the other side of gateway and not in premium , we do not report any metrics in the premium app.

**Comment by johnyuan10** [comment]
@swgupt, the CPU usage in the capacity monitor app is for the overall or for back end only? Thanks.

**Comment by mgblythe** [comment]
@johnyuan10 - it's for overall not just back end.
