### ISSUE TITLE
USEREALTIONSHIP BREAKS

### ISSUE THREAD

**Issue by thesqlgeek** [MicrosoftDocs/powerbi-docs#118]
When using RLS in SSAS you can no longer use the DAX USEREALTIONSHIP command.  An error orccurs.  This needs to be documented.  I am a MSFT Employee and we have a few customers that are running into this once implementing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15bd37b-39fb-3d45-029c-1bb01c7b4cf1
* Version Independent ID: 6746499b-661f-a3c9-dbd6-8501c7a3bbec
* Content: [Dynamic row level security with Analysis services tabular model in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tutorial-row-level-security-onprem-ssas-tabular)
* Content Source: [powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tutorial-row-level-security-onprem-ssas-tabular.md)
* Service: **powerbi**
* GitHub Login: @selvarms
* Microsoft Alias: **selvar**

**Comment by maggiesMSFT** [comment]
Hi, @thesqlgeek -- Thanks! I'll share your feedback with the author, @selvarms.

**Comment by mgblythe** [comment]
I added the following to the article where DAX is first mentioned. Should be live 10/26:

    > [!IMPORTANT]
    > Be aware that the DAX function [USERELATIONSHIP](https://msdn.microsoft.com/query-bi/dax/userelationship-function-dax) is not supported when using row level security.

@Minewiskan - please add a note to the remarks section of the reference.

**Comment by Minewiskan** [comment]
@mgblythe Added a remark to https://docs.microsoft.com/en-us/dax/userelationship-function-dax.

**Comment by mgblythe** [comment]
Thanks @Minewiskan. @thesqlgeek - closing this one, thanks for filing it.

**Comment by danieljsc** [comment]
Hi,

Digged for the RLS and USERELATIONSHIP for hours. Are there any news about this topic?
What are the alternatives proposed by Microsoft for the Multidimensional Role Playing Dimensions equivalent?
At the moment I have a very complex model (Multi Tenant) developed, with multple measures using USERELATIONSHIP. I am not expecting to hear from Microsoft that the behaviour of SSAS will be fixed or changed, but is there any workaround to avoid this? What does Microsoft suggests to do in the case we have inactive relationships?
Please take into consideration that I already have Role Playing Dimensions implemented in my Model. I only have inactive relations because I was also using 1 table connected to multiple columns of another table, so that in Power BI Dashboard I had only one slicer for that dimension, instead having 2 slicers for the same dimension filtering different columns on the fact table.

Waiting to hear back from you guys.

Best regards.
