### ISSUE TITLE
SAS OLE DB Performance Issues

### ISSUE THREAD

**Issue by C2BB** [MicrosoftDocs/powerbi-docs#1193]
Usage note for SAS OLE DB Performance Issues: http://support.sas.com/kb/63/340.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df452d2e-9a96-a9cb-40a7-830d6282c68b
* Version Independent ID: 1f84e9ab-409e-59fc-d35a-dc66f3d6bcb3
* Content: [Connect to data using generic interfaces in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-using-generic-interfaces#feedback)
* Content Source: [powerbi-docs/desktop-connect-using-generic-interfaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-using-generic-interfaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by C2BB** [comment]
Can this be fixed? The issue does not occur using Excels legacy OLE DB connection.

**Comment by maggiesMSFT** [comment]
Hi, @C2BB -- Thanks for asking. I recommend that you start with the Power BI support site, https://powerbi.microsoft.com/en-us/support/, to see if they have an answer.

**Comment by davidiseminger** [comment]
Thanks for your comment, @C2BB . Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
