### ISSUE TITLE
Connecting to Databricks using the Spark Connector

### ISSUE THREAD

**Issue by isamllr** [MicrosoftDocs/powerbi-docs#1204]
Are there any known issues when connecting to the NoPublicIP private preview of Databricks?
Is there any guidance on network setup? Happy if you can put me in touch with a knowledgeable contact. 
Thanks,
Isa

**Comment by mihart** [comment]
Thanks for your comment, @isamllr. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. You'll be able to find a knowledgeable contact either of these sites.
