### ISSUE TITLE
Zendesk API

### ISSUE THREAD

**Issue by cwootttttt** [MicrosoftDocs/powerbi-docs#1209]
Need to be able to run reports on custom fields and tags assigned to the tickets. Is this able to be added?

**Comment by mgblythe** [comment]
Thanks for your comment, @cwootttttt. This looks like  a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
