### ISSUE TITLE
Can't Administer Subscriptions

### ISSUE THREAD

**Issue by Saltzmea** [MicrosoftDocs/powerbi-docs#1222]
I need the ability to manage Subscriptions and Alerts using the API for all workspaces. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830da8e8-8526-0e6a-d83f-0c804226e006
* Version Independent ID: 3e7b9d31-133d-1b2f-fded-d9218284155b
* Content: [Subscribe yourself and others to reports and dashboards - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-report-subscribe)
* Content Source: [powerbi-docs/service-report-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-report-subscribe.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Saltzmea. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
