### ISSUE TITLE
no list of the data types

### ISSUE THREAD

**Issue by codingsolutions** [MicrosoftDocs/powerbi-docs#1229]
it doesn't list the data types so I can make it an int instead of decimal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83479d4-0fb8-7500-e6ec-5559c4e2fdae
* Version Independent ID: 23b93f03-3ab9-d658-4243-89ebebbd6796
* Content: [Data types in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-types#feedback)
* Content Source: [powerbi-docs/desktop-data-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-types.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @codingsolutions . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment, @codingsolutions. Sorry you're running into difficulty, this looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
