### ISSUE TITLE
Grant the Power BI service a reader role

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/powerbi-docs#1263]
In Add Role assignment. what or which Power BI Service should I referring to ?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @axaeffect. I've assigned this issue to the doc author for review.

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@axaeffect  You grant the Power BI service a reader roles as follows:
Go to Subscriptions => Select your subscription.
Go to Access control (IAM) => Add
Role: Reader
Assign access to: Azure AD users, groups, or service principal
Select Power BI Service and Save.

![image](https://user-images.githubusercontent.com/44426401/63406220-dd1ca280-c406-11e9-9a8f-c35ba84d69cb.png)


Hope this helps.

**Comment by axaeffect** [comment]
Hi, it's not really help since the confusion is, what Power BI Service does it refer to ?
How we create this Power BI Services? For all the steps precedes it, cleared to me.
Thanks,

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@axaeffect For my subscription, by default  "Power BI Service" is registered in Enterprise application.
To check on your subscription: Go to Azure Active Directory => Manage => Enterprise applications => Power BI Service

![image](https://user-images.githubusercontent.com/44426401/63993204-04612700-cb0d-11e9-800c-d889d2b5abfc.png)

In case, if it not registered, you can follow these steps.

There are two ways to register your application. The first is with the [Power BI App Registration Tool](https://dev.powerbi.com/apps), or you can do it directly within the [Azure portal](https://docs.microsoft.com/en-us/power-bi/developer/register-app#register-with-the-azure-portal). The Power BI App Registration Tool is more convenient to use since there are just a few fields to complete. Use the Azure portal if you want to make changes to your app.

For more details, refer "[Register an Azure AD Application to use with Power BI](https://docs.microsoft.com/en-us/power-bi/developer/register-app)".

Hope this helps.

**Comment by davidiseminger** [comment]
Looks like this is resolved, thanks for the discussion.
