### ISSUE TITLE
Get Power BI Roles list API is missing

### ISSUE THREAD

**Issue by RanjithPC** [MicrosoftDocs/powerbi-docs#1287]
Hi,

My concern is how can I get list of created roles in power BI using api. There is no api have to get roles list.

https://docs.microsoft.com/en-us/rest/api/power-bi/

**Comment by mgblythe** [comment]
Thanks for your comment, @RanjithPC. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
