### ISSUE TITLE
Powerbi directquery for postgresql

### ISSUE THREAD

**Issue by sunnn** [MicrosoftDocs/powerbi-docs#1295]
Hi can we get direct query connection to greenplum and postgres related dv

**Comment by mgblythe** [comment]
Thanks for your comment, @sunnn. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
