### ISSUE TITLE
Getting control over report pages using Query Chashing

### ISSUE THREAD

**Issue by schuffa** [MicrosoftDocs/powerbi-docs#1300]
Hello, I learned from your support page (https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching) that only the landing page of a report is cashed. In a given case of a more complex manegement report in my enterprise enviornment, it would also be great as report / capacity admin to gain control over which specific report pages are to be cashed (and which not). As I learned from this comment here (https://github.com/MicrosoftDocs/powerbi-docs/issues/1124) there should'nt be much effect on the capcity doing this, right? And even though it would, as capacity owner the transparency about the respective memnory consumption (e.g. in the Capacity Metric App) would be than helpful to manage this function as capacity admin adequately.

**Comment by mgblythe** [comment]
Thanks for your comment, @schuffa. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
