### ISSUE TITLE
Color Gradient with divergence

### ISSUE THREAD

**Issue by sarava8304** [MicrosoftDocs/powerbi-docs#1320]
[It would be better if we can accomodate multiple divergence colors, instead of only 1 in settings. So, that it will be help full to show the visual for top 10 CUstomer reports, there may be five diverging colors and it would be help full to highlight the values more predominant]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Tips and tricks for color formatting in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting)
* Content Source: [powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @sarava8304.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
