### ISSUE TITLE
Invalid Expression

### ISSUE THREAD

**Issue by dsujs** [MicrosoftDocs/powerbi-docs#1321]
Power BI Version: 2.71.5523.941 64-bit (July 2019)

CustomFiscalPeriods = 
DATATABLE (
    "Fiscal YearNumber", INTEGER,
    "FirstDayOfYear", DATETIME,
    "LastDayOfYear", DATETIME,
    {
        { 2016, "2015-06-28", "02-07-2016" },
        { 2017, "03-07-2016", "2017-07-01" },
        { 2018, "02-07-2017", "2018-06-30" },
        { 2019, "01-07-2018", "2019-06-29" }
    }
)

The syntax for "2015-08-16" is invalid.

I tested with Power-BI versions of July and May as well what gives the same error message!
My Input method is:
English (United States) and Belgian (Period) keyboard.

**Comment by dsujs** [comment]
I tested the Power-BI June and May version as well. It gives the same problem as well.

Input methods are English (United States) and Belgian (Period) Keyboard.

**Comment by mgblythe** [comment]
Thanks for your comment, @dsujs. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
