### ISSUE TITLE
Row Partitioning

### ISSUE THREAD

**Issue by saviourofdp** [MicrosoftDocs/powerbi-docs#1404]
Is there any more detail explanation of the Row Partitioning? I need to know if this helps or otherwise what happens with a large initial datasets. Are there optimal ranges? What happens when a PBIX is republished? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @saviourofdp. I’ll add this request to our docs backlog.
In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by christianwade** [comment]
Hi @saviourofdp there will be more info made available with XMLA read write because there will be more you can do like manually refreshing old partitions that were generated by incremental refresh. You can already see the partitions generated in SSMS as shown by this video:https://youtu.be/LiQCc0A9coA?t=3719

Currently when you upload a new PBIX, you lose the historical data. With XMLA endpoints read/write, you will have the option to avoid this

**Comment by mgblythe** [comment]
Thanks @christianwade - closing this one out.
