### ISSUE TITLE
Need 13 months

### ISSUE THREAD

**Issue by TheSaltyKorean** [MicrosoftDocs/powerbi-docs#1421]
While I understand a limit on the data being pulled back, we actually need 13 complete months not just 12.  Doing a month to last year's month is extremely important.  (This means we could be in month 14)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Analyze Azure cost and usage data in Power BI desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @TheSaltyKorean. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
