### ISSUE TITLE
Report View disappears when manipulating table data

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/powerbi-docs#1448]
There doesn't appear to be any way to get Report Viewer back once it's gone.  I went to edit table data and now the left-navigation just shows tables.  But, I want the left-navigation that defaults on Power BI Desktop when opening existing Power BI file.

"You can switch between Report View, Data View, and Relationship View by selecting the icons in the left-hand navigation bar:"  How do users get this view back if it disappears.  This has happened a few times.

May also be worth mentioning this on this page since it's the only page "Report View" is discussed, seemingly.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f750471-143b-f0fe-3d92-0bdaaa06dcc1
* Version Independent ID: 66cc67fb-28ff-4a0c-34f0-f688369cc15c
* Content: [Report View in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-view#feedback)
* Content Source: [powerbi-docs/desktop-report-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @awentzel . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting @awentzel - I haven't seen or heard of the Report view disappearing (it is a selection found on the left side of the canvas), so it appears this may be a support issue that should be taken up, for further investigation, rather than a documentation issue. 

You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
