### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by TheBrain75** [MicrosoftDocs/powerbi-docs#1464]
Regarding... 

Question: If I created a live connection, is it secure?

Answer: Yes. Your current Windows credentials are used to connect to the Analysis Services server. You cannot use Basic or stored credentials in either the Power BI service or Power BI Desktop when exploring live.

...

Why no option for alternate credentials, even if not stored?  I have users on a separate domain from my tabular server, so PowerBI will not allow a live connection.  This works in Excel and in Tableau, but not Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4defd9-aeac-2135-1310-332bfe227342
* Version Independent ID: c68cb581-46fc-5b74-aff1-8a69dbf433dc
* Content: [Using Analysis Services Tabular data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-analysis-services-tabular-data#feedback)
* Content Source: [powerbi-docs/desktop-analysis-services-tabular-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-analysis-services-tabular-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @TheBrain75. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
