### ISSUE TITLE
not able to switch between pages

### ISSUE THREAD

**Issue by N-avi-N** [MicrosoftDocs/powerbi-docs#1471]
When I try to move from one page to other by selecting tabs at the bottom , the page remains the same but the tab changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f750471-143b-f0fe-3d92-0bdaaa06dcc1
* Version Independent ID: 66cc67fb-28ff-4a0c-34f0-f688369cc15c
* Content: [Report View in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-view#feedback)
* Content Source: [powerbi-docs/desktop-report-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hello @N-avi-N - that isn't the expected behavior, and without more information it's difficult to determine why it might be behaving that way. This forum is only for documentation suggestions and questions. 
Your best bet for getting help with support issues (or unexpected behavior issues) such as this is to visit the community site at https://community.powerbi.com and ask if others have seen this, or you can get support by going to https://support.powerbi.com.
