### ISSUE TITLE
Export functionality not working after embedding for customers (Apps Owns) 

### ISSUE THREAD

**Issue by vinoddamupatil** [MicrosoftDocs/powerbi-docs#1473]
Hi,

Export functionality not working after embedding for customers (Apps Owns).  

We want to export it as same features available in Power BI service such as excel or csv for particular visual.

Is there any solution for embedded reports.

Thanks,
Vinod Patil

**Comment by maggiesMSFT** [comment]
Hi, @vinoddamupatil -- is this the article you're referring to? 
https://docs.microsoft.com/en-us/power-bi/developer/embedding#embedding-for-your-customers
Assigning to the author of that article to see if they can help.

**Comment by KesemSharabi** [comment]
Hi @vinoddamupatil,

The export functionality should work when using the embedding for customers solutions.

Your question looks like a support request rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
