### ISSUE TITLE
Still missing elements

### ISSUE THREAD

**Issue by alexander-korn** [MicrosoftDocs/powerbi-docs#1511]
Hello MS Team, this functionality is a huge help, 
unfortunately action buttons and more importantly toggles for visual headers are still missing. When will that be added?
What about custom visual, when will that be fully available for non-standard formatting options?
thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @alexander-korn, and for your nice comments about our Themes feature set. Looks like this is product feedback, however, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by alexander-korn** [comment]
Thanks David for your fast response. 
Just verifying: Is https://ideas.powerbi.com actually meant to be for addressing incomplete implementation of Microsoft (states of buttons and toggles for visual header)?
