### ISSUE TITLE
Cannot use filter with rs:embed=true

### ISSUE THREAD

**Issue by UteMan3431** [MicrosoftDocs/powerbi-docs#1513]
Would love to use a filter along with the embed parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters#feedback)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @UteMan3431 This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
