### ISSUE TITLE
Bookmarks Bug - September Release

### ISSUE THREAD

**Issue by jwademcg** [MicrosoftDocs/powerbi-docs#1514]
This issue doesn't happen for bookmarks on reports published from desktop that I had published before installing the September PBI Desktop.

For September release: appears that the bookmarks (both desktop and personal) are not saving the data for cross highlights on desktop or once published to the service.  It "looks" like it save as in the cross highlights are selected but the data is showing as if nothing is cross highlighted.  If you click the bookmark twice it works or if you are on another page of the report and click the bookmark it seems to work correctly, but not if you are already on the page or navigate to the page fresh in the browser from the url with the bookmark guid included.

Also, bigger issue, happening at the same time as the other issue: personal bookmarks do not even show up when you first load the report from the apps page; they only appear after you navigate to a different page in the same report.  Clearing cache and cookies the issue remains, snapshot below

initially pasted wrong image sorry here is the correct one:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/42750785/66854657-605dfe80-ef47-11e9-8566-173f8e36d2fe.png)

**Comment by srigney2142** [comment]
Thanks for your comment, @jwademcg  This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com). 

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @jwademcg -- closing this issue. It does indeed look like a support request. I hope you can get it working!
