### ISSUE TITLE
Control/Remove table(s) from Q&A scope

### ISSUE THREAD

**Issue by bartoszwmalec** [MicrosoftDocs/powerbi-docs#1522]
I have raised an Idea on forum in order to give more control over the Q&A tool: https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/38831542-q-a-possibility-to-control-remove-table-s-from

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f8e2480-703a-1417-c5d9-8d019669f45a
* Version Independent ID: 17a9f60e-b9b6-8426-2176-86b5ec3cb68f
* Content: [Q&A for Power BI consumers - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-q-and-a#feedback)
* Content Source: [powerbi-docs/consumer/end-user-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-q-and-a.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by srigney2142** [comment]
Thanks for your comment, @bartoszwmalec This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @bartoszwmalec -- you did the right thing by adding the idea in the forum! Closing this issue
