### ISSUE TITLE
Data Capacity

### ISSUE THREAD

**Issue by wechuli** [MicrosoftDocs/powerbi-docs#1545]
"When the dataset is created, the Power BI service automatically creates a new database in the service to store the data. Since there is an underlying database that continues to store the data as it comes in, reports can be created with the data"

How large a data will the push dataset hold and for how long is it retained ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-real-time-streaming)
* Content Source: [powerbi-docs/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-real-time-streaming.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srigney2142** [comment]
Thanks for your comment, @wechuli This looks like a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by mgblythe** [comment]
Thanks @wechuli - I assigned to the author to review and potentially add to the docs.
