### ISSUE TITLE
Granting access to reports

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/powerbi-docs#156]
@DaveRuijter commented on [Sat Jul 14 2018](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/3)

You suggest granting users access to the report by pinning a visual to a dashboard and sharing that dashboard. Since we now can share reports directly, probably that's a better suggestion.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Insluiten met webonderdeel Rapport in SharePoint Online - Power BI](https://docs.microsoft.com/nl-nl/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

---

@markingmyname commented on [Mon Jul 30 2018](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/3#issuecomment-408895115)

Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

---

@markingmyname commented on [Mon Jul 30 2018](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/3#issuecomment-408895647)

Thank you for your feedback! We will investigate and review if we need to change/add the information suggested

**Comment by LisandroSu** [comment]
Hi team,

Can you check on the issue reported by the user? 

Thanks!

**Comment by markingmyname** [comment]
@DaveRuijter  Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@DavidRuijter It can be a better suggestion. It all depends on the situation.

**Comment by DaveRuijter** [comment]
> @DavidRuijter It can be a better suggestion. It all depends on the situation.

@markingmyname actually, in this case, it's only a good suggestion to direct people to share the report directly, as I proposed. The suggestion to pin something on a dashboard and then share that dashboard might work, but it is not a good suggestion. Keep the end-user in mind! he/she will get a useless dashboard shared with him.. And, since we can't embed dashboards in SharePoint Online, this dashboard will not be used there also. So suggesting to create a useless dashboard, while a direct share of the report itself is now possible, does not make any sense.
It might seem like a small and unimportant thing, but a lot of users stumble upon the permissions needed to successfully embed a Power BI report in a SharePoint Online page. Let's iron out this little flaw and direct them to right way of doing things.
