### ISSUE TITLE
Supported data sources for query folding in Incremental refresh for Power BI.

### ISSUE THREAD

**Issue by akosiaxis** [MicrosoftDocs/powerbi-docs#1562]
Do we have a list of all data sources supported for Incremental Refresh for Power BI?

**Comment by srigney2142** [comment]
Thanks for your comment, @akosiaxis  This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by mgblythe** [comment]
Assigning to @christianwade to address.

**Comment by christianwade** [comment]
Given that there are many different causes for not folding queries including source system capabilities, which change, we were unable to provide a definitive list of data sources that "do" or "don't" support query folding required for incremental refresh. All the information we were able to provide is here: https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#query-folding
#please-close

**Comment by TarekSalha** [comment]
To me the documentation reads like even if a source does NOT provide query folding like a flat file, incremental refresh can still be set up. It is just useless.
Thus, I think it is valid feedback to include a statement about supported data sources. From the documentation I would assume, that ALL sources supporting import mode are supported with incremental refresh.
