### ISSUE TITLE
RLS Enforced for All Members

### ISSUE THREAD

**Issue by dtouseullcc** [MicrosoftDocs/powerbi-docs#1563]
Are there any future plans to be able to designate that Power BI Desktop Roles to be enforced for ALL users regardless what type of membership they have (i.e. non-read only such as Admin; Member; Contributor in new workspaces).  The lack of this support opens holes/risks for human error.

**Comment by srigney2142** [comment]
Thanks for your comment, @dtouseullcc  This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
