### ISSUE TITLE
please upvote: #PowerBI #Idea Composite models when connected to SQL Server Analysis Services Tabular (SSAS) 

### ISSUE THREAD

**Issue by JJDE** [MicrosoftDocs/powerbi-docs#1605]
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/34922932-composite-models-when-connected-to-sql-server-**bleep

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models#feedback)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @JJDE.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
