### ISSUE TITLE
French regions

### ISSUE THREAD

**Issue by louissalome** [MicrosoftDocs/powerbi-docs#1606]
Much appreciated updates on shape maps with new Europeans countries !
About France, the French parliament passed a law reducing the number of metropolitan regions from 22 to 13 effective 1 January 2016. It would be great to have this up-to-date division otherwise our visualizations look outdated.
PS : There is a mispelling in the id "Ile-del-France" -> "Ile-de-France".

**Comment by maggiesMSFT** [comment]
Hi, @louissalome -- thanks for the feedback! Clearly you are referring to a specific article, but I'm not seeing that info. Could you specify? 
thanks!

**Comment by louissalome** [comment]
Sorry, this is about powerbi-docs/powerbi-docs/visuals/desktop-shape-map.md section "France: Regions"

**Comment by paulinbar** [comment]
Thanks for your comment, @louissalome . This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @louissalome -- thanks for clarifying!

**Comment by mihart** [comment]
Hi @louissalome, 
I'm updating the article for the new regions. Do you have any pointers to the official ID, name, and name-en for the new regions?

**Comment by mihart** [comment]
Hi @louissalome ,
I have raised this as a product issue. The product team will add this to their backlog. Thank you for bringing this to our attention,
- Michele
