### ISSUE TITLE
Filters menu / full screen behavior via url parameter

### ISSUE THREAD

**Issue by bjhulst** [MicrosoftDocs/powerbi-docs#1661]
Hi,

Besides add a query into the URL parameters, is it possible to set the report to full-screen and/or disable/enable the filter menu ?

https://docs.microsoft.com/en-us/power-bi/service-url-filters 

for example:

app.powerbi.com/groups/me/apps/app-id/reports/report-id/ReportSection?filter=Table/Field eq 'value&'ctid=ctid&fullscreen=true

or

app.powerbi.com/groups/me/apps/app-id/reports/report-id/ReportSection?filter=Table/Field eq 'value&'ctid=ctid&filtermenu=false

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bjhulst.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @bjhulst ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
