### ISSUE TITLE
How to use custom URI in PowerBI?

### ISSUE THREAD

**Issue by FearL0rd** [MicrosoftDocs/powerbi-docs#1666]
I have created a windows application that has a custom URI to open the app with parameters. How do a add in powerbi a hyperlink to a custom URI?

example:
myAPPapi://?USER=BLABLA&OBJECT=OBJ01

**Comment by paulinbar** [comment]
Hi @FearL0rd , where exactly are you trying to add the URI? Can you provide a bit more information about your scenario?

**Comment by paulinbar** [comment]
Hi, @FearL0rd. I haven't heard back from you, so I am going to close this issues for  now. In any event, since you didn't mention a specific document (you've reached the documentation team) this looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If you don't find anything there, try our [support page](https://support.powerbi.com). Good luck!
