### ISSUE TITLE
trend axis label

### ISSUE THREAD

**Issue by WolffM** [MicrosoftDocs/powerbi-docs#1679]
Is it possible to either configure the kpi trend axis or show it?
It's hard to tell what the change over time is without units.

**Comment by mihart** [comment]
Thanks for your comment, @WolffM . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @WolffM . This looks like a product idea or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. To search for submitted ideas, or to submit your own, visit ideas.powerbi.com.
