### ISSUE TITLE
Missing warning that streaming data sets do NOT working with PowerBI Apps

### ISSUE THREAD

**Issue by jbergren-work** [MicrosoftDocs/powerbi-docs#1701]
Missing warning that streaming data sets do NOT work with PowerBI Apps

**Comment by KesemSharabi** [comment]
Thanks for your comment, @jbergren-work.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
