### ISSUE TITLE
Dynamic expression based titles with R visuals not available

### ISSUE THREAD

**Issue by anncrawford01** [MicrosoftDocs/powerbi-docs#1702]
This is a great article https://docs.microsoft.com/en-us/power-bi/desktop-conditional-format-visual-titles but it does not work on R visuals.  I want to use a dynamic title based on standard slicers used in the report.  I do not want to use variable from the R script.   When I right click on the title text for an R visual (faceted bar chart in this case) I do not see the fx conditional formatting dialog.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @anncrawford01.

I've assigned this issue to the doc author for review.

<I sometimes add this to product question ones> In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your comment. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
