### ISSUE TITLE
Does this work on the Gov tenant

### ISSUE THREAD

**Issue by kschlenker** [MicrosoftDocs/powerbi-docs#1707]
If we're on the gov tenant are we able to share in this way with non-gov collaborators?

**Comment by KesemSharabi** [comment]
Hi @kschlenker,

It's not clear what you're asking. You may find answers in the following articles:

- [Power BI for US Government customers](https://docs.microsoft.com/en-us/power-bi/service-govus-overview)

- [Frequently Asked Questions for Power BI for Germany Cloud customers](https://docs.microsoft.com/en-us/power-bi/service-govde-faq)


In any case, this looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
