### ISSUE TITLE
Data = plural

### ISSUE THREAD

**Issue by lakecoach** [MicrosoftDocs/powerbi-docs#171]
Several areas where data are identified as singular when they should be plural. Otherwise, nice introduction.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b08723-3d20-45e8-1a6e-348c33cb5ff2
* Version Independent ID: a201f1c5-9771-5eff-bac6-85de7058a8b3
* Content: [Getting started - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingstarted?tutorial-step=6)
* Content Source: [powerbi-docs/guided-learning/gettingstarted.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingstarted.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi @lakecoach -- Congrats on the eagle eye!
Ah, the age-old "Is 'data' plural or singular?" debate. We have settled on using the singular form of verbs with 'data,' preferring to think of it as a mass rather than a count noun. I just ran a check on all the Power BI docs; we use "is" with "data" 219 times. We use "are" with "data" only 8 times -- and in all 8, it's because the actual subject of the sentence is something other than "data." For example,  "...new insights from the world of data are easier to model, build, share, and extend."
Thanks for keeping us honest!
