### ISSUE TITLE
Solution no longer works

### ISSUE THREAD

**Issue by JeffriVanbuster** [MicrosoftDocs/powerbi-docs#1718]
Dear,
The solution described on this page stopped working (since December 2019 in my case).
Maybe an update of the system libraries occurred.
We're receiving the error that the 
"Destination array was not long enough. Check destIndex and length, and the array's lower bounds" 
on the line "Array.Copy(segmentEncryptedResult, 0, encryptedData, encryptedDataPosition, segmentEncryptedResult.Length);"

The length of the unencrypted segment is 85 but after the encryption is applied, the length of the segmentEncryptedResult is 256 which is twice the size vs the expected length of 128.
Thus the encryptedData array that has to hold the end result is too small to contain all the encrypted data.

Could someone have suggest a new solution for this issue?

Kind regards,
Jeffri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 714c05d7-98b0-cff6-ef96-c9e8763f0864
* Version Independent ID: e45ce6f9-717d-9d2b-85e8-034f65379b09
* Content: [Encrypt credentials - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/encrypt-credentials#feedback)
* Content Source: [powerbi-docs/developer/encrypt-credentials.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/encrypt-credentials.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @MahirDiab
* Microsoft Alias: **madia**

**Comment by mihart** [comment]
Thanks for your comment, @JeffriVanbuster . This issue has been assigned to the doc author for review.

**Comment by laurent-mic** [comment]
The issue will happen on On-premises Data Gateway versions from November 2019 and higher.
Those versions requires a higher encryption key size and the encryption algorithm supplied will no longer work.
Documentation will be update accordingly.

In the meantime there are multiple options to mitigate or fix the issue:
1. Downgrade On-premises Data Gateway version (< November 19)
2. Create or Update datasource credentials through Power BI Service.
3. Fix the credentials encryption code as done in [this Pull Request](https://github.com/microsoft/PowerBI-CSharp/commit/83ba6891704a412bfc22d7086b55a9c826454e5e 
).
4. Use Microsoft.PowerBI.Api SDK's credential encryption helper fixed in version [3.7.1-beta](https://www.nuget.org/packages/Microsoft.PowerBI.Api/3.7.1-beta)

**Comment by laurent-mic** [comment]
@KesemSharabi, please update these two documents accordingly.
- https://docs.microsoft.com/en-us/power-bi/developer/encrypt-credentials
- https://docs.microsoft.com/en-us/power-bi/developer/configure-credentials

**Comment by JeffriVanbuster** [comment]
Thank you a lot for the quick responses and the valuable suggestions to resolve our problem currently!
I'll have a look today which of the above suggestion would best for our setup.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
