### ISSUE TITLE
Will use of PBIDS files not work to Refresh from the Cloud?

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#1727]
Will use of PBIDS files not work to Refresh from the Cloud?
So, if I create a PBIDS file for a specific SharePoint site and use that for Get Data, will I be able to refresh from the Power BI Service? You should cover this under that section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-sources)
* Content Source: [powerbi-docs/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @pcgeekus . Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com. If you get clarification from the community or support, and you feel the doc should be updated, please feel free to post here again. Thanks.
