### ISSUE TITLE
Didn't find the options in my version of PBI desktop

### ISSUE THREAD

**Issue by AssiaZe** [MicrosoftDocs/powerbi-docs#1734]
There are some parts of this help page that didn't match with Power BI
For example, the refer to option, the conditions option all I do not have them in power BI
Please advice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3be58e8-522b-1bc1-5c20-94349d5ed617
* Version Independent ID: ecbf2a74-8efd-aecd-3d15-b24bc0a1ca46
* Content: [Teach Q&A to understand questions and terms in Power BI Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-tooling-teach-q-and-a)
* Content Source: [powerbi-docs/natural-language/q-and-a-tooling-teach-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/natural-language/q-and-a-tooling-teach-q-and-a.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mohaali
* Microsoft Alias: **mohaali**

**Comment by davidiseminger** [comment]
Thanks for your comment, @AssiaZe. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated since your comment was filed. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
I reviewed your feedback, and the options you refer to only appear when your training questions uses terms that Power BI doesn't understand. Refer to can be used to link variable terms, such as when your data is labeled "revenue", but your question is about "sales". You setup Q&A so that it knows those two terms refer to the same thing. A condition can be used when you want to define what makes something "best" or "awesome" - for example, if your question is "what's the best score?" your condition will specify how you define "best". Hope that helps!
