### ISSUE TITLE
Change the PBI hosted dataset associated with a report

### ISSUE THREAD

**Issue by gbrueckl** [MicrosoftDocs/powerbi-docs#174]
We currently have separated the datamodel and the actual reports into two different files and this works fine for.
However, we are totally reworking our datamodel now and published it as a new dataset. It seems to be impossible to link the existing report to the new datamodel which is also hosted in the PBI service?!

I also tried the API but this seems to break the report in terms it cannot be downloaded and modified anymore

would be great if such a basic functionality - changing the dataset - would be easier and also documented somewhere

**Comment by davidiseminger** [comment]
Thanks for your comment, @gbrueckl, and sorry for the delay responding. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com. If this functionality is updated, we'll certainly document it too.
