### ISSUE TITLE
PowerBI Embedded Subscription

### ISSUE THREAD

**Issue by MickaelLevert** [MicrosoftDocs/powerbi-docs#1777]
Hello,

Is it possible to subscribe to a report in PowerBI Embedded ? And/Or using the PBI Javascript Library ?
My reports are filtered dynamically through URL Filtering using fields from the report. So is it possible to subscribe to them in my environment ? 
The subscription would also be temporary.

Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35489ab-e39e-b7be-588d-38f26ccf5442
* Version Independent ID: f5145d5d-afbc-f3f0-7275-1186b60890d0
* Content: [Subscribe yourself to reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe#feedback)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @MickaelLevert. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com). 

I also strongly suggest that you review the [Power BI developer](https://docs.microsoft.com/power-bi/developer/) documentation.
