### ISSUE TITLE
Cannot recreate section Interpret continuous key influencers

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#1817]
Tenure's influenced is not presented as the example says, "goes up by X," but by "is more than X."  Also, the chart given is a bar chart and not a scatter chart.  This also happens if I leave in the Explain By well only the Tenure field.  Moreover, it won't let me change the Analysis to "continuous."

**Comment by davidiseminger** [comment]
Hi @asocorro - thanks for commenting, can you please reference the article you're posting about? That'll help us investigate. Thanks.

**Comment by davidiseminger** [comment]
Got it (from your other post) - this is for /powerbi-visualization-influencers.

I've forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @asocorro ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
