### ISSUE TITLE
Cannot recreate section Interpret measures and aggregates as key influencers

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#1818]
The data in the pbix file gives different values.

**Comment by davidiseminger** [comment]
Hi @asocorro - can you include the article you're referencing, so we can investigate further? Thanks.

**Comment by asocorro** [comment]
Hi David, it's this one for both comments I submitted:

https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers

Thanks!
Adolfo

________________________________

**Comment by davidiseminger** [comment]
Got it - thanks. I’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @asocorro ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
