### ISSUE TITLE
no info on using credentials to access a site

### ISSUE THREAD

**Issue by dnvrjeep** [MicrosoftDocs/powerbi-docs#1830]
There doesn't seem to be any documentation on using credentials to get to a site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1bfb7d-4e9e-27c5-ece0-74511f99136e
* Version Independent ID: 1a9b344d-65ea-518a-03db-3636ea3fb48f
* Content: [Connect to a webpage from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-to-web#feedback)
* Content Source: [powerbi-docs/desktop-connect-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @dnvrjeep , thank you for reaching out to us with your question. I am forwarding it along to the author of the article you mentioned for consideration. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment, @dnvrjeep. Looks like this is product feedback (connect to a website that requires credentials), rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
