### ISSUE TITLE
Misleading information about refresh

### ISSUE THREAD

**Issue by ElegantHaiku** [MicrosoftDocs/powerbi-docs#1869]
This sentence is misleading: "Calculated tables are recalculated if any of the tables they pull data from are refreshed or updated." This is untrue. If your calculated table uses data from a table in DirectQuery, the calculated table will only reflect the changes after the dataset has been refreshed. This needs to be changed. If a table needs to be in DirectQuery mode, so does the calculated table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23f1335-bb33-544a-67da-006015cfc92f
* Version Independent ID: 3e1dc63e-f0ac-5201-c0a5-bc7e4ee30944
* Content: [Using calculated tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-calculated-tables#feedback)
* Content Source: [powerbi-docs/desktop-calculated-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-calculated-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @ElegantHaiku , thanks for reaching out to us with your comment. I have forwarded it along to the doc author for consideration.

**Comment by sebohnRAFI** [comment]
I have a problem with formatting the value of a  measure in a calculated table. I use UNION to combine two tables and then want to display the result of a new measure in this table as percentage (e.g. 79%). But it is always displayed as 0.79, although the format is set to percentage.
If I do the same measure in the original tables, the result is displayed as desired as 79%. 
Thx for an answer.

**Comment by davidiseminger** [comment]
Thanks for your comment @ElegantHaiku - that clarification is much appreciated, and I've updated the article to include that information.

For @sebohnRAFI, your question looks like a support or community question, rather than a documentation question (though the fix for you might be straightforward). You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
