### ISSUE TITLE
Edit Queries button for Feb 2020 version has changed to Transform Data

### ISSUE THREAD

**Issue by rovermx** [MicrosoftDocs/powerbi-docs#1874]
Edit Queries button for Feb 2020 version has changed to Transform Data -&gt; Transform Data, not very intuitive, I wish you did not do the change, thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6ac628-d5b4-e722-0532-d467c8347a5a
* Version Independent ID: 20ec07f6-627d-3765-ddcb-4aa738b6952a
* Content: [Query overview in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-query-overview#feedback)
* Content Source: [powerbi-docs/desktop-query-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-query-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rovermx. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
