### ISSUE TITLE
Not working with Canada Central P1 capacity

### ISSUE THREAD

**Issue by ryanscott14** [MicrosoftDocs/powerbi-docs#1875]
I went through support and they confirmed this doesn't work for Canada Central. Please add support :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 246f0cce-9c53-3bea-15df-0fb7c8520f12
* Version Independent ID: aefc566c-9abf-1e4f-6d38-18a1e192fa23
* Content: [Large models in Power BI Premium (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-large-models#feedback)
* Content Source: [powerbi-docs/service-premium-large-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-large-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ryanscott14. I'm familiar with that support request, and we'll update the doc to be clearer.
Meanwhile, since this is product feedback rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
