### ISSUE TITLE
does the Master account needs to be a cloud only account or can it be an account that is synced from on-prem using AD Connect?

### ISSUE THREAD

**Issue by Neenisharma** [MicrosoftDocs/powerbi-docs#1890]
does the Master account needs to be a cloud only account ( created in online ) or can it be an account that is synced from on-prem using AD Connect ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers?source=docs)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @Neenisharma -- thanks for your question! I've assigned it to the author to get back to you.

**Comment by KesemSharabi** [comment]
Hi @Neenisharma,

According to our development team the master account can it be an account that is synced from on-prem using AD Connect.

In any case, this looks like a support request or product question rather than documentation feedback.

If you need further assistance, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
