### ISSUE TITLE
SQL Server stored procedures

### ISSUE THREAD

**Issue by sqlsauce** [MicrosoftDocs/powerbi-docs#190]
The list of supported objects for the SQL Server data source does not include stored procedures, but they seem to work in Import mode. Are they officially not supported, and they just happen to work or is this page wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d081a0-4c4b-f756-eaf7-1e98d583ecf8
* Version Independent ID: 0b694de6-df10-daca-888c-1062dd3299db
* Content: [Power BI data source prerequisites - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-source-prerequisites#feedback)
* Content Source: [powerbi-docs/desktop-data-source-prerequisites.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-source-prerequisites.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your question @sqlsauce - let me look into this and get back to you on this comment thread.

**Comment by sqlsauce** [comment]
@davidiseminger, have you been able to track this down?

**Comment by davidiseminger** [comment]
@sqlsauce - sorry for the delay, yes I have. Here it is: stored procedures are supported using native query - and to clarify, you can run any SQL statement you like using native query, including those which reference stored procedures. However, the navigation-driven experience is not available for stored procedures, because they can have side effects. I hope that helps.
