### ISSUE TITLE
Dashboard Subscriptions are not receiving notification emails after data refresh

### ISSUE THREAD

**Issue by MuggleMaggic** [MicrosoftDocs/powerbi-docs#1922]
I selected a notification frequency of "after data refresh (once daily)". The subscription was established for a start date of the 3/6/2020. After subscribing to the dashboard, we performed a data refresh to test the notifications we'd received. I never got an email notification for the dashboard. 
<img width="439" alt="Dashboard Subscription" src="https://user-images.githubusercontent.com/54996791/76233837-cdc04380-61f6-11ea-80a6-32cda39a61d4.png">

**Comment by davidiseminger** [comment]
Thanks for your comment, @MuggleMaggic. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
