### ISSUE TITLE
Package Request

### ISSUE THREAD

**Issue by ScarlettChild** [MicrosoftDocs/powerbi-docs#1961]
It would be great to be able to install the nCov2019 from Github to use in PowerBI - Thanks

**Comment by paulinbar** [comment]
Thanks for your comment, @ScarlettChild . I am not sure I understand your suggestion, but in any event your comment looks like product feedback or a product question, rather than documentation feedback (you've opened an issue on the documentation site). You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com). Thanks!
