### ISSUE TITLE
drill through on working in embedded report

### ISSUE THREAD

**Issue by vivekParanjape** [MicrosoftDocs/powerbi-docs#1962]
I have switched on the option for drill through for a visual in the data/drill tab.
It is working fine in desktop and service but not when embedded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drill through in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-drillthrough#feedback)
* Content Source: [powerbi-docs/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by vivekParanjape** [comment]
It is working with options menu on the right click but i need it to work on the left click as it does in the desktop and the service.

**Comment by paulinbar** [comment]
Hi @vivekParanjape , thanks for reaching out to us. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com). Thanks and good luck!
