### ISSUE TITLE
Data Source Hive LLAP added March 2020

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#1980]
Can we get this source added to the document and the grid populated with functionality available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources#feedback)
* Content Source: [powerbi-docs/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for your comment, @elfohl . Looks like this is product feedback / a product feature request, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by davidiseminger** [comment]
Oops - looks like you're just asking to have Hive LLAP added to this doc, sorry about that. I'll get in touch with the proper engineering team to get more information, thanks!

**Comment by davidiseminger** [comment]
Sorry for the delay - this will be added with the next monthly update of Power BI Desktop docs.
