### ISSUE TITLE
More on icons - blog post announcing had several pages

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#2002]
There should be much much more content about icons - perhaps even a separate page? The blog post announcing them had several screen-fulls of dense content:
https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-july-2019-feature-summary/#iconSets
More functionality has been added since.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-au/power-bi/desktop-conditional-table-formatting#add-icons)
* Content Source: [powerbi-docs/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @Mike-Honey , thank's for your comment and the links. I am forwarding them on to the article author for consideration.

**Comment by mihart** [comment]
Hi @Mike-Honey ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
