### ISSUE TITLE
Number Values

### ISSUE THREAD

**Issue by timothydickson** [MicrosoftDocs/powerbi-docs#2016]
The number values do not come over in Excel so that they can be summarized.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @timothydickson -  I think you may actually be looking for "export to excel" vs. analyze. Assigning to the docs author to comment.

**Comment by davidiseminger** [comment]
Hi @timothydickson - using Analyze in Excel creates a connection to the data from the Power BI service, rather than importing them locally to Excel. If you're having trouble with that, you might find  a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
