### ISSUE TITLE
Where is the link to this app?

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#2030]
This looks NOTHING like the "Power BI Premium Capacity Metrics" app that I see in AppSource and mentioned on this page: https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity

How do I get the app mentioned on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4843cde8-6191-2773-7500-272b87ad8084
* Version Independent ID: 27ff08bc-43e8-4c8d-2cf5-ad096b6f11ff
* Content: [Power BI Premium Metrics app - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-metrics-app)
* Content Source: [powerbi-docs/service-premium-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @klinejordan -- thanks for asking! Assigning to the writer to investigate.

**Comment by chrolivier** [comment]
Hi, any feedback on this?

**Comment by davidiseminger** [comment]
I'm sorry you're having trouble finding that app. 

Is this the link you're using? https://powerbi.microsoft.com/en-us/blog/introducing-power-bi-premium-capacity-metrics-app-as-a-template-app/

I would also suggest posting to the community,found at https://community.powerbi.com, since many folks there may be able to point you in the right direction, help you determine why yours looks different, and the like.
