### ISSUE TITLE
Need description of Power BI Audit Log Activities

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2032]
Need a brief description of each Power BI Audit Log activity mentioned here - https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#operations-available-in-the-audit-and-activity-logs

Right now, it is not clear from doc what a particular activity logs.

For example, there is a logging activity called "Changed capacity state" but end users and customers don't understand what that means. It would be helpful to have a brief description of each audit log activity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by maggiesMSFT** [comment]
Hi, @haider392 -- thanks for asking! Assigning to the author for further attention.

**Comment by mihart** [comment]
Hi @,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
