### ISSUE TITLE
Make it clear that selection button can be clear

### ISSUE THREAD

**Issue by NeilMacMullen** [MicrosoftDocs/powerbi-docs#2036]
In the gateway connection section it's _really_ counter-intuitive that the radio button next to "in premises gateway" can be clear and yet that gateway will be used.  Or maybe when there is more than one gateway in that list, they are _all_ used?  Either way it's confusing - the UI design needs to be better documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a72e523-2194-f53c-9a27-abf960e77851
* Version Independent ID: bdc43737-adc5-b7bf-245e-e065a1478566
* Content: [Configure scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-scheduled-refresh)
* Content Source: [powerbi-docs/refresh-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @NeilMacMullen -- thanks for asking! Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
Thanks for your comment, @NeilMacMullen. Seems like a reasonable request. 

However, looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by NeilMacMullen** [comment]
@davidiseminger   Alas, the forum appears to be where feedback goes to die so I'm not holding my breath on any action there. :-( I raised this as a _documentation_ request so that at least the current design could be better explained.
