### ISSUE TITLE
Free?

### ISSUE THREAD

**Issue by chicagoclone** [MicrosoftDocs/powerbi-docs#2045]
Is this a free template or paid?  If it's paid, it should mention that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278fd9da-a097-37e4-693a-6fdd64cbd10e
* Version Independent ID: 67618156-2b42-c349-85c1-dcbcab543f59
* Content: [Connect to Office365Mon with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-office365mon#feedback)
* Content Source: [powerbi-docs/service-connect-to-office365mon.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-office365mon.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @chicagoclone , thanks for your comment. Indeed, in AppSource I do not see any indication that the app is free. I need to inquire about the exact policy about where free/paid information is supposed to be mentioned, and I'll mention your comment. Thanks for reaching out! I'll let you know what happened.

**Comment by paulinbar** [comment]
Hi @chicagoclone, sorry it's taken so long to get back to you. Anyway, I am not sure what was true at the time you wrote, but I see that the Office365Mon.Com Power BI Report Pack offering on AppSource at least now states that it is free. I think that the offering is the right place for that information, since it could change and then the documentation would have to be updated. What is true, however, is that being able to install template apps requires a certain kind of license. This information is contained in the general template app [documentation](https://docs.microsoft.com/power-bi/connect-data/service-template-apps-install-distribute#prerequisites), but I am considering adding such a note to the documentation of the individual template apps that we have. However, the documentation for most template apps is the responsibility of app creators, and is not in our control. 
In any event, thanks for your comment!
