### ISSUE TITLE
Tooltip does not customize

### ISSUE THREAD

**Issue by epiphania** [MicrosoftDocs/powerbi-docs#206]
You cannot remove the default fields from tool tip from the visual which is not at all helpful especially when you want to display Total sales in Size and in color saturation, it will repeat the total sales in Tool tip which is ugly for data visual. Only solution I see is to turn off which is not helpful. Is there a solution for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfbc531-11a6-2543-6c99-d38128af21e4
* Version Independent ID: d7dd98cd-d0f9-5738-677d-41fd64804f16
* Content: [Customizing tooltips in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-custom-tooltips)
* Content Source: [powerbi-docs/desktop-custom-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-custom-tooltips.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @epiphania and sorry for the delay. Looks like this is product feedback rather than documentation feedback – you can submit product feedback or feature ideas by using the button labeled Give Product Feedback, or by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
