### ISSUE TITLE
Custom List as Filter

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2097]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.tr-tr/issues/4

@ofyayla commented 21 hours ago
We use SSAS models in my company and I am a end-user of the model. I create own dashboards with the cube datas.
Sometimes for the spesifics customer group I need to filter them on the model.
For example I have 1million customer but I want to create a special analysis for 50K number list specifically.
I tried to custom visual like filter by list by Devscope but when add numbers it stucks.
Is there a solution for that?

**Comment by paulinbar** [comment]
Hi @ofyayla , @srvbpigh , and @CeciAc . Do any of you have a reference to the doc page in question? We are the doc team and in order to be able to check the issue we need to be able to know what doc(s) are being referred to. If it is a product question or a support request, I suggest you try either the [Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com). Thanks!

**Comment by paulinbar** [comment]
Hi @ofyayla, @srvbpigh, and @CeciAc. I have not heard back from you regarding a specific doc page to refer to. Did you try the [Power BI Community](https://community.powerbi.com/) or [support page](https://support.powerbi.com/) for assistance? In any event, I am closing this issue for the time being. Please feel free to reopen if you are still having problems.
