### ISSUE TITLE
Missing information about view-only for A-sku

### ISSUE THREAD

**Issue by marclelijveld** [MicrosoftDocs/powerbi-docs#2108]
In the table above, both P and A-skus are listed. In a later paragraph, there is more detail on view-only licenses. Per my experience, this only applies to P-sku and not to A-skus. Can this please be clarified in the docs? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-what-is#unlimited-content-sharing)
* Content Source: [powerbi-docs/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @marclelijveld . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @marclelijveld ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
