### ISSUE TITLE
What about DirectQuery on SAP HANA datasources ? Can query caching be leveraged  ?

### ISSUE THREAD

**Issue by gregoryleandro** [MicrosoftDocs/powerbi-docs#2119]

**Comment by davidiseminger** [comment]
Thanks for your comment, @gregoryleandro. I'll look for clarification in the content, and this also looks like a support request rather than strictly documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
