### ISSUE TITLE
The Power BI UI for this is very user un-friendly and not very logical.

### ISSUE THREAD

**Issue by jeppesal** [MicrosoftDocs/powerbi-docs#2134]
The UI for this feature is not optimal because:
1. The data source in the gateway overview has a red-error-cross eventhough it is configured as intended.
2. It would make more sense to have a "Maps to" option that said "configure in Data source credentials".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud)
* Content Source: [powerbi-docs/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by davidiseminger** [comment]
Thanks for your comment, @jeppesal. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
