### ISSUE TITLE
Row Level Security User Bulk Add

### ISSUE THREAD

**Issue by MACEL94** [MicrosoftDocs/powerbi-docs#2148]
https://github.com/MicrosoftDocs/powerbi-docs/issues/1683#issue-537157687

**Comment by maggiesMSFT** [comment]
Hi, @MACEL94 -- I see from the other issue you link to that @kfollis already replied:
"Hi @MACEL94 - I have opened a work item for us to research this scenario and identify the best way for you to accomplish the goal so that we can enhance the article."
So I'm not sure what more you're looking for. Can you elaborate? Thanks!

**Comment by MACEL94** [comment]
The other issue was closed so I opened a new one. I would like to bulk insert many users from a ps script or your APIs for an on premise server but it,'s not clear how can I do this from the docs.

I'll close this as the other issue is now open once again :)
