### ISSUE TITLE
Missing description of Scatter chart's Play feature

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#2156]
The built-in Scatter chart has a Play feature that should be described here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5668e4cf-3837-c2d4-b818-14476441468b
* Version Independent ID: c95096dd-9b73-79ab-8ff2-158c5900f5a6
* Content: [Scatter, bubble, and dot plot charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-scatter#next-steps)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-scatter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-scatter.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by davidiseminger** [comment]
Thanks for your comment, @mike-honey. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
