### ISSUE TITLE
Incorrect or oudated information regarding default capacity?

### ISSUE THREAD

**Issue by mparowski** [MicrosoftDocs/powerbi-docs#2171]
In the "Dedicated Capacities" heading, this article says "By default workspaces, including personal workspaces, are created in the shared capacity. When you have Premium capacities, both My Workspaces and workspaces can be assigned to Premium capacities."  I have not found this to be true in my organization.  All of our personal workspaces and all new workspaces are being created by default in our Premium capacity, and discussions with our Microsoft support team members indicate that this is a default that cannot be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#feedback)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @mparowski -- thanks for your question! Referring it to the author to investigate.

**Comment by mihart** [comment]
Hi @mparowski ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
