### ISSUE TITLE
Some out of date screenshots - ribbon, conditional formatting, visualisation icons

### ISSUE THREAD

**Issue by PeterGrahamJersey** [MicrosoftDocs/powerbi-docs#2177]
- Ribbon screenshot for accessing selection pane is out of date
- Ribbon screenshot for switching theme is out of date
- Accessing conditional formatting for alt text screenshot is out of date
- Icons in screenshots of visualisation pane are out of date (particularly relevant as part of the goal of updating them was to improve contrast)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762701ab-7066-612d-cdc2-a729ba1b5483
* Version Independent ID: 8a64d563-9737-16d3-d83e-fb56e8d3d95c
* Content: [Creating accessible reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-creating-reports#feedback)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-creating-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-accessibility-creating-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @PeterGrahamJersey -- thanks for your comment! Referring it to the author to add to his backlog.

**Comment by mihart** [comment]
Hi @PeterGrahamJersey ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
