### ISSUE TITLE
Can Python or R scripts run with Incremental Refresh?

### ISSUE THREAD

**Issue by duncangrace** [MicrosoftDocs/powerbi-docs#2182]
This was an issue in the past regarding Python scripts not being able to automatically refresh unless you are using a personal on-premise data gateway. Does incremental refresh using a non-personal in-premise data gateway support Python and R scripts to run after being Published?

**Comment by maggiesMSFT** [comment]
Hi, @duncangrace -- are you referring to a specific article? If you let me know which one, I can refer your question to the author. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @duncangrace -- perhaps you're referring to this article, https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-python-scripts? Assigning to that author to answer your question.

**Comment by otarb** [comment]
Hello @duncangrace,, you would still need on-premises data gateway in personal mode to be able to refresh Python (or R) scripts. It is currently not supported in standard (also known as enterprise) mode. It's mainly due to security and permissions with which personal vs standard modes are run. Personal mode runs as an application with your credentials. Enterprise mode runs as a service with administrator privileges. 

Let me know if this answers your question.
