### ISSUE TITLE
Doubt on correctness

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/powerbi-docs#2190]
Reports with applied Text Analytics and Vision functions should be published to a workspace that is not on a Premium capacity, otherwise refreshing the dataset will fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f95078-89ba-6ba2-231b-b130755c8510
* Version Independent ID: 8f152dab-fea9-714a-f97e-f0d68109151f
* Content: [Connect to AI Insights in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-ai-insights)
* Content Source: [powerbi-docs/transform-model/desktop-ai-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-ai-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @aguptadel , thanks for your comment. I am forwarding it along to the doc author for consideration.

**Comment by mihart** [comment]
Hi @,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
