### ISSUE TITLE
Server Details

### ISSUE THREAD

**Issue by NiranjansaikrishnaC** [MicrosoftDocs/powerbi-docs#2196]
Tip mentioned here to add Server details like below is no more working.

If you're having trouble connecting in this step, try using the following format in the Server field: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host_name)(PORT=port_num))(CONNECT_DATA=(SERVICE_NAME=service_name)))

It says server name cant extend more than 128 characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-oracle-database#feedback)
* Content Source: [powerbi-docs/connect-data/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @NiranjansaikrishnaC . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @NiranjansaikrishnaC ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
