### ISSUE TITLE
Admin APIs not supported

### ISSUE THREAD

**Issue by Ponchothewise** [MicrosoftDocs/powerbi-docs#2213]
Could we have explicit confirmation that it's not possible to call admin APIs (and the associated PowerShell cmdlets) without logging in as a user? Could we also move the considerations and limitations section somewhere near the top so we don't get through the whole article to find out what we're doing isn't possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 794566fc-c06c-1d9c-b656-2e7b59bc2874
* Version Independent ID: 4c57568f-c4f2-0bd6-b724-9868b2455d50
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal)
* Content Source: [powerbi-docs/developer/embedded/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @Ponchothewise, thanks for your suggestion! Referring to the author for consideration.

**Comment by KesemSharabi** [comment]
Hi @Ponchothewise,

I understand your frustration at not finding the admin APIs limitation. However, it is common practice to have the limitation section at the end of technical articles. This is because you don't want articles to start with a list of limitations.

You can quickly navigate to any section of our articles, including limitations, by clicking the section links which are positioned at the side of the article (or in some displays at the top).

![image](https://user-images.githubusercontent.com/54834915/85548084-4244b400-b627-11ea-80e0-66f1f27162da.png)

Once again, thank you for your comment.

Kesem
