### ISSUE TITLE
My error is missing

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/powerbi-docs#2227]
Please add support for this refresh error and how to fix

Activity Id: | Activity Id: | 66f97ecd-f00f-4cc6-9bf3-af0f937f60fb | 66f97ecd-f00f-4cc6-9bf3-af0f937f60fb
-- | -- | -- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7809469d-1c82-a875-3b77-83038a901f52
* Version Independent ID: 5c41e498-26bb-eec4-444e-1c376a2fe87f
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios)
* Content Source: [powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @gkens - thanks for your comment! Assigning to the author to investigate.

**Comment by mihart** [comment]
Hi @gkens ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
