### ISSUE TITLE
Oracle client software

### ISSUE THREAD

**Issue by alomar123** [MicrosoftDocs/powerbi-docs#2267]
Hello,

Trying to get clarification on what I need to install in order to directly connect to Oracle with PowerBi. I have read the instructions here and am a little unsure on everything that needs to be downloaded/installed. It mentions installing the Oracle Client - I plan on doing it for 32 and 64 due to compatibility. Each download includes several items and need to verify which ones are required. I.E. does it need to have the instant client, OLE DB, ASP 2/4, ODBC driver.

With the point being that my organization wants me to put in separate requests to engineering for for each elements only if required. 

Thank you!

**Comment by kfollis** [comment]
Hi, @alomar123 - can you provide the article that you are referencing? If you comment isn't specific to documentation, you might try posting your questions to https://community.powerbi.com

**Comment by alomar123** [comment]
Thank you for responding! Specifically, the Microsoft article below cites "Installing the Oracle client" and links to Oracle. Are all of the elements in that Oracle ODAC package (instant client, OLE DB, ASP 2/4, ODBC driver,etc...) required to connect to Oracle with PowerBi? Or can I only pick certain required ones?

https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-oracle-database

**Comment by kfollis** [comment]
Thanks for clarifying, @alomar123! I'm adding the author to see if we have an answer. I do see that the Oracle ODAC package contains several elements, and understand that you'd like to install only the elements required for Power BI.

**Comment by mihart** [comment]
Thanks for your comment, @alomar123 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. 

I did chat with the product team and engineers, and they did some preliminary testing.  Here is their response to me: I have tried to only select “Providers for ASP.NET” and it still installed a few components.  It works fine with my quick tests but I’m not sure that we can modified the doc to say we only requires “Providers for ASP.NET” without more extensive testing.

You may get a more detailed answer by posting on the Community site.  We typically answer documentation questions here and the Community site does a great job with product questions.  

All the best,
the DOCS team

**Comment by luissimoesneom** [comment]
Actually this should be commented and clarified on the documentation.
Is it instant client enough for Power BI Gateway to connect to Oracle? Or the full ODAC needs to be installed.
