### ISSUE TITLE
Picture in share-to-teams-tenant-setting not visible

### ISSUE THREAD

**Issue by NickyvVr** [MicrosoftDocs/powerbi-docs#2271]
The picture in the [Share to Teams tenant setting](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-microsoft-teams#share-to-teams-tenant-setting) is not visible, instead the URL is shown.
I tried editing the page, but this section doesn't seem to be available there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd9c7dbe-8b03-52a9-b299-936856c89ba8
* Version Independent ID: f4496816-b872-4541-4ad9-f3b323b8917f
* Content: [Collaborate in Microsoft Teams with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-microsoft-teams#share-to-teams-tenant-setting)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-microsoft-teams.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-embed-report-microsoft-teams.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @LukaszPawlowski-MS
* Microsoft Alias: **lukaszp**

**Comment by maggiesMSFT** [comment]
Hi, @NickyvVr -- are you still having this issue? I have since split this article into several smaller articles, so the picture you refer to is now in this article: https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-report-teams
And there's a plausible reason you're not seeing the Share to Teams option: There's a setting in the Admin portal to show or hide it.   Here's a link to that article: https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#share-to-teams-tenant-setting
I'll add that link to the Share to Teams article.
Thanks for pointing that out!
