### ISSUE TITLE
Query Timeout minimum limit

### ISSUE THREAD

**Issue by Mholsen** [MicrosoftDocs/powerbi-docs#2299]
Is there a minimum limit for the Query Timeout workload setting?
I have tried to set it for 120 seconds, but a dataset refresh with only one table taking well over 7 minutes to complete runs without any Query Timeout error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-workloads)
* Content Source: [powerbi-docs/admin/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the question, @Mholsen. I'm assigning this to the author to research.

**Comment by mihart** [comment]
Hi @Mholsen ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. Your question does sound like a product question rather than a documentation option, so you may get a response by submitting your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
