### ISSUE TITLE
Original Data

### ISSUE THREAD

**Issue by logic-based** [MicrosoftDocs/powerbi-docs#2303]
Please consider showing the original data being used for the visualization, and however it needs to be prepared before uploading into PowerBI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by kfollis** [comment]
Thanks for the suggestion, @logic-based. I'm assigning this issue to the author to consider your request. If you haven't already, you might want to take a look at some of our learning modules, like this one: https://docs.microsoft.com/learn/paths/create-use-analytics-reports-power-bi/

**Comment by mihart** [comment]
Hi @logic-based ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
