### ISSUE TITLE
No new Desktop build for June Update ?

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/powerbi-docs#2319]
Version: 1.8.7468.41510 doesn’t require a new desktop client build ? Does it also address the problem where custom visuals always request users to sign in to power bi service ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Change log for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @jtarquino
* Microsoft Alias: **jaimeta**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @nojetlag.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @nojetlag -- interesting questions! And I have answers.
Version: 1.8.7468.41510 doesn’t require a new desktop client build ? No, it doesn't. 
Does it also address the problem where custom visuals always request users to sign in to power bi service ? That issue was resolved in Power BI Desktop, and doesn't require a new installation of Power BI Report Server.
Thanks!
