### ISSUE TITLE
Assigning Pro licenses to guest users - compliance with license agreement

### ISSUE THREAD

**Issue by obungimartin** [MicrosoftDocs/powerbi-docs#2343]
In the licensing area this sentence is causing my cusomter lots of trouble. They want to make Power BI reports available to customers but are afraid of violating the license agreement. I'm not aware of any Microsoft representative who can explain what the possible compliance issues could be. Can you please add more details? What license programs are in trouble? What is the specific rule this sentence is referring to?

"Before assigning Pro licenses to guest users, contact your Microsoft account representative to ensure you're in compliance with the terms of your agreement with Microsoft."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b#licensing)
* Content Source: [powerbi-docs/admin/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by mihart** [comment]
Thanks for your comment, @obungimartin . This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Hi @obungimartin - I found some resources, and it may be more helpful to link to those instead of advising customer to contact an account rep. There is a site here https://www.microsoft.com/en-us/licensing/product-licensing/products with a lot of licensing resources. In this download, http://download.microsoft.com/download/A/5/9/A599711B-6807-4757-B38D-1EE269F2F19B/FAQs-Product-Licensing.pdf, I found an FAQ that seems to answer the question: 
Third-party use
In our company, we have onsite contractors who work on short-term projects. Can we assign
Microsoft product licenses (Office, CALs, etc.) that we purchased through our own Volume
Licensing agreement to these contractor-owned devices so that they use our licensed software
for our projects?
Yes, as long as those licenses are used for the benefit of your company, the licensee, you can assign
your licenses to third-party devices.
You’re limited in how often you can assign your licenses. Volume Licensing product licenses can be
reassigned to other devices every 90 days, not more frequently. If the software will be used for the
benefit of the contractors and not your organization then the contractors need to purchase their own
licenses or explore other types of short-term software subscription licenses.

One more resource: https://www.microsoft.com/licensing/terms/ - this site might be your best reference since it lets you filter to licensing program and product. Does all that help?

**Comment by obungimartin** [comment]
Hi @kfollis  unfortunately all those sources do not really help. Do you know why that sentence was initially added to the documentation?

**Comment by kfollis** [comment]
Sorry that didn't help, @obungimartin - I believe the sentence was added to ensure that customers don't use B2B to resell/redistribute the service, as noted here: https://www.microsoft.com/licensing/terms/productoffering/MicrosoftPowerPlatform/MOSA#ServiceSpecificTerms. The primary restriction seems to be around license reassignment, as described above.
I'd like to revise the sentence in the article to read like this: "Consult the Microsoft Online Service Agreement (https://www.microsoft.com/licensing/terms/product/ForallOnlineServices/MOSA) before assigning Pro licenses to guest users to make sure you comply with the terms of use."
Would that change help to clarify?

**Comment by mihart** [comment]
Hi @obungimartin ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
