### ISSUE TITLE
IE 11 support needs to be updated

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2367]
IE11 doesn't support renaming of report page names and this either this document should be updated to reflect that limitation/bug or the bug should be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74662424-4c86-7d72-d7ad-4d8a669e83b8
* Version Independent ID: dfa6ec25-3a0c-1ee9-63b9-851c3d2ce055
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/power-bi-browsers)
* Content Source: [powerbi-docs/fundamentals/power-bi-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/power-bi-browsers.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @chrisweis, thanks for your comment. I managed to rename a report by going through the report settings, on IE 11.900.18362.0, so it doesn't seem to be a limitation of IE 11 per se. How did you try to rename the report? What version of IE are you using exactly? In any event, you've reached the documentation team, and since it doesn't seem to be an IE11 limitation to be added to the documentation, if the problem continues for you then it sounds more like a bug, in which case I encourage you to file a bug on our [support page](https://support.powerbi.com), giving them then exact details of your problem and the version of IE your using.
I am closing this as a documentation issue in the meantime. Please feel free to reopen if you think the problem needs more attention from the documentation standpoint. Good luck!

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- I'm investigating and will let you know. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- investigation shows that @paulinbar was right all along. It appears to be a bug on your side, which we can't repro. As @paulinbar says, "...in which case I encourage you to file a bug on our support page, giving them then exact details of your problem and the version of IE you're using."
thanks!
