### ISSUE TITLE
Add info about enhanced metadata prerequisite 

### ISSUE THREAD

**Issue by jorgeek830** [MicrosoftDocs/powerbi-docs#2380]
It should be clearly stated in the documentation that External tools only work with enhanced metadata feature enabled. Otherwise the tool icon will be inactive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c2607e-b89c-9572-6700-1d6446eb7133
* Version Independent ID: d14ccb79-9c49-fc0e-ff34-24d66a1db47a
* Content: [Using external tools in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools)
* Content Source: [powerbi-docs/create-reports/desktop-external-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-external-tools.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @jorgeek830 -- thanks for your suggestion! Assigning to the author for consideration.

**Comment by mihart** [comment]
Hi @jorgeek830 ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
