### ISSUE TITLE
Dataset limits needs update

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2389]
In the dataset limit section, it is mentioned "There is a 1 GB limit per dataset that is imported into Power BI. If you have chosen to keep the Excel experience, instead of importing the data, the limit is 250 MB for the dataset."

This info is no longer accurate. Power BI Premium allows datasets larger than 1 GB (Different tiers and SKUs of Premium have different limits). Please update documentation to reflect this. Also the 250 MB limit as mentioned above has been increased. Please confirm from Product Group and update documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Thanks @haider392 - notifying the author.

**Comment by maggiesMSFT** [comment]
Hi, @haider392 -- sorry for the extended delay! You're right that Premium has different size limits, so I've added a link to https://review.docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is?branch=pr-en-us-6976#large-datasets from this article. 
However, I was able to confirm that the 250 MB limitation for keeping the Excel experience instead of importing the data is correct.
Thanks!
