### ISSUE TITLE
External tools

### ISSUE THREAD

**Issue by ustrat** [MicrosoftDocs/powerbi-docs#2406]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c2607e-b89c-9572-6700-1d6446eb7133
* Version Independent ID: d14ccb79-9c49-fc0e-ff34-24d66a1db47a
* Content: [Using external tools in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools)
* Content Source: [powerbi-docs/create-reports/desktop-external-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-external-tools.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
@ustrat, I see that you opened a Ppwer BI documentation github issue, but I don't see any other information. I am going to close this issue on the assumption that it was opened by mistake, but if indeed you had a problem with the documentation, please reopen this issue and provide us the details so that we can begin to take steps. Thanks!
