### ISSUE TITLE
capacity setting changes

### ISSUE THREAD

**Issue by phobag** [MicrosoftDocs/powerbi-docs#2408]
Users will need to modify the Max Offline Dataset Size in the capacity settings to accommodate the dataset size 
![image](https://user-images.githubusercontent.com/54297657/89203989-662eda00-d583-11ea-9c04-20a80d83d8bd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 246f0cce-9c53-3bea-15df-0fb7c8520f12
* Version Independent ID: aefc566c-9abf-1e4f-6d38-18a1e192fa23
* Content: [Large models in Power BI Premium (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-large-models)
* Content Source: [powerbi-docs/admin/service-premium-large-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-large-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Thanks for your comment, @phobag.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
