### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by skiwii** [MicrosoftDocs/powerbi-docs#2443]
The ONLY place a tag shows is when the dashboard is marked as a favourite.  It doesn't show when you are in the report which is the most important place.

To me this is a Power BI bug and not a documentation issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 460b9768-213a-bd8b-5ad8-ed5071848a98
* Version Independent ID: 24bdc0f5-a172-0d0b-02b2-ff798ccd96cf
* Content: [Dashboard data classification - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-data-classification)
* Content Source: [powerbi-docs/create-reports/service-data-classification.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/service-data-classification.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thanks for the feedback, @skiwii. I'm assigning this to the author to review the article. If you want to submit your suggestion to improve the experience, you can add it here: https://ideas.powerbi.com/ideas/

**Comment by VitalyMCT** [comment]
This is definitely an issue. Either a bug (most likely) or documentation out of sync with actual product behaviour.

**Comment by mihart** [comment]
Hi @skiwii ,
Thank you for your suggestion. I am unable to replicate your issue.  It may be that the product has been updated since you wrote.  I was able to add a data classification tag and see it show up at the top of each report page :-)  And, the report is not a favorite. 
@VitalyMCT , I'm leaving your GitIssue #2559 open until we are able to do a freshness pass on the article to ensure it captures the full capabilities of this feature.  
All the best,
The DOCS team
