### ISSUE TITLE
Export Theme Not Available

### ISSUE THREAD

**Issue by snmalk** [MicrosoftDocs/powerbi-docs#2447]
Hi, I am not able to export a theme based on the documentation (https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#export-report-themes).

The instructions mention to navigate to Options, and then in the Preview features section, select Customize current theme, and then select OK. However, "Customize current theme" is not listed as a preview feature.

I'm using PowerBI Desktop Aug 2020.
Thanks!

**Comment by kfollis** [comment]
Hi @snmalk - I'll assign the writer so that they can make an update to that article. I believe that you can now do this without having to turn on the preview feature. Go to View, then select the down arrow next to themes. You should be able to customize the current theme and then save it to json format.

**Comment by snmalk** [comment]
Thanks @kfollis! I overlooked the save option, but it worked as expected. I was able to save as .json and then loaded the theme into another file just fine. Thanks!

**Comment by mihart** [comment]
Hi @snmalk ,
I see that this Git issue is a bit old, and that you were able to find a solution.  Based on your feedback, I did go ahead and update the article with the newest method of exporting a theme (View >Themes > ).  
All the best,
the DOCS team
