### ISSUE TITLE
Power BI Analyze in Excel

### ISSUE THREAD

**Issue by jfs-consulting** [MicrosoftDocs/powerbi-docs#2458]
Does anyone have performance issues on Analyze in Excel? How can I improve the query performance.
Is it possible to have a button inside the dashboard to Analyze in Excel, instead of having to access it outside of the report itself.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel#install-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your post, @jfs-consulting. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
