### ISSUE TITLE
Need C# code 

### ISSUE THREAD

**Issue by phaniraj-t** [MicrosoftDocs/powerbi-docs#2470]
[Enter feedback here]

Can you please share the complete C# code to export powerbi report
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @phaniraj-t -- thanks for your question! Assigning to the author to help out.

**Comment by phaniraj-t** [comment]
Please let me know where can I  get the complete code. I would like to export report using console application.

**Comment by KesemSharabi** [comment]
Hi @phaniraj-t,

In the [End-to-end example](https://docs.microsoft.com/power-bi/developer/embedded/export-to) section we have a code sample that covers the general use of this feature. We don't have a detailed example as the code would change depending on each customer's solution.

For your specific problem, and in order to find additional examples, I suggest that you look for a solution in the [Power BI Community]( https://community.powerbi.com). If that doesn't help, try our [support page](https://support.powerbi.com).

Thanks,

Kesem
