### ISSUE TITLE
Need Update Since Home Ribbon Has Changed

### ISSUE THREAD

**Issue by DaxelCA** [MicrosoftDocs/powerbi-docs#2476]
https://docs.microsoft.com/en-ca/power-bi/fundamentals/desktop-what-is-desktop#transform-and-clean-data-create-a-model

Buttons to access Power Query in Home ribbon is now: Transform Data

Regards
Julie

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e941f6c9-1676-dc84-ed1b-027a1c61cd23
* Version Independent ID: 373ee1b3-c001-d1a8-6eb4-832cbea29fe1
* Content: [What is Power BI Desktop? - Power BI](https://docs.microsoft.com/en-ca/power-bi/fundamentals/desktop-what-is-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-what-is-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/desktop-what-is-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @DaxelCA . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @DaxelCA ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
