### ISSUE TITLE
Different output yielded by `pbiviz start`

### ISSUE THREAD

**Issue by afernandez-yseop** [MicrosoftDocs/powerbi-docs#2511]
Hello, I'm having a different output when running `pbiviz start` than the one in the bullet 5 the section [Creating a custom visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial#creating-a-custom-visual) :
![2020-09-23_12-48-32](https://user-images.githubusercontent.com/38729160/94050877-76ea1800-fd9c-11ea-9623-3373e60dbf69.gif)

It never says `Server listening in port 8080` and the viz is not reachable from the report in powerbi.com 😟
![msedge_2020-09-23_12-52-10](https://user-images.githubusercontent.com/38729160/94051285-f2e46000-fd9c-11ea-9789-b349dbf0c7c7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d42a638-f0b9-abd1-43da-0c1618394948
* Version Independent ID: 1350b334-88ef-1aaf-61b6-6b78ab1baf82
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by afernandez-yseop** [comment]
I just created [a new post in the community regarding this](https://community.powerbi.com/t5/Developer/pbiviz-start-stuck-at-quot-compiled-successfully-quot/m-p/1391016)

**Comment by paulinbar** [comment]
Hi @afernandez-yseop. Thanks for your feedback and accompanying material. I am forwarding it all on to the doc author who might be able to channel you to the right person.

**Comment by KesemSharabi** [comment]
Hi @afernandez-yseop,

Thanks for you comments!

I revamped this tutorial - please revisit it using this link - [Tutorial: Develop a Power BI circle card visual](https://docs.microsoft.com/power-bi/developer/visuals/develop-circle-card#creating-a-custom-visual).

I'm not entirely clear as to what your issue is, but perhaps the note in **step 5** in the [View the circle card in Power BI service](https://docs.microsoft.com/power-bi/developer/visuals/develop-circle-card#view-the-circle-card-in-power-bi-service) section will help you?

![image](https://user-images.githubusercontent.com/54834915/96596975-f6b0c700-12f5-11eb-9811-ea03833c330f.png)

Thanks,

Kesem

**Comment by afernandez-yseop** [comment]
thanks a lot! 

this is enough update of the tutorial for me
