### ISSUE TITLE
Change the interaction behavior (https://docs.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions)

### ISSUE THREAD

**Issue by AzizQuazi** [MicrosoftDocs/powerbi-docs#2543]
After I "select the no impact icon", I cannot change it back as interactive again (I mean, I cannot reverse my earlier action). Can I get a solution? Thanks.

Rgds..Aziz
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7c372d-539c-5857-01c5-8a8d835380a8
* Version Independent ID: 08d1564e-d1dc-ae37-8147-ef21c80feccc
* Content: [Change how visuals interact in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions)
* Content Source: [powerbi-docs/create-reports/service-reports-visual-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/service-reports-visual-interactions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @AzizQuazi -- thanks for asking! Assigning to the author.

**Comment by mihart** [comment]
Thanks for your comment, @AzizQuazi . I tried to duplicate your experience and could not. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
