### ISSUE TITLE
Missing specifications on roles en users

### ISSUE THREAD

**Issue by elsdestickere** [MicrosoftDocs/powerbi-docs#2574]
Doc: https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration

"To bring your own ADLS Gen 2 account, you must have owner permissions at either the storage account, resource group or subscription layer. If you are an administrator, you still must assign yourself owner permission." 
Can you me more specific as in doc https://docs.microsoft.com/en-us/power-query/connectors/datalakestorage?
e.g.
You are granted the following roles for the storage account: Owner and Blob Data Owner
You granted user(?) Power BI Service the role: Blob Data Owner.

I think these are the minimum required roles but i'm not sure because I added quite a few to get there.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @elsdestickere.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community](https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @elsdestickere , 
Thank you for your suggestion.  We've captured your feedback and will include it in the next update of this article.  Here is the comment from the dataflows PM:  I am working on updated docs that elaborate more on the ADLS Gen 2 attach feature and this is good feedback to include in that, since it is about working with the data and access management is an important concept.
Thank you for your input,
the DOCS team
All the best,
The DOCS team

**Comment by mihart** [comment]
Hi again @elsdestickere 
Forgot to add this additional comment from the PM: 
As owner is the required scope, this is not needed necessarily. We are actually just storing the data backing your dataflows in a bring your own storage model. If you want access to this data, you can build your own capabilities. 
Hope this helps answer your question.  Let us know if you have any additional questions.
the DOCS team
