### ISSUE TITLE
Missing a list of supported languages

### ISSUE THREAD

**Issue by renepajta** [MicrosoftDocs/powerbi-docs#2576]
[Enter feedback here]

Hi all,

the content of this page is great, however, I would like to know also what languages are supported by the feature.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da6c49a-f7cc-213c-adc3-5b33b76716dd
* Version Independent ID: 2be2786b-c764-c142-0821-24f6a28b2459
* Content: [Smart narratives tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-smart-narrative)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-smart-narrative.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-smart-narrative.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by maggiesMSFT** [comment]
Hi, @renepajta -- good question! I've assign to the author to answer.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @renepajta.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
