### ISSUE TITLE
Other ways to access Power BI datasets from Excel - which SKUs?

### ISSUE THREAD

**Issue by andyparkerson** [MicrosoftDocs/powerbi-docs#2578]
# Other ways to access Power BI datasets from Excel

Which SKUs for Excel support connecting directly to PowerBI Datasets from the Get Data menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @andyparkerson -- this section of this article might answer your question:
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-excel-featured-tables#licensing

**Comment by mihart** [comment]
Hi @andyparkerson , 
Thank you for your suggestion.  I noticed that this Issue hasn't been closed so I checked out your question and the article.  I was glad to see that the article has been updated since you submitted this question, and that the article has the answers to your questions :-)  The Excel SKU for using "Get data" must be 2010 SP1 or later.  Also, Analyze in Excel requires that the dataset be in Premium or that the user have a Pro license.  Let us know if you have any additional questions.  
All the best,
The DOCS team
