### ISSUE TITLE
Missing text in instructions

### ISSUE THREAD

**Issue by premradhakrishnan** [MicrosoftDocs/powerbi-docs#2610]
[Enter feedback here]
In the "Create and install a certificate" section, step 3 says "In the File to Import window, select Next." It should say something along the lines of "In the File to Import window, select the pfx certificate generated in Step 1 and click Next."

This may have happened because the command "pbiviz --install-cert" didn't launch the certificate manager in my case. It is possible that if it launches with the command the file name is auto-populated with the right file name. Either way it is safer to have the additional text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/environment-setup?tabs=windows)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

Thank you for your comment, I'll take a look at your suggestion shortly and let you know what I decided to do.

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

Thanks for your comment.

I'm not sure why the `pbiviz --install-cert` command didn't launch the the certificate manager for you. @uve - are you aware of such a scenario?

In any case, I don't want to change the text as it isn't obvious where one should browse in order to find the certificate, and this is not the described scenario. The described scenario is:

![image](https://user-images.githubusercontent.com/54834915/98253893-47762000-1f84-11eb-98d0-b12f4fa06372.png)

Advanced users like yourself, can run the certificate manager separately, and find the certificate on their own.

Thanks,

Kesem

**Comment by premradhakrishnan** [comment]
Hi Kesem,

No worries if you think the current text is sufficient.

Thank you for getting back to me.

Cheers
Prem

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
