### ISSUE TITLE
Retain the Filter of the Page while using Export to File method on Embed?

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/powerbi-docs#2612]
Does Export To File have the properties to provide the Filter Criteria as well.
We have this while exporting the report to PDF from the Power BI Service UI where we can choose if we want to export the current or default values.

Please let me know as I do not see anything mentioned regarding this in the documentation.

Cheers,
Dhawal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#code-examples)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the question, @dhawal16. I'm adding the writer to review and provide feedback.

**Comment by AmosHersch** [comment]
Hi @dhawal16 thanks for your question. The default behavior in "Export to File" REST API is to export the report with the default values.
In order to receive a similar functionality to the export with "Current Values" which exists in Power BI service UI you should use capture bookmark state JavaScript API to capture current state, and provide the "Export to File" API the capture state.

See documentation about bookmarks API here: https://github.com/Microsoft/PowerBI-JavaScript/wiki/Bookmarks 

We will soon add support for providing filters to "Export to File" REST API, so it might also help you achieve a similar result.
