### ISSUE TITLE
Github link needs to be updated

### ISSUE THREAD

**Issue by arjunr1** [MicrosoftDocs/powerbi-docs#2618]
[Enter feedback here]
This page points to a github link which do not have the right set of files per the screenshots. Need to update the right github link or update the doc as per the files in the github link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @arjunr1 -- thanks for your comment! Referring to the author for consideration.

**Comment by KesemSharabi** [comment]
Hi @arjunr1,

Thank you for your comment - you're right, the screenshots in the article don't match the GitHub link.

I'm working on updating all the embedded analytics tutorials, and as part of this update will also fix this issue.

Once again, thanks for pointing this out nd please revisit this article in the future to see whether this issue was addressed.

Kesem
