### ISSUE TITLE
Not Up To Date

### ISSUE THREAD

**Issue by chrislfish** [MicrosoftDocs/powerbi-docs#2696]
There are things in this doc, like "Save As", that don't exist anymore.  And doing the "Save a Copy" just gives an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719feeea-d688-78bf-fef5-8b58c2fb047f
* Version Independent ID: 78793fa4-e2e2-7113-3652-b1165ee92145
* Content: [Monitor usage metrics in classic workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @chrislfish . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @chrislfish ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
