### ISSUE TITLE
Binary Data type not Supported as Stated in Documentation

### ISSUE THREAD

**Issue by Saltzmea** [MicrosoftDocs/powerbi-docs#2698]
The documentation on this page states that the binary data can be passed to the AI transformation. The web.contents() function returns an "any" data type which is acceptable to pass. However, using the binary data type causes an error in the M function. Probably a bug in the AI function but should also be called out with the other notices on the page. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f95078-89ba-6ba2-231b-b130755c8510
* Version Independent ID: 8f152dab-fea9-714a-f97e-f0d68109151f
* Content: [Connect to AI Insights in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-ai-insights)
* Content Source: [powerbi-docs/transform-model/desktop-ai-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-ai-insights.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Saltzmea . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @Saltzmea . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. I did hear back from the product PM and she requested that you submit this as a product bug so that they can investigate.
Take care
the DOCS team
