### ISSUE TITLE
Issues with ARC GIS map control

### ISSUE THREAD

**Issue by GSunil19** [MicrosoftDocs/powerbi-docs#2704]
Hi,
We are using Power BI Arc GIS maps without any license or login and my report embedded in web page successfully and working. Did Anything got changed recently, since last few days we were unable to view  embedded Power BI ARC GIS Map control. Can some one help me on this.

Below section says required license and sign-in
publish to web | Yes, for designers signed in to a valid ArcGIS account with the appropriate add-on license. Consumers do not need the add-on license to view published content.
-- | --
Power BI Embedded | Yes, for designers signed in to a valid ArcGIS account with the appropriate add-on license. Consumers do not need the add-on license to view published content.

**_Here is the link for the document._**
https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis#considerations-and-limitations

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf2c48a-66f7-6c38-286e-ae429fc34883
* Version Independent ID: 033ec0fc-5c72-8cf2-20fb-1c7a36ebcd5f
* Content: [Interacting with an ArcGIS map that has been shared with you - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis#considerations-and-limitations)
* Content Source: [powerbi-docs/visuals/power-bi-visualizations-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualizations-arcgis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @GSunil19, thanks for reaching out to us with your comment. I am forwarding it on to the doc owner for consideration.

**Comment by mihart** [comment]
Hi @GSunil19 
It took a minute, but here is the official response from the product team.
"Using the ArcGIS for Power BI visual in a Power BI embedded report was not previously supported, but undocumented workflows exposed an unsupported preview of this feature. In the December 2020 release of ArcGIS for Power BI, Esri provides official support to Report Designers for embedded and publish to web scenarios with the use of an ArcGIS account. Due to some technical limitations within the Power BI environment, the behavior of some visualizations will be limited”

**Comment by GSunil19** [comment]
Thank you so much for the response
