### ISSUE TITLE
Multiple Select without control (ctr) button

### ISSUE THREAD

**Issue by bosschgn** [MicrosoftDocs/powerbi-docs#2742]
Would it be possible to enable multiple select without holding the Control button like it functions on e.g. Ipad / IOS ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02349558-4417-b39f-be59-b80655babdd2
* Version Independent ID: 6c5c0c15-6bf4-e775-1f0e-d95525ec30cf
* Content: [Multi-select data elements in visuals, or multiple visuals, in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-multi-select)
* Content Source: [powerbi-docs/create-reports/desktop-multi-select.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-multi-select.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @bosschgn . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. I've also assigned this to the doc author for review.

**Comment by mihart** [comment]
Hi @bosschgn ,
You can always drag-select and "lasso" together more than one item -- such as visuals on a report page. But I do not know of any other way to multiselect other than these 2 methods - CTRL and lasso.

All the best,
the DOCS team
