### ISSUE TITLE
Adding security group to data source

### ISSUE THREAD

**Issue by ashishrajsrivastava** [MicrosoftDocs/powerbi-docs#275]
I am not able to add a security group as data source member, it does not discover the security group by name . Does a security group has to have a email id assigned to it?

https://docs.microsoft.com/en-us/power-bi/service-gateway-manage#remove-users-from-a-data-source

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87176394-a2d4-7e3d-922e-d124d59fe9c5
* Version Independent ID: 99c3109b-b094-1300-86e2-0cebb4475169
* Content: [Manage a gateway for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-manage#remove-users-from-a-data-source)
* Content Source: [powerbi-docs/service-gateway-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-manage.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ashishrajsrivastava. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. We've also let the writer of this article know about your inquiry, in case the content can be clarified.

**Comment by mgblythe** [comment]
Hi  @ashishrajsrivastava - please follow up with support if you're still having this issue. Closing this out.
