### ISSUE TITLE
connect

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/powerbi-docs#2793]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your submission, @matuhinal - again, we need more context about what issue you've found. Please provide more information here in the Comment area.

**Comment by mihart** [comment]
Hi @matuhinal ,
I see that this Git issue is a bit old, and we haven't heard back from you.  I'm going to close this Git issue.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by matuhinal** [comment]
Thanks! We work with Power BI . Installed the software Power BI

**Comment by matuhinal** [comment]
Thanks! We work with Power BI . Installed the software Power BI
________________________________
От: Michele Hart <notifications@github.com>
Отправлено: 4 марта 2021 г. 10:40
Кому: MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Копия: Matuhinal <ayuditgarantdigital@outlook.com>; Mention <mention@noreply.github.com>
Тема: Re: [MicrosoftDocs/powerbi-docs] connect (#2793)


Closed #2793<https://github.com/MicrosoftDocs/powerbi-docs/issues/2793>.
