### ISSUE TITLE
Price for Power BI Premium per User pro month

### ISSUE THREAD

**Issue by Lea43010** [MicrosoftDocs/powerbi-docs#2806]
Hi together,

how much money cost the Power BI Premium per User pro month?

Thank you very much

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4810006b-6245-ccd5-0d2d-9b1089eb06ab
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User FAQ (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @Lea43010 - Premium Per User licensing is still in preview. During this period there is no charge for the trial experience. We don't have final pricing information available yet and due to currency variations cost information won't be available in our documentation. However, when the feature is generally available, we'll add costs here: https://powerbi.microsoft.com/pricing/ and will update documentation to include a link to that site.  Thanks for the feedback, and for your patience!
