### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by kthejoker** [MicrosoftDocs/powerbi-docs#2809]
Hi, this page hasn't been updated in ... 10 months? Can this be added to someone's todo list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66293710-49bc-2b37-8899-bd917e70d626
* Version Independent ID: 913116b4-7117-ee02-8aff-5be681896a71
* Content: [What's new in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-whats-new)
* Content Source: [powerbi-docs/fundamentals/service-whats-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-whats-new.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @NikhilGaekwad-MSFT
* Microsoft Alias: **nikhilga**

**Comment by kfollis** [comment]
@kthejoker - thanks for bringing that to our attention. The blog updates now cover Power BI mobile and Power BI service in addition to Desktop, so if you're looking for a particular update, you can find it here: https://powerbi.microsoft.com/en-us/blog/. I am assigning your feedback to the article authors so that we can resolve this discrepancy. Appreciate the feedback!

**Comment by mihart** [comment]
Hi @kthejoker , 
Thank you for your suggestion.  We are going to be combining the What's New articles for Desktop and Service in the near future. Please check back in a few weeks.
All the best,
The DOCS team
