### ISSUE TITLE
Possible Explanations not working with December 2020 Update, is it correct?

### ISSUE THREAD

**Issue by JaMePa** [MicrosoftDocs/powerbi-docs#2834]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946c17db-7cc8-70d7-45d5-5502fe115f67
* Version Independent ID: 62a891ef-32c6-9913-699c-dfed292839d7
* Content: [Anomaly detection tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-anomaly-detection)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-anomaly-detection.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-anomaly-detection.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by paulinbar** [comment]
Hi @JaMePa, thanks for reaching out. I'm forwarding your comment on to the doc author for consideration.

**Comment by mihart** [comment]
Hi @, 
Thank you for your question.  Some anomaly points won't return explanations, because there simply isn't enough information to explain that point with confidence. There is a Community thread called "Share your thoughts on the new Anomaly detection feature (preview)".  You may find a more detailed answer there....or, you can post your own question which is read by the Product team. 
https://community.powerbi.com/t5/Desktop/Share-your-thoughts-on-the-new-Anomaly-detection-feature-preview/td-p/1490886

All the best,
The DOCS team
