### ISSUE TITLE
Power BI Admin rights

### ISSUE THREAD

**Issue by linekrogh** [MicrosoftDocs/powerbi-docs#2841]
What does it mean when a Power BI admin has "Manage workspaces"-rights? Does it mean the person also have access to the data in the workspaces?
We have a situation where the developers/it admin people are not allowed to have access to production data. Thus, I am not sure if giving a person the power bi admin roles will violates this security rule?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d7371c-d74d-6e7f-e6d2-77cff1d888a2
* Version Independent ID: ed31ccb5-e72f-0867-bb2e-100e76e7de72
* Content: [What is Power BI administration? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-administering-power-bi-in-your-organization)
* Content Source: [powerbi-docs/admin/service-admin-administering-power-bi-in-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-administering-power-bi-in-your-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @linekrogh, good question. Let me check that and I'll get back to you.

**Comment by paulinbar** [comment]
Hi @linekrogh, on the face of it, it looks like giving assigning a person the Power BI admin role violates your policy, because a Power BI admin may go into the Admin Portal > Workspaces, where they'll see all the personal and group workspaces in the organization. They can then select a workspace and add themselves as an admin or other role to the workspace. After that they will have access to the data in that workspace. I am checking to see if there is any remedy for this situation. I suggest you also describe your situation on the [Power BI Community]( https://community.powerbi.com). Someone may have experienced the same issue and have something to say about it. In the meantime I'm closing this issue, but if I hear back about a remedy I'll let you know. Thanks for bringing this up!
