### ISSUE TITLE
Lack of information on sorting categorical data which are represented in numbers

### ISSUE THREAD

**Issue by learnd-online** [MicrosoftDocs/powerbi-docs#2870]
I was directed to this page from: https://docs.microsoft.com/en-us/power-bi/consumer/end-user-change-sort

which promised:

> Sometimes, you want to sort your visual using a different field (that isn't included in the visual) or other criteria. **For example, you might want to sort by month in sequential order (and not in alphabetical order) or you might want to sort by entire numbers instead of by digit (example, 0, 1, 9, 20 and not 0, 1, 20, 9).**

Yet this specific point is not addressed in this tutorial. Disappointing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @learnd-online -- sorry you were disappointed! This article does address sorting a month field/column by another, related field/column; see this section:
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column#sort-using-the-sort-by-column-button
That is by far the most common use case for sorting by a different column.
Does that help?

**Comment by mihart** [comment]
Hi @learnd-online ,
I see that this Git issue is a bit old and there hasn't been any recent activity, so I'm going to close it.  I hope that you were able to get your questions answered.I did update the source article to make it a bit more clear that only the designer of the report can make the changes necessary to allow / fix sorting issues.  Because the designer has edit permissions to the data, they are able to create new columns that allow sorting to be sequential by number or month.  The destination article has instructions for doing just that. If you still have questions, a good resource is the community site community.powerbi.com.
All the best,
the DOCS team
