### ISSUE TITLE
full report attachment feature

### ISSUE THREAD

**Issue by JayG68** [MicrosoftDocs/powerbi-docs#2888]
The number of pages depends on metadata and sections count in the browser trace for a report when creating the subscription which can be different from the total number of pages the customer actually sees. Example customer has 17 pages but when doing a browser trace the metadata and sections total 22 pages. This is in the https://wabi......../exloration represented in the Json response. It will trigger an error because they are over 20 pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35489ab-e39e-b7be-588d-38f26ccf5442
* Version Independent ID: f5145d5d-afbc-f3f0-7275-1186b60890d0
* Content: [Subscribe yourself to reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by amd-yan** [comment]
Thanks for creating the issue for us, James.  It's very common to have hidden tabs in the report for various reasons, for example:
1. Newly added visuals that have not passed our internal gate review
2. Visuals are not working due to data issues that we would like to hide from the users temporarily.

When we call the following APIs to extract and download the report, these hidden tabs will not be extracted. I wonder why they will be counted when users subscribe via the UI? 

```
"https://api.powerbi.com/v1.0/myorg/groups/{group_id}/reports/{report_id}/ExportTo"
"https://api.powerbi.com/v1.0/myorg/groups/{group_id}/reports/{report_id}/exports/{export_id}"
"https://api.powerbi.com/v1.0/myorg/groups/{group_id}/reports/{report_id}/exports/{export_id}/file"
```
The subscription function is very critical to us because it allows users to self-service themselves on demand. Please keep us posted on the progress!

Last but not least, I would like to take this opportunity to request another feature - it would be great if we can subscribe/extract reports based on benchmarks. Without that function, we have to duplicate the same visual multiple times if users want to have different views in the extract.

Thank you!

**Comment by maggiesMSFT** [comment]
Hi, @jagracemicrosoftsupport and @amd-yan -- thanks for your comments! Assigning to the author to investigate.

**Comment by jagracemicrosoftsupport** [comment]
Hello Edwin


  1.  Just letting you know they will be getting the request to the Author Keep track of it using the link in the previously provided email.

**Comment by jagracemicrosoftsupport** [comment]
Ignore this

From: James Grace ***@***.***>
Sent: Friday, March 12, 2021 5:04 PM
To: MicrosoftDocs/powerbi-docs ***@***.***>; MicrosoftDocs/powerbi-docs ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [MicrosoftDocs/powerbi-docs] full report attachment feature (#2888)

Hello Edwin


  1.  Just letting you know they will be getting the request to the Author Keep track of it using the link in the previously provided email.

**Comment by amd-yan** [comment]
Thank you, James & Maggie. Please keep me posted!

**Comment by mihart** [comment]
Hi @JayG68 , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
