### ISSUE TITLE
No support for NUMERIC datatype

### ISSUE THREAD

**Issue by yiga2** [MicrosoftDocs/powerbi-docs#290]
Unfortunately PBI does not support the NUMERIC datatype of BigQuery, which is the default type for recording financial and accounting data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Connect to a Google BigQuery database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-bigquery)
* Content Source: [powerbi-docs/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-bigquery.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Thanks for your comment,  @yiga2.  It looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by yiga2** [comment]
This was reported earlier [here](https://community.powerbi.com/t5/Issues/PBI-Desktop-BigQuery-connector-no-support-for-NUMERIC-type/idi-p/489670) with no traction from the engineering team so it would only be fair to add a disclaimer to the documentation re the unsupported datatype.
