### ISSUE TITLE
We have several external users. In ad-hoc approach : how we can add many users to share the report. Any automation can done on this using less code approach?

### ISSUE THREAD

**Issue by PrashantKumbhar2** [MicrosoftDocs/powerbi-docs#2900]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70ccdae-1552-2465-be6f-d47cd260ad8e
* Version Independent ID: 1ffea5bb-64b0-2661-801e-9eec46e6eec1
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi)
* Content Source: [powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
All the best,
the DOCS team
