### ISSUE TITLE
Missing information on Power BI internal traffic

### ISSUE THREAD

**Issue by Dirkgu01** [MicrosoftDocs/powerbi-docs#2912]
[Enter feedback here]
The document only covers egress costs for communication between Power BI and Azure datasources.
It would be helpful to also cover egress costs (or lack thereof) between geographically remote Premium Capacity Nodes and the Power Bi tenant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0577c02-6c3e-870c-ddee-d93cafef9206
* Version Independent ID: b9c65245-32e4-8bc9-8971-e76bff0ad837
* Content: [Power BI and Azure egress - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-azure-egress-power-bi)
* Content Source: [powerbi-docs/connect-data/service-azure-egress-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-azure-egress-power-bi.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @Dirkgu01, thanks for reaching out to us. I am forwarding your comment along to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Dirkgu01 .

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
