### ISSUE TITLE
Non-Azure embedding?

### ISSUE THREAD

**Issue by eino-makitalo** [MicrosoftDocs/powerbi-docs#292]
If I am using non Microsoft hosting how to embed "App owns data" version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7d9793-ede4-653a-bc25-cf91be807edb
* Version Independent ID: bb12e45c-9aaa-97b2-cfc7-31e1c511fd00
* Content: [Embedding with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedding#embedding-for-your-customers)
* Content Source: [powerbi-docs/developer/embedding.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedding.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
eino-makitalo Hello, thank you for your comment. 

Power BI and Power BI Embedded are tied to Azure Active Directory.  So Azure is required.

**Comment by markingmyname** [comment]
@eino-makitalo We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by DonzellDawson** [comment]
Thank you @markingmyname for your timely response.  

What I understand from @eino-makitalo inquiry and your reply is that I am not able to utilize our created PBI embedded links for our PBI reports to display on our digital signage (ScreenCloud) screens.  When we try illustrate our reports through our digital signage screens we get the PBI Sign In Page instead because we haven't tied  to Azure Active Directory yet.

If that is correct our next step to display our reports in ScreenCloud tie to Azure Active Directory?
