### ISSUE TITLE
Cancelling Dataset refresh

### ISSUE THREAD

**Issue by thomasbibin** [MicrosoftDocs/powerbi-docs#2941]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by thomasbibin** [comment]
Dataset refresh cannot be cancelled in the middle, as of now right. Can we expect this feature?

**Comment by mihart** [comment]
Thanks for your comment, @thomasbibin . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
All the best,
the DOCS team
