### ISSUE TITLE
How to delete from Recents?

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#2942]
Hi,
Isn't really a shame that one can not delete anything from Recents ? Even deleted reports keep showing here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e1e445-7f15-0f2a-f71a-1cc2bdd97fca
* Version Independent ID: a96c4c4e-0d4f-060e-1b67-5b60c2652259
* Content: [Favorites in the Power BI service (dashboards, reports, apps) - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-favorite)
* Content Source: [powerbi-docs/consumer/end-user-favorite.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-favorite.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Thanks for your comment, @gvggvg. This looks more like product rather than documentation feedback. You can submit product feedback or ideas for features by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
