### ISSUE TITLE
Printing limitation

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#3011]
Regarding

> R visuals currently do not print with dashboard and reports printing.

In Power BI Service:

- The File => Print this Page option seems to work fine
- The Export => PDF option returns "R visuals are not supported with this operation." for the R visual

Can this limitation please be elaborated on, to clarify what printing scenarios are supported vs. unsupported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c7931b-9fbb-bec4-09c4-9c827e4ec7a1
* Version Independent ID: 7ebc1400-482b-62e6-3747-bb7ffdb1dcf3
* Content: [Create advanced analytics and visualizations using R scripts - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals)
* Content Source: [powerbi-docs/visuals/service-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/service-r-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @VitalyMCT.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
