### ISSUE TITLE
Oracle support - dynamic m query parameters

### ISSUE THREAD

**Issue by guidogabriel** [MicrosoftDocs/powerbi-docs#3057]
[Enter feedback here]
To be perfect, Oracle should be supported to dynamic m query parameters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment, @guidogabriel. This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).  In the meantime I'm closing this as a documentation issue. Please reopen if I've misunderstood your feedback. Thanks for reaching out!
