### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by regbac** [MicrosoftDocs/powerbi-docs#308]
Hi,
you might want to correct that title :
"Changed Power IB gateway data source users"
Cheers
Regis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Using auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Good catch, @regbac! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!
Did you know: In the future, if you see a typo or other small fix, you can create your own pull request. That's the fastest for us to fix because we just have to approve the PR. Just click the Edit pencil in the upper-right corner.
Thanks again --

**Comment by mgblythe** [comment]
Fixed this, thanks!
