### ISSUE TITLE
Anomaly Explanations Not Finding Best Explanation

### ISSUE THREAD

**Issue by nvanlent** [MicrosoftDocs/powerbi-docs#3081]
I tried the anomaly feature for the first time today.  When manually figuring out where an anomaly comes from, I narrowed it down to a single material.  However, the possible explanations doesn't list the material, even when I include it in the "Explain by" list.  I know the anomaly is coming from a single material, because if I use a slicer to exclude the one material, then the anomaly goes away.

![image](https://user-images.githubusercontent.com/55983553/120019086-01cb8400-bfb6-11eb-87bd-f8a317d1df13.png)

![image](https://user-images.githubusercontent.com/55983553/120019172-1c9df880-bfb6-11eb-9f52-f5663c820a68.png)

**Comment by paulinbar** [comment]
Thanks for your comment, @nvanlent. This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com). I really appreciate the time you took to provide the detailed feedback though. While you should submit this online as feedback, I am also going to forward your comment on to the team that developed that feature.
