### ISSUE TITLE
Right click to group not working in May 2021 Release

### ISSUE THREAD

**Issue by dsdesrosiers** [MicrosoftDocs/powerbi-docs#3082]
Two potential issues...

1. Downloaded May 2021 Release and found some PBIX files were now longer grouping visuals that we had - everything was just a spaghetti mess since we use the groups to show/hide sets of objects.

2. Multi-select with CTRL-Click and right click is not producing the option to Group. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6669843-8752-7777-31e8-1d1e4ec96648
* Version Independent ID: b7be0303-1882-621e-a630-32895aafa84d
* Content: [Use grouping in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-grouping-visuals)
* Content Source: [powerbi-docs/create-reports/desktop-grouping-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-grouping-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment, @dsdesrosiers. This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
