### ISSUE TITLE
Period missing at end of sentence.

### ISSUE THREAD

**Issue by Dan1480** [MicrosoftDocs/powerbi-docs#3108]
The following sentence does not have a period at its end.
"To understand which workloads are supported for each tier, refer to the Configure workloads in a Premium capacity article"
Call me picky, but it messes up my screen reader.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @Dan1480,

Thank you for pointing this out. I'll add a full stop at the end of this sentence shortly.

**Comment by KesemSharabi** [comment]
Hi @Dan1480,

Once again, thanks for your feedback. This issue is now fixed - see [Capacity and SKUs](https://docs.microsoft.com/power-bi/developer/embedded/embedded-capacity#capacity-and-skus).

![image](https://user-images.githubusercontent.com/54834915/121476448-5962ea00-c9cf-11eb-8bfa-46ec59312466.png)

Thanks,

Kesem
