### ISSUE TITLE
Sr Database Analyst

### ISSUE THREAD

**Issue by odeddror** [MicrosoftDocs/powerbi-docs#311]
How do you create these Agg tables you just showed? I'm stack with how to create these tables
Also Is there any way to get these sample as Power BI files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [Use Aggregations in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-aggregations)
* Content Source: [powerbi-docs/desktop-aggregations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-aggregations.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @odeddror , thank you for submitting feedback. I have assigned your question to the author. He will follow up for more info if needed.

**Comment by odeddror** [comment]
Kelley,
Thank you for doing that.
Oded Dror

**Comment by davidiseminger** [comment]
Sorry for the delay, and thanks for your comment, @odeddror . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 

Sample Desktop files are available in the following link: https://github.com/Microsoft/powerbi-desktop-samples/tree/master/2018

**Comment by odeddror** [comment]
Thanks

**Comment by Mholsen** [comment]
I noticed that too and wondered why the actual creation of the aggregation table wasn't included in the article.
Anyway, this Microsoft guide goes through how to create an aggregation table:
https://www.youtube.com/watch?v=RdHSo43LkQg&t=45s
