### ISSUE TITLE
Setting Alert Option is missing from a tile

### ISSUE THREAD

**Issue by dipteshbose** [MicrosoftDocs/powerbi-docs#3117]
Setting Alert Option is missing from a tile. Even for Gauges, the option does not show up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35489ab-e39e-b7be-588d-38f26ccf5442
* Version Independent ID: f5145d5d-afbc-f3f0-7275-1186b60890d0
* Content: [Subscribe yourself to reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
@dipteshbose - thanks for the feedback. I found the procedure you're referencing in this article: https://docs.microsoft.com/en-us/power-bi/consumer/end-user-alerts, but will assign this issue to the writer to verify the steps and note any exceptions you may encounter.

**Comment by dipteshbose** [comment]
![Picture1](https://user-images.githubusercontent.com/65800453/123580812-2f475f80-d7f8-11eb-87c3-860e4d2f6397.jpg)

There is no option to create an alert. I have attached a snapshot. Kindly investigate as I need this feature to be enabled to write a power automate workflow.

**Comment by mihart** [comment]
Thanks for your comment, @dipteshbose . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com.  You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.).
