### ISSUE TITLE
Premium per Capacity vs PPU

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/powerbi-docs#3125]
The table in this section needs to be updated to clarify that there are differences between PPC and PPU workspaces
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-licensing-organization#license-types-and-capabilities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec63d236-fde3-47d8-96a5-5d205dd96b59
* Version Independent ID: 0f9cc0dc-e417-ed61-ff2a-7155cdadf8c5
* Content: [Power BI licensing for users in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-licensing-organization)
* Content Source: [powerbi-docs/admin/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @danmyhre -- thanks for asking! Assigning to the author to respond.

**Comment by mihart** [comment]
Hi @danmyhre ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
