### ISSUE TITLE
Issue with data in Lab 05A - January 2021 release

### ISSUE THREAD

**Issue by kasavin** [MicrosoftDocs/powerbi-docs#3167]
On page 8, steps 21-22, after I execute the query with Fiscal Year = FY2020, the data is not consistent with what I should see in the "Sales Performance Status" column according to the lab.

Here's what I see - null values: 

![image](https://user-images.githubusercontent.com/2432736/124197767-e52eda00-da94-11eb-8ec1-f7ef178323f8.png)

And here's what the lab describes:

![image](https://user-images.githubusercontent.com/2432736/124197814-f7107d00-da94-11eb-9ec0-01e84c9ce400.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0439d49-76b1-380b-f226-317e96ca0397
* Version Independent ID: 2dd9f620-5244-936f-76f9-1f32f5ac5a23
* Content: [Power BI Paginated Reports in a Day course - Power BI](https://docs.microsoft.com/en-us/power-bi/learning-catalog/paginated-reports-online-course)
* Content Source: [powerbi-docs/learning-catalog/paginated-reports-online-course.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/learning-catalog/paginated-reports-online-course.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by kasavin** [comment]
It works properly if I set FY2019.

**Comment by peter-myers** [comment]
Hi @kasavin - thanks for point out this issue. It's a known issue, and it's because the instructions to connect to the database are wrong (see the **MyEnvironment.txt** file). If you're using the latest version of the course (copyright year is 2021), you will use the **AdventureWorksDW2021-PRIAD** database. Otherwise, use the _DW2020_ database. A fix is on it's way! Thanks again. #please-close
