### ISSUE TITLE
DeployAll Issues

### ISSUE THREAD

**Issue by CharlesAbetz** [MicrosoftDocs/powerbi-docs#3168]
Hi 

When I try to use a Service Principal to do a DeployAll from Dev to Test, I get the 400 bad request error, using Powershell cmdlets, (I used postman to get the actual error as Powershell doesn't tell me much).

Json Request
```
{
    "sourceStageOrder": 0,
    "options": {
        "allowCreateArtifact": true,
        "allowOverwriteArtifact": true
    }
}
```

Json Response
```
{
    "error": {
        "code": "ALM_InvalidRequest_ServicePrincipalNotSupported",
        "pbi.error": {
            "code": "ALM_InvalidRequest_ServicePrincipalNotSupported",
            "parameters": {},
            "details": [],
            "exceptionCulprit": 1
        }
    }
}
```

Is there a reason why the Service Principal isn't supported?

**Comment by paulinbar** [comment]
Hi @CharlesAbetz,  thanks for your comment. This looks like a support request or product question rather than documentation feedback. Is there a particular docs article that you think needs to be enhanced? If it's more a product question you might find an answer in the [Power BI Community]( https://community.powerbi.com) or not, try our [support page](https://support.powerbi.com). Thanks!
