### ISSUE TITLE
Price sheets availability is ambiguous

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3186]
Hello,

In this page, it isn't clear whether Pricesheet data is available for MCA agreements.  It states "Applicable meter rates for the provided billing profile or EA enrollment" but doesn't clarify whether that means it is only for EA or also for MCA?

Thanks!
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi Chris, and thanks for your question. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 

If you do learn, through community or support, that it also applies for MCA, let us know here (or a new post) and we'll be happy to update!
