### ISSUE TITLE
Unable to connect to the new app (preview) workspace

### ISSUE THREAD

**Issue by renaudma** [MicrosoftDocs/powerbi-docs#321]
Since the new app workspace is out (still in preview mode), i am unable to connect to my data in these workspace. The workspace does not appear in the drilldown list of PBI workspaces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458afd24-a62a-7944-5cd4-de9a9290c308
* Version Independent ID: ed6a56f0-e067-9f92-5d54-6755b49f3bc0
* Content: [Power BI publisher for Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/publisher-for-excel)
* Content Source: [powerbi-docs/publisher-for-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/publisher-for-excel.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@renaudma Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by SheepieOz** [comment]
Is there any progress on this?  The lack of this functionality in the new workspaces is concerning.

**Comment by davidiseminger** [comment]
Sorry about the trouble you're having, and thanks for your comment, @renaudma . This may have cleared up, but looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by hildeirin** [comment]
Did you find a solution to this? :)
