### ISSUE TITLE
Did Power BI team invent new Waterfall chart style?

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#3224]
This is not classical Waterfall chart. Please change its name if you want to stick to this your invention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b1f7d8-878d-b683-8f01-cce8a1bc5c46
* Version Independent ID: a1d829f2-8171-2618-ce22-cb80e1cdb72d
* Content: [Waterfall charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-waterfall-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-waterfall-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-waterfall-charts.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @gvggvg. This looks like a support request or product question rather than documentation feedback. You might want to post this as an idea at https://ideas.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
