### ISSUE TITLE
It is taking too much time export single report with only one page

### ISSUE THREAD

**Issue by er-mohd-ali** [MicrosoftDocs/powerbi-docs#3225]
I have Embedded A1 SKU capacity. I tried exporting report using export API but it is taking too much time to export report with single page only, how can I make it faster in terms of export time with filters. Also when this service will be generally available? What about limitations, there are a lot of limitations as of now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI embedded analytics reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @er-mohd-ali. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

As for general availability (GA) and limitations, I currently have no ETA.

Thanks,

Kesem
