### ISSUE TITLE
power bi service asks to set up account that has been running for years

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#3227]
Why Power bi service started asking to set up account that has been running for years ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09828fad-a8e9-a2b3-0942-6e19724fa00b
* Version Independent ID: 4b67d4da-c2b7-a6ef-e511-7e61b6b35c58
* Content: [Sign up or purchase the Power BI service as an individual - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-self-service-signup-for-power-bi)
* Content Source: [powerbi-docs/fundamentals/service-self-service-signup-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-self-service-signup-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @gvggvg . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
