### ISSUE TITLE
Sensitivity to the DAX code

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#3235]
Why not apply sensitivity to DAX code too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ffb799-4e1a-c47c-749e-c27b0bd0ae65
* Version Independent ID: 7744ac08-00fd-62d1-6014-14b96f0f2f2f
* Content: [Microsoft Information Protection sensitivity labels in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-sensitivity-label-overview#defaultlabelpolicydesktop)
* Content Source: [powerbi-docs/admin/service-security-sensitivity-label-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-sensitivity-label-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Thanks for your comment, @gvggvg. This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
