### ISSUE TITLE
Using a service principal app to access Admin read-only endpoints

### ISSUE THREAD

**Issue by sheepworrier** [MicrosoftDocs/powerbi-docs#3262]
I'm trying to use the Power BI REST API Admin endpoints, e.g. [GetGroupsAsAdmin](https://docs.microsoft.com/en-us/rest/api/power-bi/admin/groups-get-groups-as-admin) to create a picture of Power BI usage in my tenancy.

I've followed the steps to register an app with Application permissions of Tenant.Read.All.  I've added the app to a security group and granted access to that group in the Power BI Admin Portal.  However, when I then try and generate an access token [here](https://login.microsoftonline.com/common/oauth2/v2.0/token) I get a 400 Bad Request error.

> AADSTS65001: The user or administrator has not consented to use the application.....  Send an interactive authorization request for this user and resource.

So, I've gone through the interactive request (again) from Azure Portal -> Azure Active Directory -> Enterprise Applications -> My App -> Permissions -> Grant admin consent for Default Directory, but it makes no difference.

I notice on this page there is the following comment:

> Make sure there are no Power BI admin-consent-required permissions set on this application

However, how is this possible when using an Application-granted permission?  Aren't these all granted through admin consent?

I created a 2nd app using Delegated permissions and it worked as expected in my own tenancy where I am an Admin.  However, this option won't work for me in the tenant I want to use it for, as I'm not an Administrator there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd7616-4a1c-fe01-1b6b-6190bd2fdb63
* Version Independent ID: 93839448-4a4b-5489-14d4-6eebe4b3d34a
* Content: [Enable service principal authentication for read-only admin APIs - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication)
* Content Source: [powerbi-docs/admin/read-only-apis-service-principal-authentication.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/read-only-apis-service-principal-authentication.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @sheepworrier, did you enable the **Allow service principals to use read-only Power BI admin APIs** tenant setting and add the security group where you put your apps service principal? i.e. step 4 in the instructions? From your description, it sounds like you did, but if you are not an administrator on the tenant, then I am puzzled about how you managed to enable the tenant switch.

That said, I have to say that most people run into trouble because they don't notice this: "Make sure there are no Power BI admin-consent-required permissions set on this application" -  but you did. Unfortunately I myself don't understand that issue well enough to be able to help you much there. I can find someone though. First, however, let me know whether that tenant setting is enabled and has the correct security group specified. 
Thanks!

**Comment by sheepworrier** [comment]
Sorry for the confusion.  I am trying this out on a tenancy where I am the administrator, but ultimately want to implement this on a tenancy where I am not the administrator.

So on the tenancy I am the administrator I have enabled the tenant setting and specified the security group.  Look forward to hearing from someone with more info on "Make sure there are no Power BI admin-consent-required permissions set on this application"

**Comment by paulinbar** [comment]
Hi @sheepworrier, ok, will try to locate the person I'm thinking of. In the meantime, here is a blurb from one support ticket. Not sure whether it's relevant for you, but just in case: 

"This is regarding Service Principal calling Admin API in power bi. We followed below documentation and found that we were getting “PowerBINotAuthorizedException”. Upon investigation we found , we needed to remove Tenant.ReadAll and Tenant.ReadWriteAll in Azure portal to get Admin API’s working."

**Comment by sheepworrier** [comment]
> Hi @sheepworrier, ok, will try to locate the person I'm thinking of. In the meantime, here is a blurb from one support ticket. Not sure whether it's relevant for you, but just in case:
> 
> "This is regarding Service Principal calling Admin API in power bi. We followed below documentation and found that we were getting “PowerBINotAuthorizedException”. Upon investigation we found , we needed to remove Tenant.ReadAll and Tenant.ReadWriteAll in Azure portal to get Admin API’s working."

Thanks - that also sounds counter intuitive as the Admin API [documentation](https://docs.microsoft.com/en-us/rest/api/power-bi/admin/groups-get-groups-as-admin) says you need to have Tenant.Read.All scope

**Comment by sheepworrier** [comment]
> @sheepworrier , here is a screenshot from a thread about this:
> ![image](https://user-images.githubusercontent.com/54644589/130650526-5bb2207b-abd8-4957-9ef2-4a5d4a32f153.png)
> 
> Maybe that means that you have to make sure that the service principal has not been assigned any Power BI admin role. Then, by virtue of being in the security group included in the that tenant setting, it has permission to run, even without having an admin role. I would imagine that you also have to make sure that the security group you put the service principal in does not have any Power BI admin role as well.

I think some screenshots would be really helpful here :-)

**Comment by Acteon-Jon** [comment]
I've raised such a similar issue just now, almost 12 months after this one which remains open - can I ask if there was a resolution that can be noted here to help anyone else with similar issues?  Thanks!

**Comment by paulinbar** [comment]
Hi @sheepworrier and @Acteon-Jon , sorry for the long delay. The document this issue is based on has been revised to give a bit more information about that "no Power BI admin roles" problem. Apparently, if there are such permissions for Power BI on an app, and you are authenticating using a service principal, for the read only scanner APIs this causes problem. 

Anyway, please see the document again, and particularly this section: https://learn.microsoft.com/en-us/power-bi/enterprise/read-only-apis-service-principal-authentication#how-to-check-if-your-app-has-admin-consent-required-permissions. 

See also the note at the end of the intro in this article: https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-metadata-scanning

I am closing this issue now, but let me know if you are still encountering problems. Thanks!

**Comment by Acteon-Jon** [comment]
Hi Paul - thanks for the update, I think the docs are slightly clearer now, however I feel I must leave a short note here to say that following signficant time spent with PBI Pro Support (MindTree) they finally got it working by assigning permissions per the image below;
![image](https://user-images.githubusercontent.com/89031845/218040271-f2d529b3-3d62-482e-a673-a708c3285d87.png)

This appears to indicate that you are to assign API permissions for Power BI Service, which **_require_** Admin Consent, but that Admin Consent **_must not be Granted_**.

I can only tell you that it works now using this approach, MindTree were very helpful, but couldn't/wouldn't tell me why/how this works ;)
