### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by LukaszPawlowski-MS** [MicrosoftDocs/powerbi-docs#3295]
1. Wow this reads well :).  Super simple and friendly. Love the tone and balance for new users. 
2. Lets update the Datasets hub screenshot to show a recommended section with certified / promoted and some preview images. That will make it look more compelling
3. I'm wondering if we should add some  additional topics on some features to try (Q&A visual, small multiples, conditional formatting, text summaries) because those are 'wow' moments for users and they probably won't find them without prompting.
4. For auto gen report on quick create we should mention that users should slice the data by clicking a data point
5. We should link out to docs for Analyze in Excel, Sharepoint list reports Visualize in Power BI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e112abc-f3ec-bca8-7e02-9f9ca0116314
* Version Independent ID: 65db863b-4001-133f-5831-e37bb0d4f347
* Content: [Create reports from data in Microsoft Teams - Power BI](https://review.docs.microsoft.com/en-us/power-bi/consumer/business-user-teams-create-reports?branch=pr-en-us-6384)
* Content Source: [powerbi-docs/consumer/business-user-teams-create-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/business-user-teams-create-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks for the feedback, @LukaszPawlowski-MS ! Somehow it didn't bubble up to my attention - oh, I just noticed - it's in the public repo! I'm going to add it to the PR and close this. 

Wow this reads well :). Super simple and friendly. Love the tone and balance for new users.

1. Lets update the Datasets hub screenshot to show a recommended section with certified / promoted and some preview images. That will make it look more compelling
Done.
2. I'm wondering if we should add some additional topics on some features to try (Q&A visual, small multiples, conditional formatting, text summaries) because those are 'wow' moments for users and they probably won't find them without prompting.
3. For auto gen report on quick create we should mention that users should slice the data by clicking a data point
4. We should link out to docs for Analyze in Excel, Sharepoint list reports Visualize in Power BI
