### ISSUE TITLE
Missing licensing and pricing information

### ISSUE THREAD

**Issue by anna907** [MicrosoftDocs/powerbi-docs#3321]
There seems to be a problem with the licensing and requirements part in the document.

The doc says 
"An Azure Information Protection Premium P1 or Premium P2 license is required to apply or view Microsoft Information Protection sensitivity labels in Power BI. Azure Information Protection can be purchased either standalone or through one of the Microsoft licensing suites. See Azure Information Protection pricing for detail."

When clicking on the Azure Information Protection pricing link it is a dead end, the doc is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f556c227-ceb4-0712-14eb-f52b448ac158
* Version Independent ID: 0a07a48c-3500-d862-d9fd-b3a04a180557
* Content: [Enable sensitivity labels in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-enable-data-sensitivity-labels)
* Content Source: [powerbi-docs/admin/service-security-enable-data-sensitivity-labels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-enable-data-sensitivity-labels.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @anna907, thanks for bringing this to my attention. I'll look into it today. Thanks!

**Comment by paulinbar** [comment]
@anna907, hi again. I see that the pricing link points to:
https://azure.microsoft.com/services/information-protection/

When I click the link it resolves to here, and everything seems ok. Note that the browser has localized the link (i.e. inserted "en-us)" to indicate English:
https://azure.microsoft.com/en-us/services/information-protection/

Do you usually view things in your browser in English or in another language? I am wondering if perhaps the licensing page does not have a version in the language your browser is set to, if indeed it is set to something other than English. What happens if you  try this link:
https://azure.microsoft.com/en-us/services/information-protection/
Please let me know how it goes for you - this will help me fix the issue. Thanks!

**Comment by anna907** [comment]
Hi @paulinbar 
I checked again. The Azure information protection page opens, that's right - however there is no pricing information. When I click in the Pricing details tab the page says as follows: "We're sorry, this download is no longer available."

(by the way I am using english as my browser language)

**Comment by paulinbar** [comment]
Hi @anna907, ok, yes, I see what you mean - the pricing info isn't available on that tab. I'll bring that to the attention of the people who manage that page and then make any changes to our page that are necessary as a result of their fix. So for the meantime I will close this issue. Thanks for calling this out, and also following up with more info!
