### ISSUE TITLE
Improve this page by adding a Troubleshooting section

### ISSUE THREAD

**Issue by alex--thomas** [MicrosoftDocs/powerbi-docs#3328]
I keep having issues mapping from the uploaded Dataset to a Data Source defined in a PBI Gateway, at this step here:

![image](https://user-images.githubusercontent.com/1146247/135787022-653a4884-90e6-4172-baad-75a5c437655d.png)

[Enter feedback here]

Maybe this is because I just want to select a pre-existing defined Data Source on the Gateway, but this UI means I can only Create one?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sql-tutorial)
* Content Source: [powerbi-docs/connect-data/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @alex--thomas.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
