### ISSUE TITLE
Gb vs GB

### ISSUE THREAD

**Issue by bmtorres** [MicrosoftDocs/powerbi-docs#3350]
[Hi,

I saw that some parts of this document use GB (Capacity nodes for Premium Gen2), while other parts use Gb (the table summarizing the information). The problem is that GB is Gigabyte and Gb is Gigabit. I believe it should be GB in all cases.] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f3d17a8-8258-5246-24bb-b69c273d06c4
* Version Independent ID: 36f06d1c-4f46-598d-c300-eb4dd22d4487
* Content: [What is Power BI Premium Gen2? (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is)
* Content Source: [powerbi-docs/admin/service-premium-gen2-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-gen2-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @bmtorres,

Thank you for your comment, I'm looking into it and will fix the documentation accordingly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @bmtorres,

Thank you for brining this to our attention. You're are right, the table in the end of the [Limitations in Premium Gen2](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-what-is#limitations-in-premium-gen2) section, describes everything in GB (Gigabyte).

This issue is now fixed:

![image](https://user-images.githubusercontent.com/54834915/142007561-bd2c9cf3-8dc1-4670-b9fa-033cd37d149d.png)

Thanks,

Kesem
