### ISSUE TITLE
This article says you can use multi valued parameters in the Power BI Desktop Report Builder, but you can't

### ISSUE THREAD

**Issue by PAPutzback** [MicrosoftDocs/powerbi-docs#3363]
I had no luck using multi value parameters with a SQL dataset. Searching the Power BI forums I found this has not been implemented yet and that I should  submit my post to the ideas page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009519a7-b9c5-c388-53ce-d0e765fef750
* Version Independent ID: 0566119f-c2fc-3d1c-6eaf-f80910635022
* Content: [Create parameters for paginated reports in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-parameters)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-parameters.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @PAPutzback -- sorry for the delay in responding! I'm checking with the product team and will get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @PAPutzback -- The product team asks that you enter a support ticket at https://powerbi.microsoft.com/en-us/support/, "as it may be related to a known bug to be fixed in the Jan release of Power BI Report Server." 
Also, just to clarify, when you say "PBI Desktop for RB" -- I'm assuming you mean Power BI Report Builder, https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-power-bi, 
not Power BI Desktop, https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop. 
Is that correct?
Hope that helps!
