### ISSUE TITLE
Which Power BI version

### ISSUE THREAD

**Issue by mbarison** [MicrosoftDocs/powerbi-docs#3383]
Can you please specify which version of PBI Desktop/Server support the custom maps feature?

**Comment by mihart** [comment]
Thanks for your comment, @mbarison . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
