### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by anshulbb** [MicrosoftDocs/powerbi-docs#3394]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da6c49a-f7cc-213c-adc3-5b33b76716dd
* Version Independent ID: 2be2786b-c764-c142-0821-24f6a28b2459
* Content: [Smart narratives tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-smart-narrative)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-smart-narrative.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-smart-narrative.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by davidiseminger** [comment]
Hello @anshulbb -- can you provide some context around what issue you'd like to raise about this article? In order for us to address it, we need to know where you believe it could use attention, with specifics. Thanks.

**Comment by paulinbar** [comment]
Hi @anshulbb, it's been awhile since we requested bit more info so that we can move forward in addressing your issue. Since we haven't heard back from you, I am going to close this issue for the meanwhile. Please feel free to reopen the issue though if it is still relevant, but please provide a bit more context. Thanks!
