### ISSUE TITLE
Filter option wont work if table starts with a number and contains spaces

### ISSUE THREAD

**Issue by powerbraps** [MicrosoftDocs/powerbi-docs#340]
While using filter in URL, I found that the filter won't work if the table name starts with a number and contains spaces (ex: 2 Table) but works the other way around (ex: Table 2).

I tried the _x0020_ escape on the table name and that did not work, contrary to your documents. A filter example would be: ?filter=2_x0020_Table/Column1 eq 'a' 

The documentation in specific is : https://docs.microsoft.com/en-us/power-bi/service-url-filters

Could you advise on this error?
Thank you.

**Comment by maggiesMSFT** [comment]
Hi @powerbraps -- Got you a great answer:

I don’t think this is related to the spaces. This is an OData limitation that is defined by their rules for identifiers, and I included sources below. Unfortunately these were the only official sources I could find, but they are overly technical.

To summarize them, an OData identifier must start with a letter or underscore, so we don’t support identifiers that start with a number.

But we do support these identifiers in Power BI, since we added extra support for escaping characters using the _HEXC_ syntax. Based on the user’s Github example:
•	?filter=2_x0020_Table/Column1 eq 'a'

Our parser fails to handle this because the identifier starts with a “2”. But if we represent the “2” character using its escape sequence (the char “2” is x0032 in hexadecimal) the filter should get applied correctly (gets applied as “2 Table/Column1”):
•	?filter=_x0032__x0020_Table/Column1 eq 'a'

I hope this helps!

Official Sources (wasn’t sure if you needed these):
ABNF Rules: https://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt 
•	identifierLeadingCharacter  = ALPHA / "_"         ; plus Unicode characters from the categories L or Nl
XSD Schema: http://docs.oasis-open.org/odata/odata/v4.0/cs01/schemas/edm.xsd (search for name="TSimpleIdentifier")
