### ISSUE TITLE
Re: Relative filter - Last 3 months

### ISSUE THREAD

**Issue by IlanaRoth** [MicrosoftDocs/powerbi-docs#3404]
How about if I wish to filter Last 3 months but showing previous years too?
Last 3 months of this year vs same months previous years
Ilana
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @IlanaRoth . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
