### ISSUE TITLE
How do I specify the value for an x,y pair in a Power BI Scatter Plot?  

### ISSUE THREAD

**Issue by DougAtClir** [MicrosoftDocs/powerbi-docs#3445]
Under "Create a Scatter Chart", what chart type are you adding these fields to.  Also, a scatter chart should let you plot values corresponding to an x,y pair.  When I try to do this, I get error messages that make no sense at all.  

What should I use to specify the value to plot against x,y pairs?  It's obviously not Details.  There in no entry for the Value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5668e4cf-3837-c2d4-b818-14476441468b
* Version Independent ID: c95096dd-9b73-79ab-8ff2-158c5900f5a6
* Content: [Scatter, bubble, and dot plot charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-scatter)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-scatter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-scatter.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @DougAtClir, thanks for your feedback. I am passing it along to the doc owner for consideration.

**Comment by mihart** [comment]
Thanks for your comment, @DougAtClir . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
