### ISSUE TITLE
This page must updated to include more details

### ISSUE THREAD

**Issue by oussama70** [MicrosoftDocs/powerbi-docs#3463]
The screenshots are not consistent and they talk about many different cases under the same context. Confusing!!
At least one screenshot is old and confusing. If you notice, the screenshot lists P1, P2, P3, EM1, EM2, and EM3. Where is P4 and P5 in the list? The same screenshot says 8 of 17 V-Cores are used, however the count from the drop down list is:
P1: 8, P2: 16, EM1: 1, EM2: 2, EM3: 4 (P3 is greyed out, so I presume it should not be in the calculation)
The math should have been: 8 + 16 + 1 + 2 + 4 = 31 which is 8 of 31 V-Cores are used.
I couldn't make up the number 17 available V-Core.
In this article, there is nothing with regards to memory allocation. It only talks about CPU.
Can I create a capacity with single V-Core? So, if I have P1, can I create 8 capacities in 8 different regions each with a single V-Core?
Will I get 25GB divided by 8 for each of the 8 capacities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f09b043-ca4f-8d06-16b9-19f03e89b344
* Version Independent ID: 8166553d-853a-204d-b0bf-e7380d4042d6
* Content: [Configure and manage capacities in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-manage)
* Content Source: [powerbi-docs/admin/service-admin-premium-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-premium-manage.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @oussama70, thanks for your feedback. I am forwarding it along to the doc owner for consideration.

**Comment by KesemSharabi** [comment]
Hi @oussama70,

Sorry to here that you find this article confusing. Did you look at the Premium Gen2 articles. The original Power BI Premium capacities will shortly be phased out, see [Plan your transition to Power BI Premium Gen2](https://docs.microsoft.com/power-bi/admin/service-premium-transition-gen1-to-gen2). Due to this reason, we'll not be updating the Premium articles.

I suggest that you look as some of the Gen2 articles such as [What is Power BI Premium Gen2?](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-what-is) and [Premium Gen2 capacity load evaluation](https://docs.microsoft.com/power-bi/admin/service-premium-concepts), and explore new Gen2 features such as [autoscale](https://docs.microsoft.com/power-bi/admin/service-premium-auto-scale).

Hope this helps,

Kesem
