### ISSUE TITLE
Is there a JSON schema that can help me validate the data model of a PUSH dataset?

### ISSUE THREAD

**Issue by sdg002** [MicrosoftDocs/powerbi-docs#3509]
I am evaluating PUSH datasets for my customer. I can immediately see that the model specification for PUSH dataset is somewhat different from regular datasets. E.g. No support for calculated columns.

It would be very helpful to have a JSON schema from Microsoft which can help me validate if an existing SSDT model can be used for a PUSH dataset.

If Microsoft can produce a consistent schema , then I can write some simple code [like this](https://www.newtonsoft.com/json/help/html/JsonSchema.htm) to perform validatations.

Thanks,
Sau

**Comment by davidiseminger** [comment]
Thanks for your comment, @sdg002. Looks like this is product feedback or a feature request, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com
