### ISSUE TITLE
Pricing per core per hour for Power BI premium Autoscale

### ISSUE THREAD

**Issue by bertsawicki** [MicrosoftDocs/powerbi-docs#3522]
How do we determine what the cost will be for the additional core usage?  In the Azure pricing calculator, the only item is Power BI embedded.  Can we get a price per core per hour please or add it to the Azure Calculator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ebe672-8784-bd46-2637-d8cf157ff676
* Version Independent ID: 0b6f0007-66c8-c90c-bc3e-47ae4555979c
* Content: [Power BI Premium Gen2 capacity load, overload, and autoscale - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-concepts)
* Content Source: [powerbi-docs/admin/service-premium-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-concepts.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
