### ISSUE TITLE
coordinate reference system

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3531]
[EPSG:3857](https://epsg.org/crs_3857/WGS-84-Pseudo-Mercator.html) was a version of the World Geodetic System 1984 datum that Microsoft developed.  Is this the version required by Shape Map's coordinate reference system for my custom map (TopoJSON file)?  Since this version was based on a "_Pseudo_-Mercator" projection, is it compatible with Shape Map's projection setting?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mberdugo** [comment]
Thanks for your comment, @rootsmusic . 
I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @rootsmusic. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
