### ISSUE TITLE
Getting 'Could not create SSL/TLS secure channel' error when trying to run this sample application

### ISSUE THREAD

**Issue by naushadsiddiqui** [MicrosoftDocs/powerbi-docs#357]
Hello:
I am trying to use this tutorial  (https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers ) to test the Apps Own Data application that is provided as part of this tutorial. I have tried both options to run/test this application: 
a) Using the Embedding Setup Tool and then trying to run the code in Visual Studio
b) Followed the steps to complete the manual setup process (AD setup, Power BI API setup and granting of permissions etc) and then downloading of the sample application from GitHub and then updating web.config manually to run/test the application.

When I try to run the application (using either of the both above methods) then I am getting this error message below:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---

I do get the popup window in IE where it asks to select 'Embed Report'. 'Embed Dashboard' or 'Embed Tile' option but once I select/click on the 'Embed Report' button then I get the above 'SSL/TLS secure channel' related exception.

Few things I would like to ask:
- I am using a Power BI Pro trial license when testing this application. My published sample report on Power BI website was published using the trial license as well so could this error be related to any possible limitations associated with a trial Power BI Pro license?
- I am using A1 pricing tier for the dedicated Power BI Embedded capacity that I have created via my Azure portal access. Does this error has anything to do with the A1 pricing tier?

I would appreciate if someone from your team can help me figure out how to resolve this so I may complete the testing of the Apps Own Data application. Thank you!

**Comment by markingmyname** [comment]
Thanks for your comment, @naushadsiddiqui. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 

However, I can answer your 2 questions above.
1) As long as your using a Pro Licences (regardless if it is a trial or not) you should be fine.
2) The error is not related to the SKU you are using

Also, see if these articles might help:
https://community.powerbi.com/t5/Desktop/The-request-was-aborted-Could-not-create-SSL-TLS-secure-channel/td-p/122743

https://stackoverflow.com/questions/37324743/azure-api-the-request-was-aborted-could-not-create-ssl-tls-secure-channel-http

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
