### ISSUE TITLE
Clarify the requirement for MS Teams between 2 doc pages

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/powerbi-docs#3578]
On this page (https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-collaborate-microsoft-teams#requirements)
![image](https://user-images.githubusercontent.com/60522406/152514738-0e864a21-3651-40c5-bc08-b4aba7c99ddf.png)

However on this page (https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-collaborate-microsoft-teams#requirements)
![image](https://user-images.githubusercontent.com/60522406/152514817-604b5a2b-3cf1-4961-8794-96fd87ad117c.png)
My understanding is that the second one is correct, i.e. the specific mention that for a report contained in Premium capacity with a Power BI free licence. The premium advantage for free users

Can I also propose that the sentence changes from 
Your users have a Power BI Pro or Premium Per User (PPU) license, or the report is contained in a [Power BI Premium capacity (EM or P SKU)](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is) with a Power BI license.
to 
Your users have a Power BI Pro or Premium Per User (PPU) license, or the report is contained in a [Power BI Premium capacity (EM or P SKU)](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is) for users with a free Power BI license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9a0262-d1a5-2824-16f1-0f13c5ce4a64
* Version Independent ID: f73f5d7e-a45a-c8aa-18a3-ab47f641ed57
* Content: [Add the Power BI app to Microsoft Teams - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-microsoft-teams-app#requirements)
* Content Source: [powerbi-docs/collaborate-share/service-microsoft-teams-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-microsoft-teams-app.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @nathanwlee1. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @nathanwlee1 -- thanks for pointing that out! 
I updated the wording in https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-collaborate-microsoft-teams#requirements per your suggestion.
And I clarified the wording in the requirements section of https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-microsoft-teams-app#requirements. The requirements aren't the same, because in this case, you're just installing the Power BI app in Teams. You're not sharing with anyone else. So it's just about you and your license.
Thanks! Changes should be live this afternoon Fri Feb 4, Pacific time.
