### ISSUE TITLE
No Instructions for Rating Apps in AppSource

### ISSUE THREAD

**Issue by SirArtisanAzalea** [MicrosoftDocs/powerbi-docs#3594]
There's no information in this document on rating an app. I've attempted to rate an app via AppSource and am told to download and use the app first (I have). I cannot rate through the Service either. How do you rate an app?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e83a4fd-44f3-4fe6-9237-3cc56f3965cd
* Version Independent ID: 2fbc77d4-2f45-0e00-585a-de9f4f561e64
* Content: [Install and use apps with dashboards and reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-app-view)
* Content Source: [powerbi-docs/consumer/end-user-app-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-app-view.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @SirArtisanAzalea.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Thanks for your comment, @SirArtisanAzalea . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
