### ISSUE TITLE
May I know how long it will take effect after the access had been configured? 

### ISSUE THREAD

**Issue by tmhui94** [MicrosoftDocs/powerbi-docs#3599]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db2f3b5-305f-2803-012a-04154b58acb2
* Version Independent ID: 3bf41b0d-cd66-9782-1d2c-d1d79319048c
* Content: [Give users access to the new workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-give-access-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-give-access-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-give-access-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Hello there @tmhui94 -- This looks like a support request rather than documentation feedback, plus you didn't reference the article you're asking about, which makes it difficult to determine what you're asking. 

You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
