### ISSUE TITLE
PowerBI Service Tag insufficient for network isolation

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#3600]
PowerBI service tag does not include all of the endpoints necessary for an Azure Firewall rule to allow access to all necessary endpoints to render the Power BI portal.   This should include all the service tags necessary.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security white paper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by davidiseminger** [comment]
Thanks for your comment, @GitWesDone . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by RylandDeGregory** [comment]
The `PowerBI` Service tag referenced within this article, and also within the [downloadable JSON object of Service Tags](https://www.microsoft.com/en-us/download/details.aspx?id=56519), cannot be added to an Azure Firewall rule...
![image](https://user-images.githubusercontent.com/18073815/154334743-2be96f87-8293-4e87-ae3a-39492ec076f9.png)

Is this intentional?

**Comment by paulinbar** [comment]
HI @GitWesDone and @RylandDeGregory, I have forwarded your comments along to the product team for consideration. Thanks for your feedback!
