### ISSUE TITLE
Not working site: Dev.PowerBI.com/Apps

### ISSUE THREAD

**Issue by tirnovar** [MicrosoftDocs/powerbi-docs#3606]
Link: https://dev.powerbi.com/apps will take you to the right page, but you cannot sing here because once you click on "sing in," you will be redirected to "https://powerbi.microsoft.com/en-gb/developers/" not signed it and to redirected back. If I want to create an "app" on some page, I have to go through this page https://app.powerbi.com/embedsetup.

**Comment by mihart** [comment]
Thanks for your comment, @tirnovar . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
