### ISSUE TITLE
The page of Japanese article is changed in French

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3627]
Hi Authors,

The page of Japanese article has been changed in French.

![image](https://user-images.githubusercontent.com/73410575/155040604-63f06e72-407d-4667-b5a1-6029da7e7a3f.png)

Please kindly check and modifiy it.
Thanks,

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4ce540da-a491-f6c2-d33a-5293f09d2182
* Version Independent ID: dbdbaf6a-5c69-f33c-dc57-3a7b707ba5eb
* Content: [FAQ sur la haute disponibilité, le basculement et la reprise d’activité avec Power BI - Power BI](https://docs.microsoft.com/ja-jp/power-bi/admin/service-admin-failover)
* Content Source: [powerbi-docs/admin/service-admin-failover.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-failover.yml)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by mihart** [comment]
Thanks for your comment, @Hyamyam . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)

**Comment by kfollis** [comment]
@Hyamyam - your experience was very odd, so I checked with our translation team. This was a bug and has since been fixed. Thanks!
