### ISSUE TITLE
A link to the video on YouTube seems to be wrong

### ISSUE THREAD

**Issue by ankerok-dingdong** [MicrosoftDocs/powerbi-docs#3630]
[Enter feedback here]

A link to the video on YouTube seems to be wrong on several BI manuals pages I've encountered recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b2fae9-3356-f90c-8b3c-647aa2ad5f75
* Version Independent ID: 5ee251f0-8e8b-47eb-937c-356e15c341ba
* Content: [Set data alerts in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-set-data-alerts)
* Content Source: [powerbi-docs/create-reports/service-set-data-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-set-data-alerts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mberdugo** [comment]
Thanks for your comment, @ankerok-dingdong . 
I've assigned this issue to the doc author for review.

**Comment by paulinbar** [comment]
Hi @ankerok-dingdong, thanks for reaching out to us. The video link on this page seems to be working ok for me. Can you try again, and if it doesn't work, can you copy here the URL that you have for that video?
Regarding bad links on other doc pages, can you please name the specific pages so that we can check them out? Thanks. 
In the meantime I am closing this issue, but if you still have problems with the video, or have links to specific doc pages that have bad links, please feel free to reopen the issue. Thanks!
