### ISSUE TITLE
Inaccurate licensing info.

### ISSUE THREAD

**Issue by kpraeger** [MicrosoftDocs/powerbi-docs#3687]
In the Prerequisites section of this article is says "You need a Power BI Pro or Premium Per User (PPU) license to publish a report to the service.". I believe that is not accurate, because don't you need a Power BI Premium (per user or per capacity) license to publish paginated reports? I don't believe paginated reports work at all with Power BI Pro.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720989e-e6c4-2377-e0c0-8c80d5691f46
* Version Independent ID: 3c6392e8-0f91-1c9c-2c21-15291d46bfd0
* Content: [What are paginated reports in Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
@kpraeger - thank you for the feedback! I have removed that bullet point from the paginated reports articles. The prerequisite of having a workspace in Premium capacity actually covers any licensing requirements so that line item was a bit redundant and added more confusion than clarification. I'll close this issue now.
