### ISSUE TITLE
Global date filter

### ISSUE THREAD

**Issue by ZdenekSoldan** [MicrosoftDocs/powerbi-docs#3693]
In the Capacity Metrics App there is no global date filter. Filtering in each visual is nice but global date slicer synced for all three pages would be much more useful.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ZdenekSoldan. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ZdenekSoldan.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
