### ISSUE TITLE
Refresh by Artifact: top N 

### ISSUE THREAD

**Issue by ZdenekSoldan** [MicrosoftDocs/powerbi-docs#3694]
The visual Refresh by Artifact is very useful but for bigger tenant it doesn't show relevant output. When there is more artifacts than the visual can show it shows first N artifact in alphabetical order which doesn't make any sense. Changing the visual to show top N (20 or 30) artifacts by the value would be much more better.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ZdenekSoldan. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ZdenekSoldan.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
