### ISSUE TITLE
Tracking Composite Models

### ISSUE THREAD

**Issue by Melsize** [MicrosoftDocs/powerbi-docs#3754]
Is there a way to track which datasets are using a composite model and the lineage of those?  This will be most useful when changes need to be made.  At time, we are using composite models with additional data, which creates a new dataset, making the lineage difficult to trace.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Melsize. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Melsize,

As far as I'm aware, there isn't a way to track the lineage of composite models (see [Considerations and limitations](https://docs.microsoft.com/power-bi/collaborate-share/service-data-lineage#considerations-and-limitations)).

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community](https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

Hope this helps,

Kesem
