### ISSUE TITLE
Missing known issue

### ISSUE THREAD

**Issue by bernatagulloesbrina** [MicrosoftDocs/powerbi-docs#3761]
Conditional formatting for datalabel text color is still not being evaluated for each data point
see this tweet for reference 
https://twitter.com/AgulloBernat/status/1463993479579713543

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Version Independent ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Content: [Power BI known issues - Power BI](https://docs.microsoft.com/en-us/power-bi/troubleshoot/known-issues/power-bi-known-issues)
* Content Source: [powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bernatagulloesbrina. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @bernatagulloesbrina  This looks like a support request or product question rather than documentation feedback. The known issues on this page are sourced from the Support team, so you'll want to contact them and not the Documentation team.  You may be able to contact Support, refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options. (Also, I've forwarded your idea on to the Support team too ).  Thank you.

**Comment by bernatagulloesbrina** [comment]
If they have not mentioned it, I understand then that the product team sees no issue in how the conditional formatting of datalabels is currently implemented. 
If the goal is to have a complete list of issues, I'm not sure that only listening to the product team is the best approach tbh.
