### ISSUE TITLE
There is an error in the JSON (Properties within each card)

### ISSUE THREAD

**Issue by phil-lgr** [MicrosoftDocs/powerbi-docs#3764]
In https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#properties-within-each-card

the JSON is not valid, there is a missing closing bracket after `legend`

```
       "legend": {
```

WE NEED this whole JSON and the others to be published as a schema and possibly TypeScript definitions files, thanks!

Please follow up on my idea: https://ideas.powerbi.com/ideas/idea/?ideaid=cead8d13-67c2-ec11-bea1-501ac50a5d5c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#report-theme-json-file-format)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @phil-lgr. This issue has been assigned to the doc author for review.

**Comment by phil-lgr** [comment]
@maggiesMSFT @KesemSharabi if you could shine a light on the issue with having no schema or type definitions for the Theme JSON I would really appreciate

I started writing my own types around the raw JSON, obviously we should not have to do this to have basic autocomplete

![image](https://user-images.githubusercontent.com/9644867/164785285-58859479-52df-4065-a85f-85b114efde06.png)

**Comment by KesemSharabi** [comment]
Hi @phil-lgr,

Thank you for your comment and for getting involved!

You're right about the JSON example, something doesn't look right after 'legend'. I have a feeling that perhaps 'show' needs a square bracket instead of a curly one. I'll check this with the dev team and fix the document accordingly.

As for your idea, this is really for the product team to decide upon. I'm glad you already engaged with them by posting your idea, and hopefully they'll pick up on that.

Thanks,

Kesem

**Comment by phil-lgr** [comment]
@KesemSharabi thank you, if you have any other insight, please let us know :)

**Comment by maggiesMSFT** [comment]
Hi, @phil-lgr --thanks for your comment! Turns out it wasn't a missing bracket; the indentation was wrong. We've fixed that; update will be live this afternoon. Thanks!
I'm going to close this issue. Thanks for creating your idea, https://ideas.powerbi.com/ideas/idea/?ideaid=cead8d13-67c2-ec11-bea1-501ac50a5d5c. That's the right place for it!
