### ISSUE TITLE
Section regarding ways to format differences between addresses that are mapped and those that aren't

### ISSUE THREAD

**Issue by jeremiah1119** [MicrosoftDocs/powerbi-docs#3799]
I'm not sure if it's possible, but it might be nice to show a way to handle when the address search simply doesn't work. For example working with dirty data it could be nice to conditionally format a table based on whether or not Bing Maps was able to find an address and plot it on the map. Quick at-a-glance way to see those which have issues if you do not have detailed data like longitude and latitude
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Tips and Tricks for maps (including Bing Maps integration) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-map-tips-and-tricks)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jeremiah1119. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @jeremiah1119 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
