### ISSUE TITLE
Mention to enable the Power BI Tenant Setting: 'Azure AD Single Sign-On (SSO) for Gateway'

### ISSUE THREAD

**Issue by RuiRomano** [MicrosoftDocs/powerbi-docs#3800]
For Azure AD SSO to work with on-prem gateway its necessary to enable the Power BI Tenant Setting 'Azure AD Single Sign-On (SSO) for Gateway' on the Admin Portal. For example for Azure Data Explorer the checkbox for SSO enablement dont appear if this option is not enabled.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb02e4da-ce10-4450-cb39-d6891fa506ec
* Version Independent ID: 53728ae6-0194-8ad1-ef7f-d1f602a2e7c4
* Content: [Overview of single sign-on (SSO) for on-premises data gateways - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-overview)
* Content Source: [powerbi-docs/connect-data/service-gateway-sso-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sso-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RuiRomano. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @RuiRomano, well, at long last I have input from the content expert and we will be updating the page soon. He didn't think we needed to put the item about the setting on the page, but he did make other changes to try to make things more clear. The updates will come in the next few days. Thanks again for reaching out and apologies for the VERY overdue reply. 
I am going to close this issue here now.
