### ISSUE TITLE
This New Feature is Scary! What if we use service account and some one other than PBI Admin swaps it with personal auth? 

### ISSUE THREAD

**Issue by karthikk24** [MicrosoftDocs/powerbi-docs#3801]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92e0c038-1195-d758-ccf4-903b689139ca
* Version Independent ID: 181904c0-1ec5-0a1d-4cbf-a5a639bbdfeb
* Content: [Add or remove a gateway data source - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources)
* Content Source: [powerbi-docs/connect-data/service-gateway-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by karthikk24** [comment]
The New Feature of moving Gateway Datasources from Admin Portal to general will lead to lots of confusion and problems , https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources - updated 05/06.
Why was this removed from Admin Portal?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @karthikk24. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @karthikk24.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
