### ISSUE TITLE
Mail-enabled security group as sole Admin in a workspace?

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#3817]
I have a V2 workspace in premium capacity that has only 1 mail-enabled security group listed as the admin; when I do this, the workspace become orphaned. Is this expected behavior? Must I list at least one "individual" user as a workspace admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [The new workspace experience in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nicheplayer. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @nicheplayer -- Good question! I'm checking and will get back to you.

**Comment by paulinbar** [comment]
Hi @nicheplayer, we're still here. Did you ever get an answer to your question. I am inquiring as well.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
