### ISSUE TITLE
Supported data sources

### ISSUE THREAD

**Issue by albegouws** [MicrosoftDocs/powerbi-docs#3821]
Hi 

Can you please add supported data sources on this page?  It doesn't look like the feature works with Analysis Services as a data source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Version Independent ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Content: [Let report readers use field parameters to change visuals (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-field-parameters)
* Content Source: [powerbi-docs/create-reports/power-bi-field-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-field-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @albegouws. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @albegouws.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
