### ISSUE TITLE
Any Update?

### ISSUE THREAD

**Issue by rhalabi** [MicrosoftDocs/powerbi-docs#3833]
Any update when the Try It button will be restored? It's been almost a month.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f336bd62-6922-b6ce-f839-a164ad7134ad
* Version Independent ID: f336bd62-6922-b6ce-f839-a164ad7134ad
* Content: [Known issue - Try it button missing on REST API pages - Power BI](https://docs.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-169-try-it-button-missing)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-169-try-it-button-missing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-169-try-it-button-missing.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @rhalabi. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.) I know that the engineering team works to close known issues as quickly as possible but I heard that this one may take at least another month.
