### ISSUE TITLE
Where is This Content Pack

### ISSUE THREAD

**Issue by thanksforthepen** [MicrosoftDocs/powerbi-docs#385]
Hi there, 

This content pack is perfect! Exactly what I'm looking for. Could you update with a new link or new name in the App Store please? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d381e7a-6f83-a78f-3f7d-9841589f13fc
* Version Independent ID: 10415f44-f38f-3150-b581-b4a479ece2c6
* Content: [SQL Database Auditing content pack - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-sql-database-auditing)
* Content Source: [powerbi-docs/service-connect-to-azure-sql-database-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-sql-database-auditing.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by salexu** [comment]
This content pack has been deprecated since it relies on Table auditing feature, which has also been deprecated and replaced by Blob auditing. Please see this page for Power BI template that works with Blob auditing:
https://blogs.msdn.microsoft.com/azuresqldbsupport/2017/05/26/sql-azure-blob-auditing-basic-power-bi-dashboard/

**Comment by maggiesMSFT** [comment]
Thanks, @salexu, and thanks @thanksforthepen for asking!
