### ISSUE TITLE
Q&A for Power BI

### ISSUE THREAD

**Issue by alexisworking404** [MicrosoftDocs/powerbi-docs#3853]
Can you use the Q&A for Power BI in a custom website? or can you only use it in Power BI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2521838-3589-eb9e-b0b7-ed49fa6657dc
* Version Independent ID: 069373ae-dfbe-823a-6423-e1a81ebe3f72
* Content: [Q&A tutorial for Power BI business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-q-and-a-tutorial)
* Content Source: [powerbi-docs/consumer/end-user-q-and-a-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-q-and-a-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alexisworking404. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @alexisworking404 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
