### ISSUE TITLE
Field Parameter Values as a Slicer

### ISSUE THREAD

**Issue by vincent-roberto** [MicrosoftDocs/powerbi-docs#3944]
[Enter feedback here]
I see in the notes that "From the context menu, you can also choose if the field parameter shows the values or the display names of the selected field(s) for all non-slicer visuals”. It would be very useful in a future version in a specific use-case I have to be able to show the field parameter values in a slicer as well. It would solve for my current use-case where I think the workaround would be to show the field parameter values in a table and allow the user multi-selections using control+click to filter the entire page. It's clunky though and would be much better off as a slicer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Version Independent ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Content: [Let report readers use field parameters to change visuals (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-field-parameters)
* Content Source: [powerbi-docs/create-reports/power-bi-field-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-field-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @vincent-roberto.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
