### ISSUE TITLE
No admin-consent permissions : why ?

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3989]
Hi doc team,

We are confused about the statements regarding admin role and admin-consent permissions (cf. below).

Can you elaborate ? What happens if the app has been granted those permissions ?

Does it mean that we do not need to add permissions to the registered app if the settings "Allow service principals to use read-only admin APIs" is enabled in the admin portal for this app ? As described in this [article](https://docs.microsoft.com/en-us/power-bi/developer/embedded/register-app?tabs=customers%2CAzure)

Thanks for your help and the wonderful work here!

Nicolas

![image](https://user-images.githubusercontent.com/35227452/182686427-15a72c06-59f8-4140-8f15-cbaa0c572241.png)

![image](https://user-images.githubusercontent.com/35227452/182686450-024d4897-2aad-4c6b-a5b2-4d2fc2edd079.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a83362-3a66-ba07-ebe5-b83a49171917
* Version Independent ID: 58a83362-3a66-ba07-ebe5-b83a49171917
* Content: [Enable service principal authentication for read-only admin APIs - Power BI](https://docs.microsoft.com/en-gb/power-bi/enterprise/read-only-apis-service-principal-authentication)
* Content Source: [powerbi-docs/enterprise/read-only-apis-service-principal-authentication.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/read-only-apis-service-principal-authentication.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nstraw. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @nstraw, sorry for getting this only now. I will need to check with the product team about this. I'll report back as soon as I hear, and if necessary will update the documentation.
Thanks for reaching out. As I said, I'll get back in touch as soon as I have an answer.

**Comment by paulinbar** [comment]
Hi @nstraw, sorry for the LONG delay in getting back to you. As I understand it, for the 4 APIs that are called the "scanner APIs" ( https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-metadata-scanning ) if an app is going to run under service principal authentication rather than under standard delegated token authentication, it must not have any admin-consent required permissions for Power BI placed on in in the Azure portal. This document ( https://learn.microsoft.com/en-us/power-bi/enterprise/read-only-apis-service-principal-authentication ) has been changed a bit to hopefully make this more clear. If the app runs under a service principal, but has admin consent required permissions for Power BI, then if it calls one of those scanner APIs, apparently there is a failure. I understand that this is not true of other Admin read-only APIs - in those cases the admin consent required permissions are just ignored. In any event, please take another look at the document, as well as the API documentation, and let me know if you still have questions. All the Admin read-only APIs got an updated limitations section, but this has to be rolled back, as the limitation apparently only applies to those scanner APIs.
