### ISSUE TITLE
Is Azure Cost Management deprecated?

### ISSUE THREAD

**Issue by francesco1119** [MicrosoftDocs/powerbi-docs#4004]
Is [Azure Cost Management for Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management) still maintained? 

The same goes for [Cost Management Power BI App for Enterprise Agreements](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management), it looks like it's deprecated. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @francesco1119. This issue has been assigned to the doc author for review.

**Comment by francesco1119** [comment]
Hello @davidiseminger , let me know what else do you need to debug this issue. 
We have been trying to connect to both templates with maximum privilege and several Azure accounts, nothing works. 

If you search into https://community.powerbi.com/ you will see that there are many customers with the same issue.

Thank you

**Comment by davidiseminger** [comment]
Sorry for the trouble you've experienced. These connectors and their articles are updated as changes are made. We're also in the process of moving documentation for some connectors to Power Query docs, so you might find more info here: https://learn.microsoft.com/en-us/power-query/connectors/azure-cost-management


You might find a solution in the Power BI Community (since you posted this), found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
