### ISSUE TITLE
Not Current Documentation

### ISSUE THREAD

**Issue by Odeta-Jankaitiene** [MicrosoftDocs/powerbi-docs#4102]
Hello,

I can see in the Power BI tenant settings that this setting has been changed but there is no current documentation. Thus, I'm unsure what exactly has been changed. Please, update it.

Kind Regards,
Odeta Jankaitienė

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 236be35d-5c21-cd23-12ca-2a9b420545d3
* Version Independent ID: 236be35d-5c21-cd23-12ca-2a9b420545d3
* Content: [Share data with your Microsoft 365 services admin settings - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-share-data-microsoft-365-services)
* Content Source: [powerbi-docs/admin/service-admin-portal-share-data-microsoft-365-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-share-data-microsoft-365-services.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dragons-data. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Odeta-Jankaitiene, thanks for reaching out, and apologies for such a late reply. I believe that since you wrote, the article has been updated with links to relevant documentation. Please have a look at the article again and see whether it provides links to the info you need. In the meantime I am closing this issue, but please feel free to reopen if necessary. Thanks!
