### ISSUE TITLE
Synapse

### ISSUE THREAD

**Issue by CloudCrusader** [MicrosoftDocs/powerbi-docs#4119]
would this also apply for Synapse workloads?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01cad641-4e21-029b-3413-9e8b1de5ddbe
* Version Independent ID: 01cad641-4e21-029b-3413-9e8b1de5ddbe
* Content: [Using service tags with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-service-tags)
* Content Source: [powerbi-docs/enterprise/service-premium-service-tags.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-service-tags.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CloudCrusader. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @CloudCrusader.

This looks like product feedback or a product question, rather than documentation feedback.

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

There's also more information about service tags in [Virtual network service tags](https://learn.microsoft.com/azure/virtual-network/service-tags-overview).
