### ISSUE TITLE
"Chat in Teams" function doesn't work when embedded Power BI report in Microsoft Teams group chat

### ISSUE THREAD

**Issue by banhngocha** [MicrosoftDocs/powerbi-docs#4254]
Hi,

I have added a Tab of Power BI report in a Microsoft Teams group chat. When I use the "Chat in Teams" function, there's a "Share" pop up displaying in a tiny frame that doesn't show all of buttons to use. I suppose this is an UI error. Please fix this.

Thank you,

Ms. Ha Banh

![Chat in Teams](https://user-images.githubusercontent.com/121149289/208828064-9503195b-86d9-4aef-97d5-6e0ea690adc3.png)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @banhngocha. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @banhngocha.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
