### ISSUE TITLE
Option to Disable Insights

### ISSUE THREAD

**Issue by Swappy** [MicrosoftDocs/powerbi-docs#428]
We do not really want to expose this option to end users. Please add the option to disable.
Please share if the option exists alread

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216c87b1-d196-a091-048c-dc55b0649338
* Version Independent ID: f8bb7489-d0bd-58f0-9eb3-6471d4d57eab
* Content: [Use insights in Power BI Desktop to explain increases and decreases in visuals (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-insights)
* Content Source: [powerbi-docs/desktop-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-insights.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Swappy . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community to disable this option to users, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by davidiseminger** [comment]
Thanks for your comment, @Swappy . Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
