### ISSUE TITLE
Additional data would be helpful

### ISSUE THREAD

**Issue by James-Ambrose** [MicrosoftDocs/powerbi-docs#4287]
Adding the pbix is great f you could supply the excel file that's is associated would be great. I am trying something similar but need to know how to have the data to be pulled across.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79d518e0-d56d-f49b-0f32-1aa4e9bc97d0
* Version Independent ID: f05fd185-d2e9-38f0-5f5f-fe896d408a15
* Content: [Line charts in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-line-chart?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-line-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-line-chart.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @James-Ambrose. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @James-Ambrose ,
Thank you for your suggestion. We're currently updating all of the documentation in the Visuals section of our docset. I know that the instructions on this article are out-of-date, and we're working on changing that. I'm going to close this Git Issue since I know the work is being done. We hope to have all of the articles updated by April.  Thank you!
