### ISSUE TITLE
Decomposition tree - Improvment Request

### ISSUE THREAD

**Issue by HaydnMilton** [MicrosoftDocs/powerbi-docs#4291]
Hi All,
Please can I ask if it would be possible to make the Data Bar Color have the option to apply colour based upon an attribute rule. For eample a Project has meta data relationg to its, approval status, lifecyce or current status (RAG). It would be great to have the option to color code the 'Data Bars' based upon this meta data, thanks in advance for considering this,

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HaydnMilton. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @HaydnMilton.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
