### ISSUE TITLE
Not clear how to create and install the certificate

### ISSUE THREAD

**Issue by caiofcm** [MicrosoftDocs/powerbi-docs#4293]
Hello, thank you for the tutorial.

The tutorial says: "You'll also need to create and install a certificate" but it is not clear how to create this certificate.

I am having issues associated with certificates when running `pbiviz publish`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/environment-setup)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @caiofcm. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @caiofcm. The certificate should be installed automatically. I recently updated this document and removed the instructions for installing a certificate because they should no longer be necessary. If you installed the latest version of pbiviz you shouldn't need to install the certificate separately, but if you need to, there are instructions [here](https://learn.microsoft.com/power-bi/developer/visuals/create-ssl-certificate).
What kind of errors are you getting when running `pbiviz publish`?
