### ISSUE TITLE
How to customize selected values?

### ISSUE THREAD

**Issue by MikhailTryakhov** [MicrosoftDocs/powerbi-docs#430]
Hello,
have problems working, for example, with issues. What's the best way to view issues filtered by label or assignee? 
There is only a chance to view creators of issues but that's not super helpful info.
Maybe any way to export issues and any info I specified above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-github)
* Content Source: [powerbi-docs/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-github.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mihart** [comment]
Hi @MikhailTryakhov,
Thank you for your feedback. I've assigned the Issue to the author, who will get back to you soon.
Take care,
Michele

**Comment by milo73** [comment]
Hi,
Looks like an awesome tool to use. Just one thing which is not clear to me. How can this connector be used to connect to Github Enterprise?

Regards,
Milo

**Comment by maggiesMSFT** [comment]
Hi, @MikhailTryakhov and @milo73 -- Thanks for your comments! They look like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.  Thanks!
