### ISSUE TITLE
The 'Microsoft Graph Security (beta)' is no listed under 'Online Services' with a brand new install of Power BI Desktop

### ISSUE THREAD

**Issue by RichNZ404** [MicrosoftDocs/powerbi-docs#4350]
This documentation is out of date. The 'Microsoft Graph Security (beta)' is no listed under 'Online Services' with a brand new install of Power BI Desktop
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-graph-security)
* Content Source: [powerbi-docs/connect-data/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RichNZ404. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @RichNZ404, what version of Desktop are you using? I just downloaded Version: 2.114.625.0 64-bit (February 2023), and did Get data, and I don't see any mention of Microsoft Graph. Can you please elaborate a bit on how you saw it?

**Comment by paulinbar** [comment]
Hi @RichNZ404, did you mean "now listed" or "not listed"? If you meant "not listed", did you see the note at the top of the article that says that the connector has been deprecated?

**Comment by RichNZ404** [comment]
I meant "not listed". Please update the visual component to your documentation if this has been deprecated. This is a poor experience for someone looking to find documentation and then give feedback on the lacking documentation. 

In the below, the link takes me to a 404 page. How am I do find was this has been replaced with or alternative solution?

"Connect to the Microsoft Graph Security API in Power BI Desktop
[!NOTE] The Microsoft Graph Security connector is deprecated as of May 2021 and has been removed from the "Get Data" experience in Power BI Desktop. We recommend that you replace existing connections that use this connector, and refrain from using this connector for new connections. For more information, see the [Microsoft Graph Security documentation](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/power-query/connectors/microsoftgraphsecurity)."

**Comment by paulinbar** [comment]
Hi @RichNZ404,
I think you get the 404 if you click that link in these comments here in Github - that is because the links are relative and somehow part of the path get replaced with something that is not really the path to the article, and then you get the 404. The real link to that For more information, see the Microsoft Graph Security documentation link is this: https://learn.microsoft.com/power-query/connectors/microsoft-graph-security, but I'm afraid that is not going to help you much because at that page it also just says that the connector has been deprecated and you should use something else, but it provides no guidance or recommendations about what actually to do. I myself have inquired about this and noted that the current explanation there is inadequate, but have never received a response from that team. I will try again to see if I can't get them to provide more helpful information, or at least be clear that they have no recommended course of action.

**Comment by RichNZ404** [comment]
No, it was the link on the page.
