### ISSUE TITLE
Tenant Settings

### ISSUE THREAD

**Issue by abates100** [MicrosoftDocs/powerbi-docs#4354]
Would be VERY helpful if the Tenant settings pages also noted the switchName property so the correct setting label in the UI could be mapped.  We are attempting to track tenant changes and it's very problematic to do so in an automated fashion without this information to match the activity log output.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 700f1531-6391-647b-788d-56d176c930e7
* Version Independent ID: 700f1531-6391-647b-788d-56d176c930e7
* Content: [About tenant settings - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-about-tenant-settings)
* Content Source: [powerbi-docs/admin/service-admin-portal-about-tenant-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-about-tenant-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @abates100. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @abates100, interesting suggestion. You've reached the docs team, and right now we are not in a position to do anything about that since we don't get that information, but I am going to pass this info on to others in the organization who might be able to take it into consideration. In the meantime, I suggest you submit this as feedback or a feature idea by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by bringing it up in the [Power BI Community](https://community.powerbi.com/). 
Thanks for taking the time to make the suggestion!
