### ISSUE TITLE
Details about licensing required for Power BI Secure Embed feature are contradictory

### ISSUE THREAD

**Issue by pbdarkknight** [MicrosoftDocs/powerbi-docs#4356]
In 'How to embed Power BI reports into portals' section's point no. 5, it is mentioned that the content MUST be hosted in Premium capacity for Secure Embed to work.
![2023-02-19 16_12_02-Window](https://user-images.githubusercontent.com/125767925/219943300-b0e2c4d5-45e7-4315-ab57-7d235e6445e4.png)

However, in the Licensing section, it is stated that either Pro/PPU license is required OR the workspace needs to be in Premium capacity.
![2023-02-19 16_12_40-Window](https://user-images.githubusercontent.com/125767925/219943309-a009df62-c6f2-4d54-95ae-6261dbc21b2b.png)
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7197c1f9-ff31-f86c-faf3-ab89e4ab9573
* Version Independent ID: f30cdf40-43c4-e0c3-4941-a02f5bb28fc1
* Content: [Embed a report in a secure portal or website - Power BI](https://learn.microsoft.com/en-gb/power-bi/collaborate-share/service-embed-secure)
* Content Source: [powerbi-docs/collaborate-share/service-embed-secure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-embed-secure.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pbdarkknight. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
