### ISSUE TITLE
February version is having problems with power automate

### ISSUE THREAD

**Issue by ACSOJavierRod** [MicrosoftDocs/powerbi-docs#4362]
Hi Power BI team, this February version is having problems with power automate in the desktop version. 

When you go to edit a power automate process the visualisation gets white and it doesn't show any option 

Have you realised that?

Thanks.

Javier
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 540c095a-44b8-bd64-6bb2-81fdefbcb591
* Version Independent ID: 4a74c2a6-2b28-5c73-9243-1ad5e08d6dd2
* Content: [What's new in the latest Power BI update - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ACSOJavierRod. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. The most recent version of Power BI Desktop is always the best to use. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
