### ISSUE TITLE
No TRIAL available

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/powerbi-docs#4365]
Please update the text to no longer state there is a TRIAL. There is no TRIAL for GOV available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff5ba960-512e-7a76-10c9-ac6a33bd6022
* Version Independent ID: 44d12651-bb26-9d9d-42c4-66b3c42e8465
* Content: [Sign up for Power BI for United States government customers - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-govus-signup#add-power-bi-to-a-microsoft-365-government-plan)
* Content Source: [powerbi-docs/enterprise/service-govus-signup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-govus-signup.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devman2k. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi Chris, Mihir and Jonathan,

Can one of you please confirm that the customer in GitHub issue 4365<https://github.com/MicrosoftDocs/powerbi-docs/issues/4365> is correct? - there's no trial in a Microsoft 365 Government plan.

Can I get an environment/screenshot so that I can see this? I want to fix Sign up for a new Microsoft 365 Government plan<https://learn.microsoft.com/en-us/power-bi/enterprise/service-govus-signup#sign-up-for-a-new-microsoft-365-government-plan> with the exact wording.


Thanks,



Kesem

________________________________
From: devman2k ***@***.***>
Sent: Thursday, February 23, 2023 01:43
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: Kesem Sharabi ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/powerbi-docs] No TRIAL available (Issue #4365)


Please update the text to no longer state there is a TRIAL. There is no TRIAL for GOV available.

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: ff5ba960-512e-7a76-10c9-ac6a33bd6022
  *   Version Independent ID: 44d12651-bb26-9d9d-42c4-66b3c42e8465
  *   Content: Sign up for Power BI for United States government customers - Power BI<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpower-bi%2Fenterprise%2Fservice-govus-signup%23add-power-bi-to-a-microsoft-365-government-plan&data=05%7C01%7CKesem.Sharabi%40microsoft.com%7Cd954939877b44969d9fe08db152ea2b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638127062293079144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MEaoOVDqpvj66V4TPx8bP4CtdKj7z1E5xyUXTYO4ZMA%3D&reserved=0>
  *   Content Source: powerbi-docs/enterprise/service-govus-signup.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerbi-docs%2Fblob%2Fmain%2Fpowerbi-docs%2Fenterprise%2Fservice-govus-signup.md&data=05%7C01%7CKesem.Sharabi%40microsoft.com%7Cd954939877b44969d9fe08db152ea2b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638127062293079144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=htJeKs8Gl0d3E69hDFU9R6Yxk9aWB4XKAgoLL%2B%2FVgvI%3D&reserved=0>
  *   Service: powerbi
  *   Sub-service: powerbi-admin
  *   GitHub Login: @KesemSharabi<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKesemSharabi&data=05%7C01%7CKesem.Sharabi%40microsoft.com%7Cd954939877b44969d9fe08db152ea2b7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638127062293079144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ztD9MgKKOmtZo74nBGYluGg2FFcF1BRJXggWI%2BuVyC4%3D&reserved=0>
  *   Microsoft Alias: kesharab

**Comment by KesemSharabi** [comment]
Hi @devman2k,

Thanks for pointing this out. I removed the trial information from the document, and you'll be able to see the change shortly.

Thanks again for getting involved,

Kesem
