### ISSUE TITLE
Information on license required to use personalized visuals required 

### ISSUE THREAD

**Issue by edik7257** [MicrosoftDocs/powerbi-docs#4410]
Information on license required to use personalized visuals required 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7c4b038-e61f-691f-f155-333e271e611c
* Version Independent ID: 3e653013-5cf2-269f-aa6e-d617d7607de6
* Content: [Feature availability for users with Free licenses in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-features)
* Content Source: [powerbi-docs/consumer/end-user-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @haydnr
* Microsoft Alias: **haydnr**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @edik7257. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
