### ISSUE TITLE
Prerequisites section referencing designer and automl links to the code example of Azure Machine Learning

### ISSUE THREAD

**Issue by pgr-lopes** [MicrosoftDocs/powerbi-docs#4411]
Hi everyone, good day.

In this page, the prerequisites section mentions 3 ways to achieve this by creating the machine learning model using: code, designer and automl.
The links to both designer and automl take you to the code development section instead of an actual designer/automl example.

I believe either these 2 options need to be removed from the link or they should be linked to the correct articles explaining how to develop models using designer/automl.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfdd02ee-f034-f9c3-7d52-199944ac23bb
* Version Independent ID: 4336a0d9-94d1-a5f7-f0d1-e5d260018b68
* Content: [Tutorial: Consume an Azure Machine Learning model in Power BI - Azure Machine Learning](https://learn.microsoft.com/en-us/power-bi/connect-data/service-aml-integrate)
* Content Source: [powerbi-docs/connect-data/service-aml-integrate.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-aml-integrate.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @samuel100
* Microsoft Alias: **samkemp**

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
