### ISSUE TITLE
Known Issue appears to still be active

### ISSUE THREAD

**Issue by mmBPCS** [MicrosoftDocs/powerbi-docs#4416]
[Enter feedback here]

Encountered the initial issue described here on 3/17/23 with a report that what previously available, removed from a workspace, and re-uploaded to the same space.

Manual regrants of access described in the workaround are not consistently successful, and some share emails are not being received. In most cases, granting and then removing build permissions was what appeared to resolve access concerns. RLS for the report now also appears non-functional. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bead40a7-0f26-dc4b-0e4f-9427dd1296c2
* Version Independent ID: bead40a7-0f26-dc4b-0e4f-9427dd1296c2
* Content: [Known issue - Accessing Power BI app report is denied due to no dataset access - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-284-accessing-app-report-denied-due-to-no-dataset-access)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-284-accessing-app-report-denied-due-to-no-dataset-access.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-284-accessing-app-report-denied-due-to-no-dataset-access.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mmBPCS. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
