### ISSUE TITLE
Lack of UK Support

### ISSUE THREAD

**Issue by AdrianJBW** [MicrosoftDocs/powerbi-docs#443]
Why does every supported Country have a level of regional support for map areas, other than the UK which is split only by country. A county and / or postcode is a must for Power BI to be competitive in this space with rivals.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape Maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @AdrianJBW -- Thanks for contacting us! This looks like product feedback,  rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
