### ISSUE TITLE
Option A Step 9 Clarification

### ISSUE THREAD

**Issue by acLuebke** [MicrosoftDocs/powerbi-docs#4440]
[Enter feedback here]
The doc directs us to select "Use any authentication protocol". In this scenario does this technically mean only "any Kerberos authentication protocol" ? Or could other protocols be leveraged here? Is there a potential security risk/concern?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8d4509b-ab31-a917-16a2-8ed7ce834c41
* Version Independent ID: 31f21190-cd0d-f369-fc4a-48ca7ac1ccb0
* Content: [Configure Kerberos-based SSO from Power BI service to on-premises data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-kerberos#step-4-configure-kerberos-constrained-delegation)
* Content Source: [powerbi-docs/connect-data/service-gateway-sso-kerberos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sso-kerberos.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
HI @ms-kgorgi, can you comment on this one?

**Comment by ms-kgorgi** [comment]
Answering the questions _italics_: 

In this scenario does this technically mean only "any Kerberos authentication protocol" ? 
_Yes. Furthermore, the gateway relies on the Windows OS for Kerberos authentication so whatever Kerberos authentication protocol the Windows OS supports is what the gateway will use._

Or could other protocols be leveraged here?
_No because the gateway does not support it._ 

Is there a potential security risk/concern?
_No because the gateway only supports Kerberos SSO authentication in this scenario. Another protocol cannot be used._

**Comment by paulinbar** [comment]
Thanks @ms-kgorgi.
@acLuebke, I am going to close this issue now, and will engage with @ms-kgorgi as to whether and how to clarify the documentation. Thanks for taking the time to reach out with your question!

**Comment by ms-kgorgi** [comment]
@acLuebke fyi I updated my previous comment with additional information.
