### ISSUE TITLE
Incorrect filename

### ISSUE THREAD

**Issue by Darryl-G** [MicrosoftDocs/powerbi-docs#4447]
Hello,

The file "PowerBI.DataMovement.Pipeline.GatewayCore.dll.config"   is not found.
It should be **Microsoft.**PowerBI.DataMovement.Pipeline.GatewayCore.dll.config    ???

Thanks

Darryl

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa7ca8d8-0f83-2cd6-57b1-04fc8e04981b
* Version Independent ID: 196ee3c3-aa88-f8ca-c725-33bf77be0db5
* Content: [Use Security Assertion Markup Language for SSO from Power BI to on-premises data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-saml)
* Content Source: [powerbi-docs/connect-data/service-gateway-sso-saml.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sso-saml.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Darryl-G. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
