### ISSUE TITLE
Relative Date Filtering

### ISSUE THREAD

**Issue by hello789567** [MicrosoftDocs/powerbi-docs#447]
Wondering when you will be adding Quarter to the options in Relative Date Filters? Many businesses look at data for a quarter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @hello789567 -- this looks like a great product request, rather than documentation feedback. SO head on over to https://ideas.powerbi.com. You can search for this idea and up-vote it if you find it, and if not, you can add it so others can up-vote it. The product team looks through those ideas often, though maybe not over the Thanksgiving holiday. 
Thanks for contacting us!
