### ISSUE TITLE
App(build) permission allows user to share report with user that doesn't have any dataset permission

### ISSUE THREAD

**Issue by nachiketkmaat** [MicrosoftDocs/powerbi-docs#4478]
Looks like a Security bug.

I have a user (say User1) that doesn't have any workspace level permissions.

When I publish an app, add the User1 into the Audience, and checkmark the `Allow people to build content with the datasets in this app audience` (this is on the final page when publishing an app. I have NOT checkmarked the share dataset checkbox), then that user (User1) is able to create their own reports (that points to this dataset) and share their report with another user (User2). User2 is able to open the report even though User2 doesn't have any permission on the dataset (or workspace). Is this a bug?

For example: If I don't checkmark the above option, but give User1 `build` permission on the dataset, then the User1 is able to create own report (that points to this dataset), and when User1 shares their report with User2, then, User2 gets access denied. This is as expected.

So there is a potential bug with App (build)?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nachiketkmaat. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @nachiketkmaat. 

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
