### ISSUE TITLE
App Source Install link returns a 404

### ISSUE THREAD

**Issue by mdunnpexcard** [MicrosoftDocs/powerbi-docs#4483]
HI - The install link included in this article returns a 404 error.  What happened to app install and when will it return?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e206457c-e836-d03f-33fe-20d9f6e40979
* Version Independent ID: e206457c-e836-d03f-33fe-20d9f6e40979
* Content: [Install the Log Analytics for Power BI Datasets Template app (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/log-analytics/install-as-engine-app#install-the-app)
* Content Source: [powerbi-docs/transform-model/log-analytics/install-as-engine-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/log-analytics/install-as-engine-app.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @bstar92
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mdunnpexcard. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
