### ISSUE TITLE
Not available in Power BI org apps

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4487]
In the considerations and limitations we don't call out specifically that this is not available in Power BI apps today, it would be good to include that as well --> "The add-in currently supports Power BI report pages and visuals only. Other types of items such as dashboards and paginated reports aren't supported."

Thanks,

Dan English

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6201fae6-4740-8c60-7ce6-2b3691654e50
* Version Independent ID: 6201fae6-4740-8c60-7ce6-2b3691654e50
* Content: [About storytelling with Power BI in PowerPoint - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-power-bi-powerpoint-add-in-about)
* Content Source: [powerbi-docs/collaborate-share/service-power-bi-powerpoint-add-in-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-power-bi-powerpoint-add-in-about.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @denglishbi, thanks for your feedback. Let me just be sure I understand your suggestion. Are you suggesting that we should change the limitation so that it mentions apps specifically? For example:

The add-in currently supports Power BI report pages and visuals only. Other types of items such as dashboards, paginated reports, and organizational apps aren't supported.

Is something like that what you had in mind?
 -
