### ISSUE TITLE
How to add a tile to Power BI report

### ISSUE THREAD

**Issue by jaramiar** [MicrosoftDocs/powerbi-docs#4507]
Hi there. Have followed along these instructions. However, I do not see a tile feature anywhere in the current version of Power BI Service or Power BI Desktop. I would like to add HTML content. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d341efbc-c7f8-97ea-080f-8c5c4dc32613
* Version Independent ID: 473c098e-8d06-be1a-1720-d516a1ec5cc6
* Content: [Create or edit a dashboard tile - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboard-edit-tile)
* Content Source: [powerbi-docs/create-reports/service-dashboard-edit-tile.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-dashboard-edit-tile.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @jaramiar, hmm.. indeed, in Desktop I do not see that option. We will follow up. In the service, have you tried doing it in the service via a dashboard? Go into a workspace, select **New > Dashboard**
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/54644589/3b89196c-64a3-495a-8458-01483cb93881)

Then, in the new dashboard, choose Tile under the Edit menu:
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/54644589/35c362fc-e488-4454-bfd0-1c510b7c2291)
Does that give you the options you were looking for?
In the meantime I'm going to close this issue here and move your comment about the docs pages to our work backlog so that we can better consider it and track progress on it. Please feel free to comment on this issue still or to reopen if necessary. Thanks!
