### ISSUE TITLE
Using RLS with workspaces in Power BI - for Direct Access and Sharing Links

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#4532]
The section "Using RLS with workspaces in Power BI" needs to be expanded or cloned to cover the scenario where the report is shared as a Link or via Direct Access. It seems from my testing that "Read" access in that scenario is equivalent to the "Viewer" access described in that section? "Write" is equivalent to "Member"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mike-Honey. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Mike-Honey,
Thanks for your comment. I believe what you suggest is be true - that RLS will be applied in the case of a user who does not have a role in the workspace but who has been given read permissions explicitly - either via a link or direct access. This table https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-permissions#permissions-acquired-implicitly-via-workspace-role shows the actual dataset permissions that are granted per workspace role. I think that what RLS really looks for is the "read" permission, rather than the "Viewer" role. I will confirm this with the product team and add to the article if necessary, as you suggest. In the meantime I am creating a work item to follow this and closing this issue. Feel free to reopen if you feel the need. Thanks!
