### ISSUE TITLE
New Workspace Preview does not give access to Dataset when App is published

### ISSUE THREAD

**Issue by lukaszjakubczyk** [MicrosoftDocs/powerbi-docs#455]

**Comment by lukaszjakubczyk** [comment]
When app is published from new workspace (preview) then access to dataset that are related with published reports is not granted automatically. I had to add access to dataset manually.

**Comment by mgblythe** [comment]
@lukaszjakubczyk Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by maggiesMSFT** [comment]
Hi, @lukaszjakubczyk -- again thanks for your comment! Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
