### ISSUE TITLE
Continually getting errors at DAX step and typo in tutorial

### ISSUE THREAD

**Issue by suetholen** [MicrosoftDocs/powerbi-docs#4558]
[Enter feedback here]
The tutorial says in text to do many to one in one direction but it looks like the image shows the opposite.
This is at the step in the tutorial for creating the model, after the dataflow and pipeline.
Separate from that or possibly related, I keep getting errors of various sorts and it "reverts to previous version" but the previous version can't be edited to add a DAX measure or anything else without that same error.  I started over from scratch since no way to back up in time or undo things, but got the same errors at the same point.  Cannot get past the modeling step. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @suetholen. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
