### ISSUE TITLE
New Workspace Preview - users outside tenant cannot be added to the App

### ISSUE THREAD

**Issue by lukaszjakubczyk** [MicrosoftDocs/powerbi-docs#457]
I cannot grant access to App that was built in new workspace (Preview) to users that are outside of the tenant. It is possible in the previous version.

**Comment by mgblythe** [comment]
@lukaszjakubczyk Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by maggiesMSFT** [comment]
Hi @lukaszjakubczyk -- Thanks for your comment. Looks like this is product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
