### ISSUE TITLE
What is the need for external Sharing setting

### ISSUE THREAD

**Issue by machariajosemwangi** [MicrosoftDocs/powerbi-docs#4578]
Hello, even after allowing external sharing  in the settings, I cannot share the dataset outside my organization. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca3ecd13-b49c-1263-a464-c5582ea08307
* Version Independent ID: ca3ecd13-b49c-1263-a464-c5582ea08307
* Content: [Use Power BI in-place dataset sharing (preview) to share datasets with external users - data provider - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-dataset-external-org-share-provider)
* Content Source: [powerbi-docs/collaborate-share/service-dataset-external-org-share-provider.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-dataset-external-org-share-provider.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @machariajosemwangi. This issue has been assigned to the doc author for review.

**Comment by ajburnle** [comment]
Thanks for your feedback, I am investigating this issue.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
