### ISSUE TITLE
发生了异常: 不支持给定的数据源种类。数据源种类: Lakehouse。

### ISSUE THREAD

**Issue by liliwen365** [MicrosoftDocs/powerbi-docs#4584]
[Enter feedback here]
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/76478019/50089e74-acc5-4b24-b563-ccda7069b9a6)
链接到目标数据时总是出现：发生了异常: 不支持给定的数据源种类。数据源种类: Lakehouse。

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @liliwen365. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
@itsnotaboutthecell, here's a translation of the title and body. Does it ring any bells?

Title: An exception occurred: The given data source kind is not supported. Data source type: Lakehouse

Body: When linking to the target data always occurs: An exception has occurred: The given data source type is not supported. Data source type: Lakehouse.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
