### ISSUE TITLE
power query template data is not working.

### ISSUE THREAD

**Issue by mvkally** [MicrosoftDocs/powerbi-docs#4632]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started#prerequisites)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](![err](https://github.com/MicrosoftDocs/powerbi-docs/assets/46073512/60c7672d-e1d6-4edf-8de3-d1e81ccf2a3b))
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mvkally. This issue has been assigned to the doc author for review.

**Comment by itsnotaboutthecell** [comment]
Hi @mvkally can you provide more detail on what is not working, I'm able to view the data in the Power Query data preview window without issue and to proceed with the refresh.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
