### ISSUE TITLE
Paginated reports and Power BI Premium

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#4651]
Does this article need to get updated given that Power BI Premium is not required for paginated reports as of https://powerbi.microsoft.com/en-us/blog/announcing-support-for-paginated-reports-in-power-bi-pro/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfaaf125-cd9e-4b88-c808-3bd53525d367
* Version Independent ID: df09f8c6-0e60-14dc-6095-c2be885019c7
* Content: [Create and use the paginated report visual - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/paginated-report-visual)
* Content Source: [powerbi-docs/visuals/paginated-report-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/paginated-report-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GitWesDone. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @GitWesDone, checking this out. Thanks for bringing this to our attention.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
