### ISSUE TITLE
Export to PNG with multiple pages specified

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#4692]
The documentation should reflect how the action behaves when provided with an array of pages and the export format is PNG.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GitWesDone. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @GitWesDone, I have created a work item to find the answer to your question and to update the documentation. I'll put your revised title in the item. I can't give an ETA when we'll update the doc though because we have a backlog. But now your comment is in a system where we can track it more easily. I have also make a note to update this issue when we've made the update, so you should hear about it.
If you need the answer now, then I suggest you give the [Power BI Community](https://community.powerbi.com/) our [support page](https://support.powerbi.com/) a try. In the meantime I am going to close this issue here. Thanks!
