### ISSUE TITLE
Embed a report web part in SharePoint Online  - report isn't in POwer BI Manage permission yet it's showing up on SharePoint Online communication site

### ISSUE THREAD

**Issue by gretchunkim** [MicrosoftDocs/powerbi-docs#4697]
Unlike what's described in the documentation, I see that the report is showing for a user without permission granted from the Power BI report when the report is embedded in SharePoint Online on Communication site in which the user has read permission. 

Permission setting: Test User
**On SharePoint Online Communication Site:** Read only
On Power BI Workspace manage permission:  None! 

Result: Test User is viewing the report 
Expected behavior: Test User won't be able to view the report unless it's granted from Power BI Workstat0 Direct Access as indicated on the documentation.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gretchunkim. This issue has been assigned to the doc author for review.

**Comment by gretchunkim** [comment]
This issue is no longer reproducible on my end - MS Support reached out and able to reproduce the issue when we were on a call when the permission was  given then taken out- The report was still showing up (even after cache clear) even after permission was taken way.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @gretchunkim.

This looks like product feedback or a product question, rather than documentation feedback. Looks like you already contacted support and got the issue resolved. If you haven't. you can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
