### ISSUE TITLE
Will External Member B2B support with the PowerBI?

### ISSUE THREAD

**Issue by simonkw2000** [MicrosoftDocs/powerbi-docs#4708]
From the article below, it mentions that External member isn't supported in Power BI. Only External Guest will do.

May I know any reasons? Any workarounds and plan to allow External Member supported in Power BI?

https://learn.microsoft.com/en-us/azure/active-directory/external-identities/user-properties

**Comment by bishalgoswami** [comment]
Thanks for your comment, @simonkw2000. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @simonkw2000.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
