### ISSUE TITLE
Why I can't aggregate Currency field in my D365 CRM?

### ISSUE THREAD

**Issue by CMF220** [MicrosoftDocs/powerbi-docs#4716]
I have a similar D365 CRM environment with several currency fields in the table. But when clicking on the "visualize this view" button, I can't do aggregation for the currency field. 
Any reason of that? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa2a0fbc-0b85-9b61-d5a6-af09b1e11608
* Version Independent ID: fa2a0fbc-0b85-9b61-d5a6-af09b1e11608
* Content: [Visualize your data quickly from Power Apps and Dynamics 365 apps - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/dynamics-quick-create-report)
* Content Source: [powerbi-docs/create-reports/dynamics-quick-create-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/dynamics-quick-create-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CMF220. This issue has been assigned to the doc author for review.

**Comment by CMF220** [comment]
Hi, this is the field setting in our D365 CRM:
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/142768453/b2b36a8a-a4d5-4e1d-811e-cef13fabde13)

**Comment by maggiesMSFT** [comment]
Hi, @CMF220 -- thanks for the screen shots! I'll investigate and get back to you.

**Comment by maggiesMSFT** [comment]
Hi @CMF220 -- I've got a 2-pronged answer for you. 

1. Fix it yourself: this issue is that the data types are not being set when the model is being generated from Dynamics, so the currency field in your case could be showing up as Text type. 

If you save the report to the Power BI service, you could potentially use the new modeling on the web preview to make sure all the data types are set up correctly, and then the report should start working the way you’d expect. 

2. If you'd like it to "just work," you should reach out to the Dynamics support team to file an issue with them, since their team would have to be the one to fix it. The Currency data type is not properly mapped. This is done by Dynamic teams. They have logic to map their data types to data types that Power Query supports. 

Good luck!

**Comment by CMF220** [comment]
Hi Maggie,

Appreciate your sharing and help!
I will contact Dynamics support team to have a thorough fix for it.

Kind regards,
Chunming
