### ISSUE TITLE
can't export embedded power bi dashboard to powerpoint in sharepoint online

### ISSUE THREAD

**Issue by Kizar123** [MicrosoftDocs/powerbi-docs#4718]
Unbale to export embedded power bi dashboard to powerpoint in sharepoint online

Could any one help me in this ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed a report web part in SharePoint Online - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-spo)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-embed-report-spo.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Kizar123. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Kizar123 -- just trying to understand the scenario. You were able to embed the Power BI report in a SharePoint site page successfully, yes? Was it a report, or a dashboard? This article is specifically about embedding a _report_, not a dashboard. 

And after that, you want to export the report to PowerPoint?

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
