### ISSUE TITLE
Does Azure Map Conversion Note Apply to Shape Maps?

### ISSUE THREAD

**Issue by PBrad** [MicrosoftDocs/powerbi-docs#4723]
Does the note at the top of the page about Azure Maps general availability and converting Maps / Filled Maps to Azure Maps apply to Shape Maps? If you follow the link provided in the note to ["convert maps and filled maps to Azure Maps visuals"](https://learn.microsoft.com/en-us/azure/azure-maps/power-bi-visual-conversion?context=/power-bi/create-reports/context/context) the documentation only references Maps and Filled Maps, but does not reference Shape Maps.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @msftrien
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PBrad. This issue has been assigned to the doc author for review.

**Comment by msftrien** [comment]
It does not yet apply. I'll update this doc to remove that notice for now.

**Comment by PBrad** [comment]
Thank you @msftrien and @bishalgoswami !

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
