### ISSUE TITLE
Missing basic information about how to get started with App. 

### ISSUE THREAD

**Issue by GGBMLC** [MicrosoftDocs/powerbi-docs#4737]
[Enter feedback here]
Hi
I tired to use the Power Bi App function.
But the GUI require a "CapacityID" ??

Where can I found this Id?
Why is the ID not present in a Power BI report?
Also this setup information are missing from the webpage about Power BI App.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe16182b-c80c-4cc3-da85-bf6fb0fe152f
* Version Independent ID: 6b92afe7-dfda-39b3-455c-e886b27e3d70
* Content: [Apps in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-apps)
* Content Source: [powerbi-docs/consumer/end-user-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GGBMLC. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @GGBMLC ,
Thank you for submitting your feedback.  However, I am unable to duplicate your error.
This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
