### ISSUE TITLE
Inconsistent content

### ISSUE THREAD

**Issue by g2000ny** [MicrosoftDocs/powerbi-docs#4744]
[Enter feedback here]
Content of this page is obsolete.  When I click on New button, I don't see the upload anymore.  Instead I have to click on the upload button which is right next to the new button to upload.  Yet, after successful upload of the file, I don't see the dataset.  Reload does not help either.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96cd9605-f371-a7b3-4a2f-8c9cd1125db6
* Version Independent ID: 4d250457-caa3-4127-07ce-5fb1fa6a0720
* Content: [Tutorial: From Excel workbook to a Power BI report in Microsoft Teams - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-from-excel-to-stunning-report)
* Content Source: [powerbi-docs/create-reports/service-from-excel-to-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-from-excel-to-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @g2000ny. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
