### ISSUE TITLE
Very difficult to follow tutorial

### ISSUE THREAD

**Issue by rickhardy** [MicrosoftDocs/powerbi-docs#4745]
This tutorial requires some work to make it possible to follow for IT professionals

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rickhardy. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
