### ISSUE TITLE
When exactly PowerBI added 'Live connection' feature to the Desktop version? 

### ISSUE THREAD

**Issue by InnaPidd** [MicrosoftDocs/powerbi-docs#4754]
When exactly PowerBI added 'Live connection' feature to the Desktop version?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @InnaPidd. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @InnaPidd.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
