### ISSUE TITLE
Wrong screenshot for "Queries & Connections" option for Refresh All Objects

### ISSUE THREAD

**Issue by keithrjones** [MicrosoftDocs/powerbi-docs#4757]
Under the Refresh All Objects section the screenshot for the second option using the Queries & Connections pane does not show that UI. Instead the screenshot is the same as the one shown for the Refresh All->Refresh option.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a4819a8-3056-4134-248c-b216300f62dd
* Version Independent ID: 7a4819a8-3056-4134-248c-b216300f62dd
* Content: [Design refreshable reports in Excel with Power BI data - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-power-bi-datasets-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-power-bi-datasets-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-analyze-power-bi-datasets-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @keithrjones. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
