### ISSUE TITLE
Connection to Azure Analysis Service

### ISSUE THREAD

**Issue by vishalaj1** [MicrosoftDocs/powerbi-docs#477]
Hi,

We have reports which are connecting to azure analysis service.

Can we deploy them here? I cannot see any option for connection string for azure analysis service.

Regards,
Vishal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da59f209-0ccd-01d0-6e0e-12943ef3680e
* Version Independent ID: 390690ff-76bd-f4c6-afac-d5ad2f3854cb
* Content: [Tutorial: Create a paginated report and upload it to the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-quickstart-aw)
* Content Source: [powerbi-docs/paginated-reports-quickstart-aw.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-quickstart-aw.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @vishalaj1. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. In the meantime, you could ask your question in the community: https://community.powerbi.com/.

**Comment by maggiesMSFT** [comment]
Hi, @vishalaj1 -- currently paginated reports in the Power BI service support these data sources:
Azure SQL Database and Data Warehouse
SQL Server
SQL Server Analysis Services
See this article for details: https://docs.microsoft.com/en-us/power-bi/paginated-reports-embedded-data-source. 
More data sources will be coming.
Thanks for asking!

**Comment by jdfancke** [comment]
Hi @maggiesMSFT -- I have also tried to upload a report using Azure Analysis Services and am having issues as per the image below.
![641941b4-58cd-4548-8e6c-14483248fa8b](https://user-images.githubusercontent.com/20044040/52254557-73551380-2962-11e9-9abf-d37881e9e5a6.jpg)

I sent a quick [tweet](https://twitter.com/jdfancke/status/1092548433393549312) to Bhavik Merchant asking him because in his [talk at Ignite](https://t.co/nz9upYMB9h) he specifically mentions that Azure Analysis Services is supported (although his slide states SQL Server Analysis Services, but he speaks as if AAS is included within this). 

If AAS is not specifically supported right now it may be worth mentioning in the article to avoid confusion.

**Comment by maggiesMSFT** [comment]
Hi, @vishalaj1 and @jdfancke -- Support for Azure Analysis Services is coming, but isn't here yet. 
thanks for asking!

**Comment by vishalaj1** [comment]
Do we have some approximate time line? We have moved to azure and this is hurting us since we cannot connect the on prem report server to azure analysis services neither can we deploy the ssrs report on service to connect azure analysis service.
