### ISSUE TITLE
GA release date for report readers using field parameters to change visuals

### ISSUE THREAD

**Issue by bradsmucker** [MicrosoftDocs/powerbi-docs#4773]
Hello,

We are using field parameters to handle data translations, and I was wondering when the ability to let report readers use field parameters to change visuals would move from preview to general availability.

Unless I am missing it, I do not see it in the current release wave:

https://learn.microsoft.com/en-us/power-platform/release-plan/2023wave2/power-bi/planned-features

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Version Independent ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Content: [Let report readers use field parameters to change visuals (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-field-parameters)
* Content Source: [powerbi-docs/create-reports/power-bi-field-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-field-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bradsmucker. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bradsmucker.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
