### ISSUE TITLE
When Do Users Receive Request Emails

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/powerbi-docs#4783]
"If you're a report owner, you **might** receive an email..."

I came to this article looking to understand who receives report access requests. But the article doesn't know either.

The question is who receives access requests for Reports and Apps?

**Product Feedback**

I know it's product not documentation feedback - but we should also be able to turn off request sharing. I want to give the users a note or URL on the proper way to request access which in most cases is by adding them to an AD/Entra Group. Please pass this along to the product team.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eee97d20-cca2-c705-0429-6debab9f9a32
* Version Independent ID: 40334cca-f3c1-e8a8-7df2-e53e78ecfb40
* Content: [Request or grant access to dashboards or reports - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-request-access)
* Content Source: [powerbi-docs/collaborate-share/service-request-access.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-request-access.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JoelLeichty. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
