### ISSUE TITLE
Finding product keys for Power BI Report Server if purchased through CSP

### ISSUE THREAD

**Issue by jonharris-microsoft** [MicrosoftDocs/powerbi-docs#4788]
How do I get the product key for Power BI Report Server when I purchase SQL Server Enterprise Core in CSP, as granted here: https://www.microsoft.com/licensing/terms/productoffering/ServerSubscriptionsforAzure/MCA

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69db1b96-91ed-2440-5a1c-873a19d7ee47
* Version Independent ID: db0e2007-963b-44a5-9b6e-5be35481473e
* Content: [Install Power BI Report Server - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/install-report-server)
* Content Source: [powerbi-docs/report-server/install-report-server.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/install-report-server.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jonharris-microsoft. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
