### ISSUE TITLE
dataset structure

### ISSUE THREAD

**Issue by jongkok** [MicrosoftDocs/powerbi-docs#4793]
if i want to "Use specific Latitude and Longitude" AND ALSO "Use geo-hierarchies so you can drill down to different levels of location", what my dataset (sales revenue per location) should looks like ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Tips and Tricks for maps (including Bing Maps integration) - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-map-tips-and-tricks)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jongkok. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @jongkok. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
