### ISSUE TITLE
[BUG] Open in new tab does not work

### ISSUE THREAD

**Issue by opwvhk** [MicrosoftDocs/powerbi-docs#4797]
When trying to open the home in a new tab (I want to keep the current report open), this fails.

Searching for the text "Open in new tab" gives me results that don't look like what I searched for, and the top result (the only likely candidate) does not describe a working solution.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Version Independent ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Content: [Power BI dataset experience in Excel - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-connect-excel-power-bi-datasets?wt.mc_id=searchapi_inproduct_fabrichelppane)
* Content Source: [powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @opwvhk. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
