### ISSUE TITLE
Regarding Document Update of Power BI Report Server.

### ISSUE THREAD

**Issue by SwaroopSorte** [MicrosoftDocs/powerbi-docs#4804]
Is this updated Document ?
Because We are able to share on Power bi service
Able to add bookmarks.
Able to View in Full Screen. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Compare Power BI Report Server and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SwaroopSorte. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
