### ISSUE TITLE
Dataverse connector in Power BI desktop does not translate or show the display names of the columns correctly

### ISSUE THREAD

**Issue by spasal** [MicrosoftDocs/powerbi-docs#4864]
The dataverse connector in Power BI desktop is not translating or showing the display names of the columns correctly. This issue appeared in the October/September 2023 version of Power BI desktop and was not present in the July 2023 version. I am unable to use the dataverse connector to its full potential due to this issue.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @spasal. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @spasal.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
