### ISSUE TITLE
New throttling mecanism

### ISSUE THREAD

**Issue by pauljenny** [MicrosoftDocs/powerbi-docs#4892]
As there is now a new mecanism on throttling with Fabric / Premium capacities, the Power BI Premium FAQ looks like not up-to-date anymore.

i.e.: "If a capacity’s utilization exceeded a 100% and it cannot use autoscale, due to being turned off or already at its maximum v-core utilization value, the capacity enters into a temporary interactive request delay mode[....]". There are now carryforwards to overcome temporarily the 100% utilization value (https://learn.microsoft.com/en-us/fabric/enterprise/throttling).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea1adec6-8c0c-a72c-c165-19a72bae7cc6
* Version Independent ID: a2543cc8-a37b-dde4-b0fe-5ebeb9ed2560
* Content: [Power BI Premium FAQ - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-faq)
* Content Source: [powerbi-docs/enterprise/service-premium-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pauljenny. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @pauljenny,

Thank you for pointing this out.

I fixed [What happens to traffic during overload if I don't autoscale?](https://learn.microsoft.com/power-bi/enterprise/service-premium-faq#what-happens-to-traffic-during-overload-if-i-don-t-autoscale-) so that it points to [The Fabric throttling policy](https://learn.microsoft.com/fabric/enterprise/throttling).

This change will go live shortly.

Kesem
