### ISSUE TITLE
"In Power BI, support for UserType Member is currently in preview" | Mean ?

### ISSUE THREAD

**Issue by vamdevmishra** [MicrosoftDocs/powerbi-docs#4894]
[Enter feedback here]
Can someone explain what is the meaning of this statement in detail, it creates ambiguity and need clarity what may or may not work or has know issue/restrictions?

"In Power BI, support for UserType Member is currently in preview"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vamdevmishra. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@vamdevmishra Thank you for taking the time to submit feedback. The referenced article has been updates since your comment was submitted, so I am closing this issue now. If you have additional feedback, please feel free to use the on-page feedback tools for the article. Thanks again for taking the time to help improve our docs!
