### ISSUE TITLE
Adding Single Values in to Multiple Groups in PowerBI

### ISSUE THREAD

**Issue by JacksonMahomes** [MicrosoftDocs/powerbi-docs#4911]
Is it possible to add the same value in to multiple groups? 

For example if I have 3 values; A, B, and C. Can I create groups that follow this structure:
 Group 1: A
 Group 2: A and B
 Group 3: A, B, and C

I'm essentially trying to create a funnel report and am stuck. When I create a group in PowerBI based on values from one of my fields, if I select value A for group 1 I can no longer select value A for another group.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JacksonMahomes. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @JacksonMahomes.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
