### ISSUE TITLE
What are the labels?  How do you define them?

### ISSUE THREAD

**Issue by SnakePlissken47** [MicrosoftDocs/powerbi-docs#4931]
What are the labels?!  Why didn't you list them?!  Where are the definitions?!  This is very basic.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2b9a90f-49bf-0605-dc45-f58494f6d956
* Version Independent ID: f2b9a90f-49bf-0605-dc45-f58494f6d956
* Content: [Sensitivity labels from Microsoft Purview Information Protection in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-sensitivity-label-overview)
* Content Source: [powerbi-docs/enterprise/service-security-sensitivity-label-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-sensitivity-label-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @SnakePlissken47, thanks for your feedback. You are absolutely right - the documentation is unclear. We are currently in the process of migrating the Power BI information protection articles over to the Fabric documentation, and as part of this process we'll be reviewing the documentation with the aim of making it shorter and more clear. So your point is well taken. In any event, in order to get sensitivity labels going, you need the sensitivity labels and label policies that are published to users, and you need to enable sensitivity labels in the Fabric tenant settings. The labels and policies are not defined in Fabric/Power BI, but rather in the MIcrosoft Purview compliance center. See the fourth bullet under this section https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-enable-data-sensitivity-labels#licensing-and-requirements. In that bullet, there is a link that takes you to the Microsoft Purview information protection documentation (which I don't control) about creating sensitivity labels. You are absolutely right.. such basic information buried in a bullet under Licensing and requirements. This will be rectified. 
Anyway, again, thanks for taking the time to give us your feedback!
