### ISSUE TITLE
The user has exceeded the amount of embed token that can be generated on a shared capacity.

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4934]
Can you please provide more information on the amount of embed token that can be generated on a shared capacity?

For example, what is the number of tokens? 

Is there a way to check the that the number of tokens is the issue since it is one of several possibilities that will cause the 403 error?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cca83c56-2eeb-fc12-a845-9d1161ee2f05
* Version Independent ID: cca83c56-2eeb-fc12-a845-9d1161ee2f05
* Content: [Troubleshoot Power BI REST APIs - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/troubleshoot-rest-api)
* Content Source: [powerbi-docs/developer/embedded/troubleshoot-rest-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/troubleshoot-rest-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi @djurecic0, thanks for your question.
We don’t disclose this number since it changes depending on the level of abuse of privilege.  You can check the burn rate via API:  [Available Features - Get Available Features - REST API (Power BI Power BI REST APIs) | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Frest%2Fapi%2Fpower-bi%2Favailable-features%2Fget-available-features&data=05%7C02%7Cmonaberdugo%40microsoft.com%7C02ee8fa2c1cd450666bf08dc1823d34f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638411789544057556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IahI%2Bu6ilzVYIFEAtWdXppCv8HjzjPptOwr672oZ%2FmQ%3D&reserved=0). Usage is reported as whole number but actually is a percentage.  The closer you are to 100 the fewer tokens you have left.
Hope this helps!
