### ISSUE TITLE
What F sku is required to run "embed for your customers scenario"?

### ISSUE THREAD

**Issue by apappila** [MicrosoftDocs/powerbi-docs#4952]
Document is unclear on what is the minimum size of F sku that you need to be able to run the scenario  "embed for your customers scenario". Per user license is not required for consuming the reports in embedded - so should the ISV buy the A sku or is a smaller than F64 sku a possible option for embedding PBI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @apappila. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @apappila 
that F SKUs support PaaS embed on any size SKU.  It is just may not be too practical to use smaller SKUs because F2 is smaller than even A1 where devs were running of capacity all the time: [Capacity and SKUs in Power BI embedded analytics - Power BI | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpower-bi%2Fdeveloper%2Fembedded%2Fembedded-capacity%23which-sku-should-i-use&data=05%7C02%7Cmonaberdugo%40microsoft.com%7C02ee8fa2c1cd450666bf08dc1823d34f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638411789544079264%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ArsrjRltnVLcTwker1Sdy6kOTLPDBoUpvef%2BqsmN5XI%3D&reserved=0)
