### ISSUE TITLE
Update "openssl" to resolve CVE findings of Power BI Desktop

### ISSUE THREAD

**Issue by Zachery2008** [MicrosoftDocs/powerbi-docs#4954]
As for now, the latest Power BI Desktop version is 2.124.1554.0, it has openssl version 3.0.9. Our Azure Defender reports there are a few openssl CVE findings. Please help to upgrade openssl.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Zachery2008. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Zachery2008.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
