### ISSUE TITLE
Where to install the HANA client for windows?

### ISSUE THREAD

**Issue by Robby29** [MicrosoftDocs/powerbi-docs#498]
Hi can you please mention how to install the HANA client. I got the SAR file from SAP marketplace but where to place the file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea414a5c-c3ca-281e-46ca-3e677d27924b
* Version Independent ID: 363a9c9c-13e2-58ce-cb79-9f897d83c307
* Content: [Use SAP HANA in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-hana)
* Content Source: [powerbi-docs/desktop-sap-hana.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-hana.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Robby29. We’ve forwarded your feedback to the writer, who should respond soon.

**Comment by davidiseminger** [comment]
Thanks for your comment, @Robby29 . This looks like a support request (for SAP, too) rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. Or you can check the SAP documentation or support channels.
