### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by SConnellSwordGroup** [MicrosoftDocs/powerbi-docs#4988]
# Known issues and limitations
- Currently, Direct Lake models can only contain tables and views from a single Lakehouse or Data Warehouse. However, tables in the model based on T-SQL-based views cannot be queried in Direct Lake mode. DAX queries that use these model tables fall back to DirectQuery mode.

From https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview#known-issues-and-limitations
I feel that this sentence is ambiguous and could be revised for clarity.
I assume that a warehouse view (for example) is intrinsically T-SQL based so am I also to assume that this is not usable for Direct Lake? I am told explicitly that it is. What is meant by tables in the model? Does this mean **Semantic Model** tables where I have used a TSQL script to define and join **Warehouse** tables as opposed to a view in my Warehouse which is scripted like this example:
```

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[Territory]
AS SELECT 
SalesTerritoryKey
,SalesTerritoryRegion as Region
,SalesTerritoryCountry as Country
,SalesTerritoryGroup as [Group]
FROM [DimSalesTerritory]
GO
```
Any clarification would be useful.

Kind regards.
Stephen Connell

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Version Independent ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Content: [Learn about Direct Lake in Power BI and Microsoft Fabric - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview#known-issues-and-limitations)
* Content Source: [powerbi-docs/enterprise/directlake-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SConnellSwordGroup. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SConnellSwordGroup. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SConnellSwordGroup. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SConnellSwordGroup. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SConnellSwordGroup. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SConnellSwordGroup. This issue has been assigned to the doc author for review.

**Comment by jeroenterheerdt** [comment]
@christianwade should probably take a look at this

**Comment by christianwade** [comment]
@KayUnkroth do you mind chiming in here?

**Comment by KayUnkroth** [comment]
Let's start with some definitions:

1. Direct Lake model -- A semantic model that uses the new Direct Lake storage mode. 
2. Direct Lake storage mode -- A new *dual* mode that lets the model load data directly from Delta tables in Direct Lake mode or indirectly from a T-SQL Endpoint in DirectQuery mode. 
3.  Direct Lake mode -- The specific method to load data directly from Delta tables.
4. Fallback to DirectQuery mode -- An automatic (and transparent) switch from Direct Lake mode to DirectQuery mode whenever the model cannot load data directly from Delta tables.

With this out of the way:

- Yes, you can select tables and views to add tables to a Direct Lake model.
- In the Direct Lake model, there are only tables, i.e. tables based on DW tables, and tables based on DW views.
- Because views are T-SQL constructs that aren't backed by a Delta table, a Direct Lake model cannot use Direct Lake mode to load that data directly from Delta tables. The views must be queried using the T-SQL endpoint. Therefore, DAX queries that query these "view-backed" tables (in the semantic model) must always fall back to DirectQuery mode.

**Comment by kfollis** [comment]
[like]  Kate Follis reacted to your message:
________________________________

**Comment by SConnellSwordGroup** [comment]
OK. @KayUnkroth, thanks for that clarification. Given this detail and that the https://learn.microsoft.com/en-us/training/paths/work-semantic-models-microsoft-fabric/ learning path has this exercise, https://learn.microsoft.com/en-us/training/modules/understand-scalability-power-bi/4a-exercise-create-star-schema-model, https://microsoftlearning.github.io/DP-500-Azure-Data-Analyst/Instructions/labs/04-create-a-star-schema-model.html. Is it possible to satisfy this as a Direct Lake Model. It feels like the answer is no or at least yes but the tables will fallback to Direct Query.

Sorry if this takes thing in a tangential direction.

**Comment by SConnellSwordGroup** [comment]
Food for thought here, and I'm genuinely trying to get my head around the impacts of the limitations. I think the limitations as they are presently described will require some very careful planning of what we intend to contain in our Facts when Direct Lake is the plan. It also feels that in many cases views to limit Dimensions or remove snowflakes will be the norm. I suspect the data size will be the determinate factor and whether the additional redundancy will outweigh the impacts of fallback.  Thanks for the input.
