### ISSUE TITLE
Visual calculation is not available with Lines and stacked column chart 

### ISSUE THREAD

**Issue by MusicDendy** [MicrosoftDocs/powerbi-docs#5026]
Visual calculation is not available with Lines and stacked column char

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MusicDendy. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @MusicDendy.

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

You can also submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).
