### ISSUE TITLE
App Power BI & Template App

### ISSUE THREAD

**Issue by wanajo38** [MicrosoftDocs/powerbi-docs#5034]
Hi,

I saw that in May 2024, the old app version must be updated for the new version.

What about the template app? Because I try to update my app in my template app workspace and it doesn't work.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @wanajo38. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Thanks for your comment, @wanajo38. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community](https://community.fabric.microsoft.com/t5/Power-BI-forums/ct-p/powerbi). If not, try our [support page](https://support.fabric.microsoft.com/en-us/support/).
