### ISSUE TITLE
Not able to locate Drill-through in Visualizaiton pane in POWER BI, despite turned it on from settings.

### ISSUE THREAD

**Issue by Nomangihub** [MicrosoftDocs/powerbi-docs#5042]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70cc0df0-14a7-079d-c32c-78fff8aef03f
* Version Independent ID: ff23bd8e-3901-3010-af39-19fb69f2fa6c
* Content: [Use cross-report drillthrough in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-cross-report-drill-through)
* Content Source: [powerbi-docs/create-reports/desktop-cross-report-drill-through.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-cross-report-drill-through.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Nomangihub. This issue has been assigned to the doc author for review.

**Comment by Nomangihub** [comment]
Dear Bishal,

Still haven't heard back from the author.

Regards
Noman

**Comment by tasnef** [comment]
We used all the changes, spaces, directories, and reports in PowerP on several projects and several levels of graphic flows, some of which are large and some of which are small. Unfortunately, there is a party that controls, blocks, opens, permits, closes, kidnaps, and replaces. We cannot control the settings of your devices. You are supposed to help us, we are the right holders, and learn the truth about the infiltrator, and announce it. These are not ordinary projects, crucial projects. If we submit them, otherwise we stop them and through the courts, they will be prolonged or shortened, or we will hand them over to any government investment fund, jointly or equally. It is safer than engaging in such endless wars

**Comment by tasnef** [comment]
We used all the changes, spaces, directories, and reports in Power bi several projects and several levels of graphic flows, some of which are large and some of which are small. Unfortunately, there is a party that controls, blocks, opens, permits, closes, kidnaps, and replaces. We cannot control the settings of your devices. You are supposed to help us, we are the right holders, and learn the truth about the infiltrator, and announce it. These are not ordinary projects, crucial projects. If we submit them, otherwise we stop them and through the courts, they will be prolonged or shortened, or we will hand them over to any government investment fund, jointly or equally. It is safer than engaging in such endless wars

**Comment by maggiesMSFT** [comment]
Hi, @Nomangihub -- I'll set up the scenario and run through it, to see what's changed. Thanks for your comment!
I created a work item for myself: https://dev.azure.com/msft-skilling/Content/_workitems/edit/239008/
