### ISSUE TITLE
Different behaviours for xls in PBI Destop and Service

### ISSUE THREAD

**Issue by eduardo-suela-DEq** [MicrosoftDocs/powerbi-docs#5080]
This is the problem in PBI Service with no solution
https://community.fabric.microsoft.com/t5/Service/Power-BI-Direct-Connect-Refresh-to-XLS-Fail/m-p/128076

This is the problem in PBI Desktop with a solution
https://community.fabric.microsoft.com/t5/Desktop/quot-Microsoft-Access-The-Microsoft-ACE-OLEDB-12-0-provider-is/m-p/109184/highlight/true#M45918

I also see using a gateway to a local space with the driver, but this implies too many changes in already developed pbix 
https://community.fabric.microsoft.com/t5/Service/On-Premise-Data-Gateway-and-Access-Databases/m-p/2301597

There are still many programs and web sites that generate xls as a file export.
For example linked-in analytics are generated as xls. Also other web analytics services export xls
**There is the need to read xls, because they are in the market.**
**But it is a serious problem when publishing pbix as xls files that were readable in Desktop are no longer readable in Service**

Please keep the solution available in desktop.
Please add the driver in the service.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @eduardo-suela-DEq. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @eduardo-suela-DEq.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by eduardo-suela-DEq** [comment]
Thank you
Yes it is a product feedback
I will post it in that section
