### ISSUE TITLE
Grouping by selecting elements in a visual not working

### ISSUE THREAD

**Issue by CarterCenter-AlexAddison** [MicrosoftDocs/powerbi-docs#5085]
"Then right-click one of the selected elements, scroll to Group, and choose Group from the context menu."

This function appears to be broken. I have a set of related columns that are not summarized. It is virtually identical to the example shown. Ctrl-click to select multiple items works. When right-clicking to bring up the contextual menu, "Group" is grayed out.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CarterCenter-AlexAddison. This issue has been assigned to the doc author for review.

**Comment by CarterCenter-AlexAddison** [comment]
Hi Kesem,
I provided as much info as I could. There is probably no article associated with it. I filed this weeks ago. It is a bug, not an article feature.
Alex

**Comment by KesemSharabi** [comment]
Thanks for your comment, @CarterCenter-AlexAddison.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Microsoft Fabric Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
