### ISSUE TITLE
Need Usage Metrics

### ISSUE THREAD

**Issue by systamper** [MicrosoftDocs/powerbi-docs#525]
I know this is not currently included, but can you share WHEN it will be? The new app workspace is fantastic! But we really need usage monitoring ASAP.

Thanks, Scott

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#planned-new-app-workspace-preview-features)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @systamper -- thanks for asking. I'll poke around and see if I can find an answer. Often these days, the product team spells out upcoming features in the Business Applications Release Notes, https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/power-bi-service/overview. So that's a good place to check.

**Comment by maggiesMSFT** [comment]
Hi @systamper -- sounds like it's a feature coming in the next few months, the next quarter. Hope that helps!
