### ISSUE TITLE
Essbase Connector

### ISSUE THREAD

**Issue by anbuchelva** [MicrosoftDocs/powerbi-docs#540]
Connecting to essbase database is unsuccessful. Adding tutorial would help a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-sources)
* Content Source: [powerbi-docs/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting @anbuchelva  - we'll look into putting a tutorial for Essbase into our work planning.

**Comment by msfttimmac** [comment]
Are we still working on putting together a tutorial on how to connect to ESSBASE?

**Comment by anbuchelva** [comment]
I found how to connect essbase. My initial experiments here: https://blog.anbuchelva.in/hyperion/power-bi-and-essbase-initial-experiments/

**Comment by msfttimmac** [comment]
Yes.  I found that as well.  I am trying to get official Microsoft Documentation here, as the customer is pushing back on logs and such and need something that fully steps through the items and provides good information around it. There does not seem to be a lot of information around connecting to ESSBASE.

If we have an ESSBASE Server to connect to, I can write up documentation / blog around it.  Especially from an internal perspective for engineers on the Power BI Support Team, so that we know how to troubleshoot it better and understand how it works.

Tim



Timothy P Macaulay
SR. Support Escalation Engineer | Support Engineering – Business Intelligence & Application Platforms | Power BI CSS Support Team
Customer Services & Support | Microsoft Corporation
•(980) 776-7446; • timmac@microsoft.com<mailto:timmac@microsoft.com>
Hours: 12pm to 9pm EST
[cid:image001.png@01D52C67.26F17670]<https://www.linkedin.com/in/timothy-macaulay-7bb4b326/>
Manager: Brian Schumer – bschumer@microsoft.com<mailto:bschumer@microsoft.com> - +1 (425) 7069702
[cid:image003.jpg@01CDAD56.DC434040]

**Comment by anbuchelva** [comment]
That would really help. Appreciate it!

PS: I would never respond GitHub issue from my email, even if I do I wouldn't do it with signature on.

**Comment by msfttimmac** [comment]
:-D Thank you for the info!

**Comment by anbuchelva** [comment]
I have never used PBI before and I tried to get it working during Dec when the Essbase connector was available. Then I moved to different company where a different BI tool is being used. It has a connector for Essbase.

This is my understanding (might be entirely wrong) on PBI with Essbase.

The way smart view (the excel add-in for essbase related products) works is entirely different from PBI. First it queries the meta data on each dimensions. Once the user setup the point of view (a specific intersection that they want to query) then they hit refresh. This will query essbase for a small set of data, would be faster. When they drill down to next level, smart view queries the essbase for next set of data. The speed of getting data depends on what generation they use, whether the cube is BSO/ASO, whether the member property is store / dynamic calc, etc.,

But PBI tries to query the entire database and tries to store in the dashboard (similar to Import method), mostly it reaches some GB. So the essbase server crashes. It worked only when the database is small. PBI might always work on Direct Query method, instead of Import method. This would help in two ways.

1. The query / the data transfer would be small and fast on each dashboard.
2. No need to maintain the security setup in two places (i.e. essbase and PBI).

__Ignore typos, as it was sent from mobile__

**Comment by msfttimmac** [comment]
Good info!  At this point, I am simply trying to connect using XMLA, which appears to be the only way to connect to an ESSBASE Server.  Once connected, should be able to use DQ and Native Query to be able to work with the data.  But getting connected seems to be the first issue to overcome.
