### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by tripleacoder** [MicrosoftDocs/powerbi-docs#541]
The Streaming dataset matrix does not show PushStreaming, only Push, Streaming and PubNub, why is that?

Also, PushStreaming is called Hybrid when you go to Power Bi and look at the list of Datasets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-real-time-streaming)
* Content Source: [powerbi-docs/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-real-time-streaming.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @tripleacoder. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com. 

We'll also look at updating the docs, if they are not correctly reflecting the UI.
