### ISSUE TITLE
Ability to add a column in Desktop PBI when connected to Live Power BI Dataset in the cloud

### ISSUE THREAD

**Issue by jpuncochar** [MicrosoftDocs/powerbi-docs#544]
I can only add a measure, would love to be able to add a column, which is a little more user friendly than add a measure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @jpuncochar and thanks for your feedback. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com. .
