### ISSUE TITLE
"app owns data" with app secret/service principal

### ISSUE THREAD

**Issue by tripleacoder** [MicrosoftDocs/powerbi-docs#561]
Is it possible to authorize an "app owns data" application with a service principal instead of a user (by using an app secret instead of a password)?
I have tried to do it, but I get 401 errors when I try to push data to Power BI.

If it's not possible, then I think this documentation should mention it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by davidiseminger** [comment]
Thanks for your comment, @tripleacoder. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 

If you find the definitive answer, and would like us to update the docs with your findings, feel free to open this PR back up with the details.
