### ISSUE TITLE
For Published Apps, URL Filter only works for IE 11

### ISSUE THREAD

**Issue by dejadee** [MicrosoftDocs/powerbi-docs#588]
Using URL parameters to filter a report works for reports in workspaces--where the URL is in the form of:
https://app.powerbi.com/groups/___/reports/___/ReportSection?filter=____

However, when the URL is for a published app, the filtered URL only works in the IE 11 browser. It does not work in Chrome or Microsoft Edge. That is, when the URL looks like:
https://app.powerbi.com/groups/me/apps/___/reports/___/ReportSection?filter=___

This documentation should note that reports in workspaces and reports in published apps do not have the same behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @dejadee . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @dejadee -- I've checked with the product team. They point out a clarification I need to add to the article: 
Links to reports in an app have a query parameter (ctid) that gets added to the URL. Query parameters need to be separated by &’s. So you need to append the query with “&filter=” (after the ctid parameter) instead of “?filter=”. Like this:
app.powerbi.com/groups/me/apps/<app-id>/reports/<report-id>/ReportSection
?ctid=xxxxxxxxxxx&filter=Table~2FName%20eq%20%27A%27

**Comment by jburns157** [comment]
Hi Maggie,

After about an hour of trying to get this to work, I have failed!  I do not see any "ctid" generated when I look at a link to a Power BI app.  Thus, I don't know where / how to append the code you discuss above.  We are not running Premium.  Can you please advise how / where to find the CTID?  Or, if it's not visible, how it can be found?  Here is the link when the app loads:

https://app.powerbi.com/groups/me/apps/c1d03b08-8706-47a7-8da6-a5294697d87a/reports/4f336567-1c3f-44b1-bf6e-c0e5a7acc419/ReportSection00b3a19702d303247519

**Comment by maggiesMSFT** [comment]
Hi, @jburns157 -- Hmmm, agreed, that's a puzzle. I just tried creating a query string for a report in an app. The URL didn't have 'ctid' in it either. So I created the URL without the ctid and it worked fine. Try that.
Meanwhile I'll check some more.
thx!

**Comment by jburns157** [comment]
Hi!  Thanks for helping.  When you say that you built the URL without the ctid, does that mean (for the below link), that you chopped off the last section that happens after "ReportSection"?  And are you using the "?" or the "&"?  

https://app.powerbi.com/groups/me/apps/c1d03b08-8706-47a7-8da6-a5294697d87a/reports/4f336567-1c3f-44b1-bf6e-c0e5a7acc419/ReportSection00b3a19702d303247519

Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @jburns157  -- I used the ? because you only need the & to separate parameters, and I had only one. So it was:
ReportSection5?filter=<Table-Name>/<field-name> eq 'value'
But now I'm wondering. I created the app myself from an app workspace, so even though I'm viewing it in the app, it may not be acting as it would if the app were shared with me. Need to check.

**Comment by maggiesMSFT** [comment]
Oh! Git very helpfully removed the text because I put it in brackets. Here it is:
ReportSection5?filter=_table-name/column-name_ eq 'value'
see if that shows up better

**Comment by jburns157** [comment]
Hi Maggie,

I'm sorry for the delayed response!  I just got back to my desk.  I have tried this and it does not work, sadly.  The browser just routes back to app.powerBI.com.  

I have pondered if the random string in the URL that comes after "ReportSection" might be the culprit, but I have not been able to figure it out.

**Comment by maggiesMSFT** [comment]
Hi, @jburns157 -- yup, it was because I was the author. When I tried same with a report in an app I couldn't edit, I did indeed get the ctid. And when I added it after the ?filter = part, it worked. Like this:
https://app.powerbi.com/groups/me/apps/_app-id_/reports/_report-id_/ReportSection3?filter=_Table/field_ eq '_value_'&ctid=_ctid_

**Comment by jburns157** [comment]
Hi @maggiesMSFT , I just tested this extensively.  Very strange - it worked a single time for me.  After the initial success, it repeatedly fails now.  When I click the link now, it shows the proper URL, thinks for a millisecond, and then replaces the URL with the "?filter" logic with just app.powerbi.com, and it loads a blank page.  I took my test user out of all workspaces - all the user has access to is the app itself.

**Comment by maggiesMSFT** [comment]
Hi, @jburns157 -- hmmm. Sounds like time to hit up the community and/or support sites, I'm afraid. 
https://community.powerbi.com/ and https://powerbi.microsoft.com/en-us/support/

**Comment by mcsmith3** [comment]
Has this been updated to work in Chrome or Firefox?

**Comment by jburns7744** [comment]
Hi there mcSmith3, I am not sure about Firefox... but I can tell you that it is working great for me on Chrome.  Seems like the problem just went away for me.
