### ISSUE TITLE
Barcode scanner for field, in android

### ISSUE THREAD

**Issue by keradin** [MicrosoftDocs/powerbi-docs#601]
Can we expect the great functionality of mobile Power BI, also for android smartphones?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a19d0436-4c82-5830-5ad6-3cc8b4281ff5
* Version Independent ID: fc73c232-b9a5-e0db-e013-838d955a22d0
* Content: [Scan a barcode with an iPhone from the Power BI mobile app - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-scan-barcode-iphone)
* Content Source: [powerbi-docs/consumer/mobile/mobile-apps-scan-barcode-iphone.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-apps-scan-barcode-iphone.md)
* Service: **powerbi**
* GitHub Login: @mshenhav
* Microsoft Alias: **mshenhav**

**Comment by mshenhav** [comment]
This is under review currently.

**Comment by mgblythe** [comment]
Thanks for your comment, @keradin. This looks like a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, at https://community.powerbi.com.
