### ISSUE TITLE
Supported for ADX/Kusto queries?

### ISSUE THREAD

**Issue by morgangrobin** [MicrosoftDocs/powerbi-docs#604]
Is this feature supported for Azure Data Explorer/Kusto queries? When I try to use incremental refresh with an ADX query, the oldest row is always deleted if it no longer exists in the source database, even though I have only set incremental refresh to refresh the last 1 day

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* GitHub Login: @christianwade
* Microsoft Alias: **chwade**

**Comment by maggiesMSFT** [comment]
Hi, @morgangrobin -- Thanks for your comment.  I've assigned it to the author, but it looks more like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
