### ISSUE TITLE
Numeric slicer unnecessarily shows values in between

### ISSUE THREAD

**Issue by markus-zhang** [MicrosoftDocs/powerbi-docs#622]
Hi experts,
I'm confused about this anti-feature, basically I have a column of fixed dates like this:
2018-11-01
2018-11-08
...
But if I put up a slicer on this column, all dates are shown.
Did I do anything wrong? Why would I want to see all values in between?
Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc558f3-8a74-7154-c048-2dd74ad4eb8a
* Version Independent ID: f84aa1a5-4bab-6f6d-a0ba-5040c0f5defb
* Content: [Use the numeric range slicer in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-slicer-numeric-range)
* Content Source: [powerbi-docs/desktop-slicer-numeric-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-slicer-numeric-range.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @markus-zhang and thanks for your question. Thanks for your comment, @[github person who posted]. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
