### ISSUE TITLE
Needs updated to reflect Workspace 2.0

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#627]
Needs updated to reflect Workspace 2.0 where O365 Groups are not used and Edit screens change/differ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19005ba4-1b45-4a5e-2335-3408eaaffbf5
* Version Independent ID: 3587ce6f-8a2f-34c4-e00b-c28985833249
* Content: [Manage your app workspace in Power BI and Office 365 - Power BI](https://docs.microsoft.com/en-us/power-bi/service-manage-app-workspace-in-power-bi-and-office-365)
* Content Source: [powerbi-docs/service-manage-app-workspace-in-power-bi-and-office-365.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-manage-app-workspace-in-power-bi-and-office-365.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @pcgeekus -- thanks for your comment! This article isn't updated yet because workspaces 2.0 are still in preview. That's why this article has that Note at the top linking to the article about the new workspaces. When the new workspaces are generally available (GA), we'll update all the docs to reflect that. I for one can't wait! 
Thanks again!

**Comment by pcgeekus** [comment]
Any idea when it will go GA?
