### ISSUE TITLE
R package

### ISSUE THREAD

**Issue by almartinezos** [MicrosoftDocs/powerbi-docs#629]
Hi. The R package smooth is very useful to forecast time series with mobile average model. Do you have planned to introduce it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#r-scripts-that-are-not-supported-in-power-bi)
* Content Source: [powerbi-docs/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-r-packages-support.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @almartinezos and thanks for the suggestion. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
