### ISSUE TITLE
New build silently released: 2.65.5313.1381 64-bit (December 2018) 

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#639]
I just noticed there is a new build of Power BI Desktop that was silently released (not prompting to update, no info in blog).  It's dated 16 Jan 2019, but Options/Diagnostics shows: 2.65.5313.1381 64-bit (December 2018).  By my count that's at least the 4th build released labelled "December 2018" - some kind of record. 

I haven't done much with it yet but it hasn't obviously broken (or fixed) anything ... can anyone share any insight?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6a76e2-8d94-5e76-bfb6-971c3b2c7c85
* Version Independent ID: f7bd2111-3bb0-fb08-0f23-a31efd407f66
* Content: [What's new in the latest Power BI Desktop update? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update)
* Content Source: [powerbi-docs/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Mike-Honey. We’ve forwarded your feedback to the writer, who should respond to this thread shortly.

**Comment by davidiseminger** [comment]
Well @Mike-Honey - that's probably an issue we need to look into. Adding another assignee to ferret that out and see what's happening. Thanks for posting!

**Comment by amandacofsky** [comment]
Hey @Mike-Honey usually when we release new builds but don't announce anything, it means the release has some minor bug fixes we didn't want to wait for the next month to ship. In the case of December, there was more than normal since we didn't do a Jan release of Power BI Desktop. You can always update if you want, but assuming you weren't hitting any issues, you don't HAVE to update. You could wait until the next monthly major release.
