### ISSUE TITLE
Capability to rename the title

### ISSUE THREAD

**Issue by jainn4** [MicrosoftDocs/powerbi-docs#648]
Hi, 

This is more of a feedback. Can we add the functionality of renaming the title of each filter to make it more meaningful for the end user (assuming you already don't have it on your roadmap 👍 

Thanks
Nishant

**Comment by kfile** [comment]
Hi @jainn4  and thanks for the feedback. You've reached the documentation team. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
