### ISSUE TITLE
CredSSP and Failed Deployment

### ISSUE THREAD

**Issue by mhaarbrink** [MicrosoftDocs/powerbi-docs#653]
This doesn't seem to be working anymore.  Marketplace offering has been trying to deploy for almost 2 hours without success. 
 Looks to be hung up on the REPORTVM/configureRSServer extension.

Deployed the VM's directly from their gallery image reference without the extensions to see what might be going on and ran into the CredSSP issue.  I was connecting from a patched Windows 10 system, so it looks like the gallery images are not updated with the CredSSP patch, preventing me from logging in from a patched system.  I implemented the registry change to unsecure my system and was able to connect.

Has anyone deployed this recently with success?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c7b5d6-c9a4-3445-81c1-41dc41ae0929
* Version Independent ID: a45e9b8a-185b-ff29-dc4a-b8912c13ed1b
* Content: [Tutorial: Explore Power BI Report Server in a VM - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/tutorial-explore-report-server-web-portal)
* Content Source: [powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by Prezentter** [comment]
I was having the same issue. When I tried to login, it just said "An authentication error has occurred. The function request is not supported. This could be due to CredSSP encryption oracle remediation."

The steps to fix this were detailed at https://support.microsoft.com/en-au/help/4295591/credssp-encryption-oracle-remediation-error-when-to-rdp-to-azure-vm

The most common scenario is that the client has the CredSSP update installed, and the Encryption Oracle Remediation policy setting does not allow an insecure RDP connection to a server that does not have the CredSSP update installed.

To work around this issue, follow these steps:

On the client has the CredSSP update installed, run gpedit.msc, and then browse to Computer Configuration > Administrative Templates > System > Credentials Delegation in the navigation pane. 
Change the Encryption Oracle Remediation policy to Enabled, and then change Protection Level to Vulnerable.

Once I did these steps, I could login using the RDP connection, no problems.

It'd be great if it just worked instead of having to spend time figuring out all these issues!

**Comment by Prezentter** [comment]
Spoke too soon! I can connect to the VM, but the VM has nothing in it. The Desktop just has a recycle bin and a "SQL Server getting started" IE icon. It seems this VM needs updating as it doesn't work!!

**Comment by mhaarbrink** [comment]
The fix you mentioned is what I did as well.  But that means I have to change the registry to allow my computer to connect to insecure systems.  Which means the gallery image used in this deployment is _not_ running the patch for this.

The reason the VM is empty, I believe, is because that final script that is kicked off by the last extension in the ARM template is failing.  The ARM template builds the VM from a SQL server image and then runs a script to finish the configuration.  So it has SQL but no configuration as the instructions suggest should be there.

**Comment by mhaarbrink** [comment]
For more reference, here is the error from the deployment:
{ "id": "/subscriptions/f91cf6ff-d439-414d-90cd-6e9e809d3f0b/resourceGroups/PowerBIReporting/providers/Microsoft.Resources/deployments/reportingservices.technical-preview-20190201144555/operations/B8BAB3356C173973", "operationId": "B8BAB3356C173973", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-02-01T23:45:42.9603153Z", "duration": "PT1H30M18.0501445S", "trackingId": "054143c8-4e83-43e5-aed4-c57a9d84080d", "statusCode": "Conflict", "statusMessage": { "status": "Failed", "error": { "code": "ResourceDeploymentFailure", "message": "The resource operation completed with terminal provisioning state 'Failed'.", "details": [ { "code": "VMExtensionProvisioningTimeout", "message": "Provisioning of VM extension 'configureRSServer' has timed out. Extension installation may be taking too long, or extension status could not be obtained." } ] } }, "targetResource": { "id": "/subscriptions/f91cf6ff-d439-414d-90cd-6e9e809d3f0b/resourceGroups/PowerBIReporting/providers/Microsoft.Compute/virtualMachines/REPORTVM/extensions/configureRSServer", "resourceType": "Microsoft.Compute/virtualMachines/extensions", "resourceName": "REPORTVM/configureRSServer" } }}

The total deployment attempt was 1 hour 59 minutes.  The configureRSServer extension was 1 hour 30 minutes before it finally failed.

**Comment by Prezentter** [comment]
Thanks for the info. Do you know if it's possible to manually kick off the extension that's failing?  Or is this something that MS needs to fix in their VM script? Thanks

**Comment by maggiesMSFT** [comment]
Hi @mhaarbrink @Prezentter -- thanks for asking! I'm investigating and will reply back when I have an answer. 
thanks again --

**Comment by mhaarbrink** [comment]
@maggiesMSFT We have an email conversation going on with Matt Goswell of Microsoft also.  You may ping him internally and see if he's come up with anything yet.  We sent him the link to this document and open issue.

**Comment by sagardafle** [comment]
Hi @mhaarbrink  and @Prezentter , 

So we tested against a new VM and we could log into it from a patched machine.
We pulled the logs- it goes through and installs the update too. 
The extensions are what configure and domain join and set up the security patch so you can’t do this without the extensions, that is what caused you to have a non-patched machine.
The net time to deploy one machine from the image was 35 mins including the configureRSServer step. Another machine took 41 mins.
So the machine not deploying might be a one-off. Potentially you need to redeploy to fix it.
The other thing you mention about the VM not having anything, that’s because the extensions didn’t run as well. The PowerShell scripts install the server and configure it and upload the sample reports. Without this, you have a new blank VM.

Please let us know if you still face any issues. Thank you.
- Sagar (MSFT)
