### ISSUE TITLE
Windows Feature Installs and .NET 3.5

### ISSUE THREAD

**Issue by jzetterman** [MicrosoftDocs/powerbi-docs#77]
NET-Framework-Features requires that you set the -Source parameter to D:\Sources\SXS (assuming that's where your Windows ISO is mounted). Without this the entire feature install fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90025eee-cd72-9503-6c1d-c14bb617b5b4
* Version Independent ID: 58e25db4-5d25-ac1d-b763-72d27e943373
* Content: [Host Excel workbooks using Office Online Server (OOS) - Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/excel-oos)
* Content Source: [powerbi-docs/report-server/excel-oos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/excel-oos.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@jzetterman Thank you for your feedback.  We are currently looking into this information.

**Comment by jzetterman** [comment]
Thanks. As an FYI, I wrote the following PowerShell to get around the issue, by installing each feature one at a time.

`$array = @('Web-Server','Web-Mgmt-Tools','Web-Mgmt-Console','Web-WebServer','Web-Common-Http','Web-Default-Doc','Web-Static-Content','Web-Performance','Web-Stat-Compression','Web-Dyn-Compression','Web-Security','Web-Filtering','Web-Windows-Auth','Web-App-Dev','Web-Net-Ext45','Web-Asp-Net45','Web-ISAPI-Ext','Web-ISAPI-Filter','Web-Includes','NET-Framework-Features','NET-Framework-45-Features','NET-Framework-Core','NET-Framework-45-Core','NET-HTTP-Activation','NET-Non-HTTP-Activ','NET-WCF-HTTP-Activation45','Windows-Identity-Foundation','Server-Media-Foundation')

ForEach ($item in $array) {
  $InstallStatus = Get-WindowsFeature | Where-Object {$_.Name -eq $item}
  If ($InstallStatus.InstallState -eq 'Installed') {
    Write-Host "$item is installed!" -ForegroundColor Green
  } else {
    Write-Host "$item is NOT installed! Installing now..." -ForegroundColor Red
    Add-WindowsFeature -Name $item -Source D:\Sources\sxs
  }
}`

**Comment by jzetterman** [comment]
`test`

**Comment by markingmyname** [comment]
@jzetterman Thank you for the information about using PowerShell. However, since this is around the OOS install – this isn’t an RS-specific issue. Instead, it’s specific to Office Online Server and would be an issue with the install of that whether for SharePoint or PBI RS. 

Here are articles describing how to install OOS and how to configure it with SP just for further reference:

OOS install - https://docs.microsoft.com/en-us/exchange/plan-and-deploy/install-office-online-server 

Configure with SP - https://docs.microsoft.com/en-us/officeonlineserver/configure-office-online-server-for-sharepoint-server-2016/configure-office-online-server-for-sharepoint-server-2016

Hope this helps.

Thank you.
