### ISSUE TITLE
Incremental Refresh - Issue

### ISSUE THREAD

**Issue by Pulendarvadde** [MicrosoftDocs/powerbi-docs#791]
I have SQL server data model. My fact table is not having date filed to declare getStartDate or end date. I only have a time dimension table which is connect to fact based on time key.
Please let me know, how can I use incremental refresh.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* GitHub Login: @christianwade
* Microsoft Alias: **chwade**

**Comment by mgblythe** [comment]
Thanks for your comment, @Pulendarvadde. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

CC: @christianwade @Minewiskan
