### ISSUE TITLE
you will want to fine the Authentication/AuthenticationTypes section.

### ISSUE THREAD

**Issue by hiteshgaur** [MicrosoftDocs/powerbi-docs#824]
change to 
you will want to find the Authentication/AuthenticationTypes section.

for file [powerbi-docs/powerbi-docs/report-server/configure-kerberos-powerbi-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/configure-kerberos-powerbi-reports.md)

**Comment by kfile** [comment]
Thanks for your feedback, @hiteshgaur ! Did you know that because our docs are in GitHub, you can edit them yourself? For a fix like this, please select the Edit pencil at the top-right on this page, make the change yourself, and submit it. OK? Then the author can review it and accept it. 
Thanks again for your help in improving the docs!

**Comment by hiteshgaur** [comment]
Thank you Kelly, I tried the pencil, but it forked out the repo for me. :) 
Happy Friday !!
