### ISSUE TITLE
Clone Tile in Group fails for New Workspace

### ISSUE THREAD

**Issue by Saltzmea** [MicrosoftDocs/powerbi-docs#844]
I can't clone the tiles into a new workspace. I get the following error when using the clone tile in group api: 

Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

**Comment by markingmyname** [comment]
Thanks for your comment, @Saltzmea. 

Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
