### ISSUE TITLE
How and Where security updates are delivered for previous releases ?

### ISSUE THREAD

**Issue by VinitashokPatil** [MicrosoftDocs/powerbi-docs#845]
Referring to documentation on this page, requesting to confirm understanding on 
a) where to look for the security updates and download them for PBIRS.  
b) Does the 'change log' list all the security updates that have been released so far ? there are not any listed since beginning of 2018. 
c) Are there no security updates ? 
d) or are they clubbed into the updates ?
e) Also is there a more detailed bug / issue fix list maintained any where or only what is listed under change log ?

Above queries are in context of text at the start of this page:
"After the next release, the previous release continues to receive security updates for the remainder of the 12-month release lifespan"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b388ff1b-9b08-2ac3-bb06-125115c96758
* Version Independent ID: f7b5f58c-9219-e9f8-2b3f-ae39b0c278f3
* Content: [Support timeline for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/support-timeline#feedback)
* Content Source: [powerbi-docs/report-server/support-timeline.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/support-timeline.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@VinitashokPatil

Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
a) Where to look for the security updates and download them for PBIRS.

Response: Currently, they come with the new release of PBI RS.

b) Does the 'changelog' list all the security updates that have been released so far? There are not any listed since the beginning of 2018.  

Response: The last updates were done in January of 2019

c/d) Are there no security updates, or are they clubbed into the updates?

Response: Clubbed into the updates.

d) Also is there a more detailed bug/issue fix list maintained anywhere or only what is listed under change log ?

Response: Currently, the [Change Log](https://docs.microsoft.com/en-us/power-bi/report-server/changelog) article is the official location for this info.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

**Comment by VinitashokPatil** [comment]
Thank You!
I appreciate the inputs provided.
