### ISSUE TITLE
Will the ability to leverage the on-premises data gateway using the service principal be added to the solution?

### ISSUE THREAD

**Issue by amwidi77** [MicrosoftDocs/powerbi-docs#859]
Will the ability to leverage the on-premises data gateway using the service principal be added to the solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thanks for your comment, @amwidi77.  Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
