### ISSUE TITLE
Feature Request- Cosmos DB Direct Query

### ISSUE THREAD

**Issue by jcbendernh** [MicrosoftDocs/powerbi-docs#870]
Would love to see Azure Cosmos DB as a data source for Power BI Direct Query for many IoT Ingestion for more complex scenarios were Stream Analytics to Power BI does not suffice.

**Comment by mihart** [comment]
Thanks for your comment, @jcbendernh . This looks like product feedback rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team at https://community.powerbi.com.
Take care,
The DOCS team
