### ISSUE TITLE
Group Policy to disable Custom Connectors

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#881]
Is there an option for IT admins to disable the option to enable custom connectors, similar to the option to disable custom visuals and the sign up check using group policy? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db81b-e91f-c1c8-7062-eb8bd5920eb9
* Version Independent ID: 63ba058e-817c-3b82-767b-5f94d8204e5b
* Content: [Connector Extensibility in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connector-extensibility)
* Content Source: [powerbi-docs/desktop-connector-extensibility.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connector-extensibility.md)
* Service: **powerbi**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by mgblythe** [comment]
Thanks for your comment, @klinejordan. This looks like a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, at https://community.powerbi.com.
