### ISSUE TITLE
The asp.net core sample doesn't work

### ISSUE THREAD

**Issue by melzoghbi** [MicrosoftDocs/powerbi-docs#894]
Hi, I downloaded the sample asp.net core application and it doesn't work, specially the login and the redirect doesn't redirect to the home page as set in the app settings or AAD app settings. I am not able to submit an issue in the GitHub repo either!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505b774c-e4e2-78b0-dad9-ae19c9240004
* Version Independent ID: a5dac00f-35c2-a87d-3224-c96682d2ffb7
* Content: [Embedded analytics to embed Power BI content in your application for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization)
* Content Source: [powerbi-docs/developer/embed-sample-for-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-your-organization.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@melzoghbi Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
Thanks for your comment, @melzoghbi.  This looks like a support request rather than documentation feedback – you can get support by going to https://support.powerbi.com. You might find a solution in the Power BI Community, found at https://community.powerbi.com.

However, you can also log product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. We truly appreciate your contribution to our articles.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
