### ISSUE TITLE
RLS in SSAS Tabular showing different result compare to the same model in Power BI Desktop

### ISSUE THREAD

**Issue by dunganhle** [MicrosoftDocs/powerbi-docs#971]
Hi,

As saying in the title, I have the exact model that runs in SSAS Tabular And Power BI Desktop and having different result.

Let me know how can I show you the issue ( the 2 roles I have are like below in both solution, an AD group of users belong to these roles) :
UserRole1:
'Customer'[CurrentSalesUnitKey_SharedAccount_01] = 
LOOKUPVALUE(
'AD-Territory'[Value],
'AD-Territory'[UserName],
USERPRINCIPALNAME(),
'AD-Territory'[Value],
'Customer'[CurrentSalesUnitKey_SharedAccount_01]
)
&&
NOT ISBLANK('Customer'[CurrentSalesUnitKey_SharedAccount_01])
&&
'Customer'[CurrentSalesUnitKey_SharedAccount_01] <> ""

UserRole 2:
'Customer'[CurrentSalesUnitKey_SharedAccount_02] = 
LOOKUPVALUE(
'AD-Territory'[Value],
'AD-Territory'[UserName],
USERPRINCIPALNAME(),
'AD-Territory'[Value],
'Customer'[CurrentSalesUnitKey_SharedAccount_02]
)
&&
NOT ISBLANK('Customer'[CurrentSalesUnitKey_SharedAccount_02])
&&
'Customer'[CurrentSalesUnitKey_SharedAccount_02] <> ""

**Comment by davidiseminger** [comment]
Hello @dunganhle  - thanks for posting. The information about the article about which you're asking was deleted from your post, so we can't see which article you're posting about. 

Also, this looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
