### ISSUE TITLE
Flexibility to only show specific filter type to End Users

### ISSUE THREAD

**Issue by mannsandhu** [MicrosoftDocs/powerbi-docs#984]
There should be flexibility given to report author to restrict end user to see any specific filter type in filter pane. For e.g. If end user should see only filter on the page level or report level but should not see filters applied to a visual then it should be controlled at report author level.
Currently when any visual is selected in the Power BI services, end user will see all visual level filters applied to that visual. Even after hiding these visual level filters they can be seen. 
NOTE: When any filter has some pre-defined condition selected then if we hide this filter, end user will not be able to see this filter completely.

**Comment by mgblythe** [comment]
Thanks for your comment, @mannsandhu . This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
