### ISSUE TITLE
Cohort not working

### ISSUE THREAD

**Issue by vikram-relyfy** [MicrosoftDocs/powerbi-docs#987]
In the current version of Google Analytics connector for the Power BI desktop doesn't support cohort dimensions and metrics.
When I select User Retention metrics and cohort dimension, it tells that ga:cohortuserretentionrate is not supported in this API version.
If this could be fixed, that would be great to show my user retention.
If any other alternative is available I'm interested in that too.
Thank You

**Comment by mgblythe** [comment]
Thanks for your comment, @vikram-relyfy. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
