### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by RevengeIsOurs** [MicrosoftDocs/powerbi-docs#994]
After conditional formatting, how do we get a legend to appear on the visual?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-conditional-table-formatting#feedback)
* Content Source: [powerbi-docs/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
Hi @RevengeIsOurs,

Thanks for your comment, @[github person who posted]. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
