### ISSUE TITLE
Billing Profile ID

### ISSUE THREAD

**Issue by jzuchora87** [MicrosoftDocs/powerbi-docs#995]
"You can get your billing profile ID from the Azure portal. Navigate to Cost Management + Billing, select your billing account, and then select Biling profiles in the sidebar. Select your billing profile and select Properties in the sidebar. Copy your billing profile ID."

Can you please update the doc on how to accurately find the billing profile id? I'm an EA customer and the profile ID I see in the portal is just our current EA number. Also when I try to enter the billing profile id (our EA number) into PowerBI get an error "TenantId: Failed to discover tenantsBillingAccountId: Failed to discover tenants" and I'm not the only one: https://community.powerbi.com/t5/Desktop/Using-new-Azure-Cost-Management-Connector-issues-with-Account-ID/td-p/645034

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure cost and usage from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @jzuchora87 -- thanks for your comment! I've referred it to the author, who'll get back to you.

**Comment by awentzel** [comment]
I'm on the actual Microsoft Corporate tenant for AIRS and there is no left bar Billing Profile option. In fact. I would suggest updating the documentation to reference the current Azure Portal User interface nomenclatures.  For example, i don't see the term "Billing Account" anywhere.  It appears instead the Billing account may correlate to the Subscription.  Select the Subscription and then you can see cost details.  

**Cost Management + Billing - Overview page**
![Screen Shot 2019-05-31 at 11 46 22 AM](https://user-images.githubusercontent.com/16669785/58727650-c4699700-8399-11e9-9e41-713a7d18bec3.png)

**The named Subscription - Overview page (not billing account) Subscription**
 ![Screen Shot 2019-05-31 at 11 46 37 AM](https://user-images.githubusercontent.com/16669785/58727649-c4699700-8399-11e9-8a25-5eba8e62c23d.png)

**Comment by awentzel** [comment]
Additionally, when connecting to Azure Cost Management the "Billing Profile ID" isn't a think on Azure Portal so it's confusing. The watermark hint shows what is really a subscription id.  Here I recommend calling it Azure Subscription Id rather than Billing Profile Id.

![Screen Shot 2019-05-31 at 11 48 59 AM](https://user-images.githubusercontent.com/16669785/58727806-317d2c80-839a-11e9-9108-eb9e199dcc50.png)

**Comment by sbhuttan** [comment]
Subscription Id is not the right answer here either. As using subscription id throws this error "TenantId: Failed to discover tenantsBillingAccountId: Failed to discover tenants", as another user mentioned above.

**Comment by DiegosilveiraIT** [comment]
Hi,

I had the same  issue and in contact with Microsoft, they share with me a similar connector that could be used.

The explain that exists a difference between a kind of your contract that you have in your enviroment. Please, see the below documentation:



 https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#connect-with-azure-consumption-insights

**Comment by awentzel** [comment]
@DiegosilveiraIT, It was a good idea.  Except when using this connect it then asks for "Enrollment ID", which is only valid on Enterprise Subscription.  So while that may help those subscription types, it doesn't help mine.  I'd recommend to Microsoft that it should be a value that can be used that applies to all subscriptions.  Using different connectivity methods is confusing to the community and will be challenging to document accurately.

**Comment by davidiseminger** [comment]
Thanks for all the feedback, adding @shilpiguatam who can help resolve the best way to clarify the documentation.

**Comment by mgblythe** [comment]
@davidiseminger - assigning back to you to follow up with Ben Shy. I can't get his GitHub handle (@BenShy) to resolve here.

**Comment by ahughes257** [comment]
I have the same issue - cant see a billing id within costmanagement + billing.
This would be a much simpler connection if we can just sign into Azure; then any cascaded permissions on cost management are pulled through from the azure account to PowerBI

**Comment by davidiseminger** [comment]
I've reported this to our engineering team, and will work with them to get the updates taken care of. Sorry for the inconvenience.

**Comment by eosho** [comment]
+1 on this.

**Comment by Chai-NED** [comment]
+1, I need the Billing Profile ID to show up in my Azure portal please.

**Comment by davidiseminger** [comment]
Thank you for your input and feedback. Updates to this article are in the works, which will hopefully address all of these concerns and questions. Adding the owners of the updates and services. @bandersmsft

**Comment by bandersmsft** [comment]
@davidiseminger I'm getting Ben's input on this.

**Comment by bandersmsft** [comment]
First, there are currently two connectors: one supports EA, the other MCA. No other billing accounts are supported by either connector, so Microsoft internal account's aren't supported. We are in the process of splitting this article into two so that each one is specific to it's own connector. I expect the result will help prevent confusion.

The Azure Consumption Insights connector only supports EA agreements. The connector needs your Azure enrollment number and your API access key. Both are shown in the Azure EA portal, as described in the article.

The current Azure Cost Management (Beta) version of the connector only supports Microsoft Customer Agreements. To determine if you are under an Microsoft Customer Agreement **and have access to a billing account**, follow the steps outlined at [Check access to a Microsoft Customer Agreement](https://docs.microsoft.com/azure/billing/billing-mca-overview#check-access-to-a-microsoft-customer-agreement).  The connector needs your MCA **Billing Profile ID**. You can find the ID in Azure Cost Management, as described in the article.

BTW, upcoming updates to the Azure Cost Management connector will include support for Enterprise Agreement (EA) customers.  Until the update is available, Enterprise Agreement customers should continue using the Azure Consumption Insights connector.

##please-close

**Comment by rodneyjoyce** [comment]
Hi, I know this is an old thread and I get that the API only works for EA or MCA customers, but are there any plans to extend this to ALL subscription types? I am an MS Gold Partner and cannot use the API but I have a lot of subscriptions where cost management is important...

**Comment by awentzel** [comment]
It would also be helpful to know when updates are released so we can try this out again.  Thanks

**Comment by cloudstake** [comment]
Yes, would like an update too, thanks.

**Comment by csijake** [comment]
I am struggling to find ours as well - we are on the MS-AZR-0003P offer and I don't see this value anywhere in the portal.

Please update the documentation for the top 5 most used subscription offers so that folks can find this!
